Repository decentraland/unity-renderer, pull requests merged in 2021-08, with the labels that each got.

#879 fix: TextMeshPro materials used by TextShape are not properly destroyed
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
Labels: ready for review

#857 refactor: AssetBundle and GLTF AssetLibrary
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetLibrary_AB_GameObject.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/APK_AB_GameObject_Promise_Should.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetLibrary_Poolable.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Tests/AssetLibrary_Poolable_Should.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Tests/AssetLibrary_Poolable_Should.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetLibrary_GLTF.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/AnyAssetPromiseShould.cs
Labels: ready for review

#872 feat: disable SSAO for far-away avatars
  unity-renderer/Assets/Rendering/Common/Resources/ShaderVariantCollections/shadervariants-selected.shadervariants
  unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/DCLSimpleLighting.hlsl
  unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/ToonShaderCompiled.shader
  unity-renderer/Assets/Rendering/Shaders/Toon/Master_ToonShader.shadergraph
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/WearableController.cs
Labels: ready for review

#898 chore: exclude tests, ABConverter and WSSController from code coverage
  ci-playmode-test.sh
Labels: ready for review

#901 chore: rename PlayerStatus to Player
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarNamesHUD/AvatarNamesHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarNamesHUD/AvatarNamesHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarNamesHUD/AvatarNamesTracker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarNamesHUD/Tests/AvatarNamesHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarNamesHUD/Tests/AvatarNamesHUDViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarNamesHUD/Tests/AvatarNamesHUDView_VisualTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/IUsersAroundListHUDListView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/Tests/UsersAroundListHUDShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUDListView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapUserIcon.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/Players/Player.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/Players/Player.cs.meta
Labels: ready for review

#913 fix: shadow resolution on Ultra is now 4096
  unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
Labels: ready for review

#915 feat: increased draw distance and updated quality presets, #880
  unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/DrawDistanceControlConfiguration.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/ScenesLoadRadiusControlConfiguration.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/QualitySettingsData.cs
Labels: ready for review

#917 fix: GLTF's AsyncCoroutineHelper coroutine runner
  unity-renderer/Assets/UnityGLTF/Scripts/Async/AsyncCoroutineHelper.cs
Labels: ready for review

#916 fix: AssetPromiseKeeper singleton
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromiseKeeper_AB.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromiseKeeper_AB_GameObject.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseKeeper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromiseKeeper_GLTF.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/AssetPromiseKeeper_Gif.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/AssetPromiseKeeper_Material.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetPromiseKeeper_Texture.cs
Labels: ready for review

#929 feat: correct biw flow with the shortcut
  unity-renderer/Assets/Scripts/MainScripts/DCL/Configuration/Configuration.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs
Labels: ready for review

#924 fix: Moving platforms now rotate character avatar and first person camera
  unity-renderer/Assets/Resources/ScriptableObjects/MovingPlatformRotationDelta.asset
  unity-renderer/Assets/Resources/ScriptableObjects/MovingPlatformRotationDelta.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateFPS.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Tests/CharacterControllerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/Variables/QuaternionVariable.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/Variables/QuaternionVariable.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/Variables/Tests/VariableTests.cs
Labels: ready for review

#908 feat: avatar lods transition
  unity-renderer/Assets/Materials/AvatarLOD.mat
  unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/ToonShaderCompiled.shader
  unity-renderer/Assets/Rendering/Shaders/Toon/Master_ToonShader.shadergraph
  unity-renderer/Assets/Rendering/Shaders/Toon/Toon Shader Dither.shadersubgraph
  unity-renderer/Assets/Rendering/Shaders/Toon/Toon Shader Dither.shadersubgraph.meta
  unity-renderer/Assets/Rendering/Utils/ShaderUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarLODController/AvatarLODController.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarLODController/AvatarLODController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarsLODController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarsLODControllerInterface/IAvatarsLODController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRendererInterface/AvatarRendererHelpers.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRendererInterface/AvatarRendererHelpers.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRendererInterface/AvatarRendererInterface.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRendererInterface/IAvatarRenderer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/ParticlesOnAvatarVisualCue.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/WearableController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/Players/Player.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/Players/PlayerModels.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/BaseComponent.cs
Labels: ready for review

#923 style: fix unique card gradient and loading item background
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/NFTItemToggle.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/Unique.prefab
Labels: ready for review

#927 fix: master promise never unloaded if forgotten with pending promises
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromise.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseKeeper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Mock/AssetPromise_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Mock/Tests/BlockedAndMasterPromisesShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/BlockedAndMasterPromisesShould.cs
Labels: ready for review

#925 fix: master promise cleaned or unloaded while waiting promises still exist
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseKeeper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Mock/AssetPromiseKeeper_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Mock/Tests/BlockedAndMasterPromisesShould.cs
Labels: ready for review

#938 feat: improve code coverage report
  ci-playmode-test.sh
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/SmartItem/SmartItemCommon/SmartItemCommon.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/ActionController/ActionAdapter.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/ActionController/ActionListview.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/Voxels/VoxelController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/Voxels/VoxelEntityHit.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/Voxels/VoxelPrefab.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/FirstPerson/BIWFirstPersonMode.cs
Labels: ready for review

#945 fix: Mute scene SFX when Backpack, BiW Editor or Tutorial is open
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioStream.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-renderer/Assets/Tutorial/Scripts/Tutorial.asmdef
  unity-renderer/Assets/Tutorial/Scripts/TutorialController.cs
Labels: ready for review

#874 fix: scene boundaries unit test
  unity-renderer/Assets/Scripts/MainScripts/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTInfoFetcher.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTInfoFetcher.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTInfoFectcherShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTInfoFectcherShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTShapeTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TestAssetsUtils/TestAssetsUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SBC_Asserts.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
  unity-renderer/Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs
  unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
  unity-renderer/Assets/UnityGLTF/Scripts/Loader/GLTFFileLoader.cs
  unity-renderer/Assets/UnityGLTF/Scripts/Loader/GLTFFileLoader.cs.meta
  unity-renderer/TestResources/NFT/nftImage.png
  unity-renderer/TestResources/NFT/nftInfo.json
Labels: ready for review

#942 feat: add more biw unit test
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/BIWGodMode.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/FreeCameraController/FreeCameraMovement.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/Modes/BIWGodModeShould.cs
Labels: wip

#946 Fix: pools instantiating additional objects when renderer was turned off
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Tests/PoolManagerTests.cs
Labels: ready for review

#949 fix: SendWebRequest retries system is blocking the async operation
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/WebRequestAsyncOperation.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestController.cs
Labels: ready for review

#967 fix: third person camera lens is now common
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Resources/CameraController.prefab
Labels: ready for review, merge me!

#974 chore: remove always-false codepath of indexed db
  unity-renderer/Assets/Plugins/DCL_CachedXHR/DCL_CachedXHR.jspre
Labels: ready for review

#982 chore: updates for new scheme
  .github/workflows/main.yml
  unity-renderer/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
Labels: ready for review

#983 chore: remove unused sendUserEmail message
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#989 fix: use desambiguated content server
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Catalyst.cs
Labels: ready for review, merge me!

#994 fix: TextShape showing "hello" when created
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
Labels: ready for review

#991 chore: replace old peer url
  unity-renderer/Assets/ABConverter/Tests/ABConverterCoreShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/BuilderProjectsPanelController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/ContentServerUtils/ContentServerUtils.cs
Labels: ready for review

#951 feat: add unit test to the BIW main controller
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldBridge/BuilderInWorldBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWEntityHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWFloorHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWModeController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWSaveController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/NFTs/BIWNFTController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWEntityHandlerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWMainControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWNftsShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BuilderInWorldTest.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/Helpers/BIWTestHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Utils/BIWUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DeployedScenesFetcher/LandWithAccess/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DeployedScenesFetcher/LandWithAccess/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DeployedScenesFetcher/LandWithAccess/DeployedScene.cs
  unity-renderer/TestResources/JsonEntity/NFTEntity.json
Labels: ready for review

#976 feat: biw add more unit test
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldInputWrapper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Gizmos/BIWGizmos.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Gizmos/BIWGizmosAxis.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Gizmos/BIWGizmosController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Gizmos/BIWGizmosRotate.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Gizmos/BIWScaleGizmos.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/BIWMode.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/FreeCameraController/FreeCameraMovement.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWFreeCameraShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWFreeCameraShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWGizmosShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWGodCameraShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWInputWrapperShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWScaleGizmosShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWScaleGizmosShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/Modes/BIWModeShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/Modes/BIWModeShould.cs.meta
Labels: ready for review

#997 fix: builder and builder in world use the same metrics
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs.meta
Labels: ready for review

#1015 chore: enable project settings that improve unity editor performance
  unity-renderer/Assets/Scenes/InitialScene.unity
  unity-renderer/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
  unity-renderer/ProjectSettings/EditorSettings.asset
Labels: ready for review

#1022 chore: add date and commit hash to npm package version
  browser-interface/scripts/build.ts
Labels: ready for review

#968 chore: max avatars lods
  unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/ToonShaderCompiled.shader
  unity-renderer/Assets/Rendering/Shaders/Toon/ShaderGraph/Master_ToonShader.shadergraph
  unity-renderer/Assets/Rendering/Shaders/Toon/ShaderGraph/Toon Shader Dither.shadersubgraph
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarLODController/AvatarLODController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarLODController/Tests/AvatarLODControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarsLODController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/Tests/AvatarsLODControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/MaxNonLODAvatarsControlController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore.cs
Labels: ready for review

#1032 fix: deformed avatar when backpack interrupts "head explode" emote
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRendererInterface/IAvatarRenderer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModel.cs
Labels: ready for review

#1036 fix: alpha and emission wearable issues
  unity-renderer/Assets/ABConverter/Client.cs
  unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/DCLSimpleLighting.hlsl
  unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/ToonShaderCompiled.shader
  unity-renderer/Assets/Rendering/Shaders/Toon/ShaderGraph/ColorspaceConversionWithAlphaPreservation.shadersubgraph
  unity-renderer/Assets/Rendering/Shaders/Toon/ShaderGraph/ColorspaceConversionWithAlphaPreservation.shadersubgraph.meta
  unity-renderer/Assets/Rendering/Shaders/Toon/ShaderGraph/GetUvEncodedAttributes.shadersubgraph
  unity-renderer/Assets/Rendering/Shaders/Toon/ShaderGraph/Master_ToonShader.shadergraph
  unity-renderer/Assets/Rendering/Shaders/Toon/ShaderGraph/TextureSample.shadersubgraph
  unity-renderer/Assets/Rendering/Shaders/Toon/ShaderGraph/ToonShader.shadersubgraph
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/AvatarMeshCombiner.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/AvatarMeshCombinerUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/CombineLayerUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/Tests/AvatarMeshCombinerUtilsCan.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Materials/Avatar Material.mat
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/VisualTests/WearablesVisualTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/Tests/Helpers/AvatarAssetsTestHelpers.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/Tests/Helpers/Resources/TestCatalogArrayLocalAssets.asset
  unity-renderer/Assets/Scripts/Tests/VisualTests/VisualTestsBase.cs
  unity-renderer/TestResources/Avatar/Assets/COLDIE_3D.glb
  unity-renderer/TestResources/Avatar/Assets/warrior.glb
  unity-renderer/TestResources/Avatar/TestCatalog.json
  unity-renderer/TestResources/VisualTests/BaselineImages/WearableVisualTests_AlphaBlendWearableWithTransparentBaseColor_0.png
  unity-renderer/TestResources/VisualTests/BaselineImages/WearableVisualTests_EmissiveWearableWithNoEmissionMap_0.png
Labels: ready for review

#992 fix: biw thumbnail bug
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/DropSceneObject.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/DropSceneObject/CatalogItemDropController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/DropSceneObject/CatalogItemDropController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/UI/Adapters/CatalogAssetGroupAdapter.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/UI/CatalogGroupListView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWCatalogShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/Helpers/BIWTestHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/BuildModeHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuildModeHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuildModeHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/Common/QuickBarController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/Common/SceneCatalogController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/DragAndDropSceneObjectController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/DragAndDropSceneObjectView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/BuildModeHUDViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/DragAndDropSceneObjectControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/QuickBarControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/Unpublish/UnpublishPopupController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/SceneAssets/SceneObject/SceneObject.cs
Labels: ready for review

#1027 feat: changed PR template to match the current link
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review

#1007 fix: biw analytics improvements
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Analytics/BIWAnalytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWPublishController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWCommonShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Utils/BIWUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/BuilderProjectsPanelController.cs
Labels: ready for review

#956 fix: UiShape now refreshes when screen size changes
  unity-renderer/Assets/Resources/Prefabs/Main.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/Tests/UIContainer.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/Tests/UIContainerStackTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ScreenController.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ScreenController/ScreenSizeWatcher.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ScreenController/ScreenSizeWatcher.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore.cs
  unity-renderer/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
Labels: ready for review

#1017 feat: fixed text models to be equals to their kernel counterpart
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/Tests/TextShapeTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIInputText/Tests/InputTextTestsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIInputText/Tests/UIInputTextTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIInputText/UIInputText.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIText/Tests/UITextTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIText/Tests/UITextVisualTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIText/UIText.cs
Labels: ready for review

#1004 feat: biw last final round of unit test
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/ActionController/BIWActionController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWPublishController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Gizmos/BIWGizmosRotate.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/BIWMode.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/BIWGodMode.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWRotateGizmosShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWRotateGizmosShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWTranslateGizmosShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWTranslateGizmosShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/Helpers/BIWTestHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/Modes/BIWGodModeShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/Common/SceneCatalogController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/SceneCatalogControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/BuilderProjectsPanelController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/ScenesController/SceneData.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/SectionController/MenuSections/SectionSceneAdminsSettingsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Tests/BuilderProjectsPanelControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Tests/SceneDataShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Tests/SceneDataShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Tests/SectionSceneAdminsSettingsShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DeployedScenesFetcher/LandWithAccess/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/SceneAssets/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/SceneAssets/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/SceneAssets/AssetCatalogBridge.cs
  unity-renderer/Assets/Scripts/Tests/TestHelpers.cs
Labels: ready for review

#1053 fix: biw publish photo is getting the correct camera
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/FreeCameraController/FreeCameraMovement.cs
Labels: ready for review

#1038 feat: implemented biw missing asset prefab collider
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWCreatorController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/MissingAsset.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/MissingAsset.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Prefabs/ErrorPrefab.prefab
Labels: ready for review

#1026 feat: implemented analytic for external link, NFTs and voicechat
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/NFTPromptHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/NFTPromptHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/VoiceChat/DCLVoiceChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/VoiceChat/VoiceChatController.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/AnalyticsHelper.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/AnalyticsHelper/AnalyticsHelper.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/AnalyticsHelper/AnalyticsHelper.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/AnalyticsHelper/AnalyticsHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/AnalyticsHelper/AnalyticsHelper.cs.meta
Labels: ready for review

#1051 fix: solve a null reference edge case in quest controller
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/QuestsController/QuestsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/QuestsController/Tests/QuestsControllerShould.cs
Labels: ready for review

#1090 fix: better mobile errors
  browser-interface/src/index.ts
Labels: bug, ready for review, regression, merge me!

#760 fix: improve gltf external texture caching
  unity-renderer/Assets/Resources/TestJSON/SceneLoadingTest.json
  unity-renderer/Assets/Resources/TestJSON/TestSceneSeveralParcels.json
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/GLTFImporterTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromise_GLTF.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromise_PrefetchGLTF.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/APK_GLTF_Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/GLTF_PromiseShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/GLTF_PromiseShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/ContentProvider.cs
  unity-renderer/Assets/UnityGLTF/Scripts/Cache/AssetCache.cs
  unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
  unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
  unity-renderer/Assets/UnityGLTF/Scripts/Loader/GLTFFileLoader.cs
  unity-renderer/Assets/UnityGLTF/Scripts/Loader/ILoader.cs
  unity-renderer/Assets/UnityGLTF/Scripts/Loader/WebRequestLoader.cs
  unity-renderer/Assets/UnityGLTF/Tests/GLTFBenchmark.cs
  unity-renderer/TestResources/GLTF/TextureSharingGLTF/Test.png
  unity-renderer/TestResources/GLTF/TextureSharingGLTF/cube.bin
  unity-renderer/TestResources/GLTF/TextureSharingGLTF/cube.gltf
  unity-renderer/TestResources/GLTF/TextureSharingGLTF/cylinder.bin
  unity-renderer/TestResources/GLTF/TextureSharingGLTF/cylinder.gltf
Labels: ready for review

#1002 fix: gltf download order
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromise_GLTF.cs
  unity-renderer/Assets/UnityGLTF/Scripts/DownloadQueueHandler.meta
  unity-renderer/Assets/UnityGLTF/Scripts/DownloadQueueHandler/DownloadQueueHandler.cs
  unity-renderer/Assets/UnityGLTF/Scripts/DownloadQueueHandler/DownloadQueueHandler.cs.meta
  unity-renderer/Assets/UnityGLTF/Scripts/DownloadQueueHandler/IDownloadQueueElement.cs
  unity-renderer/Assets/UnityGLTF/Scripts/DownloadQueueHandler/IDownloadQueueElement.cs.meta
  unity-renderer/Assets/UnityGLTF/Scripts/DownloadQueueHandler/Tests.meta
  unity-renderer/Assets/UnityGLTF/Scripts/DownloadQueueHandler/Tests/DownloadQueueHandlerShould.cs
  unity-renderer/Assets/UnityGLTF/Scripts/DownloadQueueHandler/Tests/DownloadQueueHandlerShould.cs.meta
  unity-renderer/Assets/UnityGLTF/Scripts/DownloadQueueHandler/Tests/DownloadQueueHandlerTests.asmdef
  unity-renderer/Assets/UnityGLTF/Scripts/DownloadQueueHandler/Tests/DownloadQueueHandlerTests.asmdef.meta
  unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
Labels: ready for review, merge me!

#1049 feat: AudioClip promise keeper
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioClip.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/AssetPromiseKeeper_AudioClip.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/AssetPromiseKeeper_AudioClip.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/AssetPromise_AudioClip.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/AssetPromise_AudioClip.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/Asset_AudioClip.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/Asset_AudioClip.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/Tests/APK_AudioClip_Promise_Should.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/Tests/APK_AudioClip_Promise_Should.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/Tests/APK_AudioClip_ShouldWorkWhen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/Tests/APK_AudioClip_ShouldWorkWhen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/Tests/APK_AudioClip_Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/Tests/APK_AudioClip_Tests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/Tests/BlockedAndMasterPromisesShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/Tests/BlockedAndMasterPromisesShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
Labels: ready for review, merge me!

#1082 fix: reimplemented websocket server search available port with try-ca…
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/IKernelCommunication.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/NativeBridgeCommunication/NativeBridgeCommunication.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/WebSocketCommunication.cs
  unity-renderer/Assets/Scripts/MainScripts/Debugging.meta
  unity-renderer/Assets/Scripts/MainScripts/Debugging/DebugParameters/DebugConfigComponent.cs
Labels: ready for review

#1099 bug: expressions now are played properly
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
Labels: ready for review
