Repository decentraland/unity-renderer, pull requests merged in 2022-12, with the labels that each got.

#3609 feat: [SUB-BRANCH] Receive a friend request for improved friend requests
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/NewFriendRequestsApiBridgeMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/Helpers/FriendsController_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/WebInterfaceFriendsApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationsFeature.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/FriendRequestNotificationModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/FriendRequestNotificationModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/IMainChatNotificationsComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ITopNotificationsComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/MainChatNotificationsComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationComponent/ChatNotificationMessageComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationComponent/ChatNotificationMessageComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationComponent/FriendRequestNotificationComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationComponent/FriendRequestNotificationComponentModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationComponent/FriendRequestNotificationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationComponent/FriendRequestNotificationComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationComponent/IChatNotificationMessageComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationComponent/IShowableNotificationView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationComponent/IShowableNotificationView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationMessagesHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Resources/FriendRequestNotification.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Resources/FriendRequestNotification.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/ChatNotificationControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/ChatNotificationMessageComponentViewTest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/FriendRequestNotificationComponentViewTest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/FriendRequestNotificationComponentViewTest.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/MainChatNotificationsComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/NotificationMessagesTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/TopNotificationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChatNotificationHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/TopNotificationHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
Labels: Not QA Needed

#3612 feat: move rpc server creation to the service and add ensure rpc
  docs/how-to-renderer-protocol.md
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/RPC.Context.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/RPCContext.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/TransportServiceContext.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/TransportServiceContext.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Interfaces/IRPC.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/RPC.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/RPC.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/ServerBuilder/RPC.ServerBuilder.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/ServerBuilder/RPCServerBuilder.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/TransportService/RPC.Services.TransportService.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/TransportService/TransportServiceImpl.cs
Labels: Not QA Needed

#3645 fix: SDK7 set scene init message on first Crdt
  unity-renderer/Assets/DCLPlugins/ECS7/Tests/ECS7HotReload.cs
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/ECS7TestScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/IParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/CRDTServiceContext.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/RPC.Context.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/RPC.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/RPC.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTServiceImpl.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/RPC.Services.CRDTService.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/Tests/CRDTServiceShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/Tests/RPC.Services.CRDTService.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/UnityParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
Labels: Not QA Needed

#3670 fix: SDK7 deprecate `Liberation Sans` font
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/TextShape/Tests/ECSTextShapeShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/ProtoConvertUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/TextShape.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Texts.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/UiText.gen.cs
Labels: Not QA Needed

#3672 hotfix: SDK7 Ui breaking scenes loading
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/ECSScenesUiSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECSScenesUiSystemShould.cs
Labels: Not QA Needed

#3614 Feat/passport about tab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTIconComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypeIconsAndColors.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypesIcons.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/IPassportApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/IPassportApiBridge.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/IPassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/WebInterfacePassportApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/WebInterfacePassportApiBridge.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/PassportHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/EquippedWearable.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/EquippedWearable.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/NFTIcon.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PlayerPassport.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/PassportHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/PassportHUDTests.asmdef
  unity-renderer/Assets/Textures/UI/PassportBackground.png
  unity-renderer/Assets/Textures/UI/PassportBackground.png.meta
  unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
Labels: Not QA Needed, no_reviewers

#3692 fix: gltfast importer wont work if the package name changes
  unity-renderer/Packages/manifest.json
  unity-renderer/Packages/packages-lock.json
Labels: do not review, Not QA Needed

#3701 Feat: added nft carousel for new passport
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NftPageView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NftPageView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/IPassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/NFTPage.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/NFTPage.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PassportNFTCarousel Variant.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PassportNFTCarousel Variant.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PlayerPassport.prefab
  unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs
Labels: Not QA Needed, no_reviewers

#3727 fix: SceneController Service global scene load
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Bridge/SceneControllerBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/GlobalScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/ISceneController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/SceneControllerServiceImpl.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.cs
Labels: Not QA Needed

#3602 fix: SDK7 AvatarAttach empty id use local avatar
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarAttach/AnchorPointsGetterHandlers/GetAnchorPointsHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarAttach/Handler/AvatarAttachComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarAttach/Tests/AvatarAttachHandlerShould.cs
Labels: Not QA Needed

#3723 Feat: added scrollbars in passport navigation tab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTIconComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTIconComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypesIcons.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NftPageView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/Tests/NFTIconComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/IPassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/IPassportPlayerInfoComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/PassportHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/NFTIcon.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PassportNFTCarousel Variant.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PlayerPassport.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/PassportHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/PassportHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_HUDs.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs
Labels: Not QA Needed, no_reviewers

#3738 chore: updated review list
  .github/auto_assign_config.yml
Labels: Not QA Needed

#3743 fix: character moving on characteronly colliders
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Resources/Prefabs/CharacterController.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Tests/CharacterControllerTests.cs
Labels: ready for review

#3776 chore: align main dev 2022 12 15
  unity-renderer/Assets/Prefabs/Resources/Bridges.prefab
Labels: Not QA Needed

#3772 Fix: AssetBundles detection commands stop working when triggered again outside the initial range
  unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorTracker.cs
Labels: minor, new

#3771 feat: Worlds Analytics
  unity-renderer/Assets/DCLPlugins/RealmsPlugin/AboutConfigurationExtensions.cs
  unity-renderer/Assets/DCLPlugins/RealmsPlugin/AboutConfigurationExtensions.cs.meta
  unity-renderer/Assets/DCLPlugins/RealmsPlugin/RealmPlugin.cs
  unity-renderer/Assets/DCLPlugins/RealmsPlugin/Tests/DCL.Plugins.RealmsPlugin.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/RealmsPlugin/Tests/RealmBlockerModifierTests.cs
  unity-renderer/Assets/DCLPlugins/RealmsPlugin/Tests/RealmMinimapModifierTests.cs
  unity-renderer/Assets/DCLPlugins/RealmsPlugin/Tests/RealmPluginTests.cs
  unity-renderer/Assets/DCLPlugins/RealmsPlugin/Utils/JumpToHomeController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/IWorldsAnalytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/IWorldsAnalytics.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/Tests/WorldsAnalyticsTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/Tests/WorldsAnalyticsTests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/Tests/WorldsAnalyticsTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/Tests/WorldsAnalyticsTests.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/WorldsAnalytics.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/WorldsAnalytics.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/WorldsAnalytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/WorldsAnalytics.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/WorldsAnalyticsTypes.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/WorldsAnalytics/WorldsAnalyticsTypes.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystem.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UpdateEventHandler/IUpdateEventHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UpdateEventHandler/UpdateDispatcher.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Common.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
Labels: No QA Needed

#3798 fix: try to cope with desktop native crashes on quit
  unity-renderer/Assets/DCLPlugins/MapTexturePlugin/MapTexturePlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/DCLWebSocketService.cs
Labels: No QA Needed

#3700 chore: rpc scene controller service
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/CameraSystem/ECSCameraEntitySystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/CameraSystem/Tests/ECSCameraEntitySystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PlayerSystem/ECSPlayerTransformSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PlayerSystem/Tests/ECSPlayerTransformSystemShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/CRDTProtocol.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Executor/CRDTExecutor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/ClientSceneControllerService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/ClientSceneControllerService.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/SceneControllerService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/SceneControllerService.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Entity.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/SceneController.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/SceneController.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Bridge/SceneControllerBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/GlobalScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/ISceneController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/CRDTServiceContext.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/RPC.Context.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/GeneratedCode.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/ServerBuilder/RPC.ServerBuilder.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/ServerBuilder/RPCServerBuilder.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/RPC.Services.SceneControllerService.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/RPC.Services.SceneControllerService.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/SceneControllerServiceImpl.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/SceneControllerServiceImpl.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests/RPC.Services.SceneControllerService.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests/RPC.Services.SceneControllerService.Tests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests/SceneControllerServiceShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests/SceneControllerServiceShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.cs
  unity-renderer/Packages/packages-lock.json
Labels: ready for review

#3825 fix: ReportAvatarFatalError needs to send a json
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: No QA Needed

#3770 fix: sdk7 ui fixes
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBUiTransform_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/Tests/DCL.ECSComponents.UIText.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/Tests/UiTextHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/UiTextHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UITransform/UITransformHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentModels.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ScenesUI/ScenesUiPanelSettings.asset
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/ECSScenesUiSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECS7Plugin.Systems.ScenesUiSystem.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECSScenesUiSystemShould.cs
Labels: ready for review, No QA Needed

#3826 feat: porting decoupled loading screen events to renderer
  unity-renderer/Assets/DCLPlugins/LoadingScreenPlugin/LoadingScreenPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/DCL.LoadingScreen.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Interfaces/ILoadingScreenView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Tests/LoadingScreenControllerTests.cs
Labels: stream-core

#3810 fix: Typo on "disable for other users"
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Scripts/AvatarModifierAreaFeedbackView.cs
Labels: stream-core

#3832 fix: profile hud v2
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDViewV2.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD_V2.prefab
Labels: No QA Needed

#3804 chore: update code gen to use interfaces for the clients
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/bff/ClientAuthenticationServiceService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/bff/ClientCommsDirectorServiceService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/bff/ClientCommsServiceService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/bff/ClientHttpEndpointsService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/bff/ClientTopicsServiceService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/kernel_services/ClientAnalyticsService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/kernel_services/ClientEmotesKernelService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/kernel_services/ClientFriendRequestKernelService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/ClientCrdtService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/ClientEmotesRendererService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/ClientFriendRequestRendererService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/ClientSceneControllerService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/ClientTransportService.gen.cs
Labels: No QA Needed

#3829 chore: update gltfast to 5.0.0
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/AssetPromise_GLTFast_Loader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Asset_GLTFast_Instance.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Asset_GLTFast_Loader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFDownloaderWrapper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFTextureDownloaderWrapper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFastDownloadProvider.cs
  unity-renderer/Packages/packages-lock.json
Labels: stream-core

#3852 Fix: fixed tutorial getting stuck in explore step
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
Labels: critical

#3856 chore: re-add SDK7 ui text displacement test
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECSScenesUiSystemShould.cs
Labels: ready for review, No QA Needed, no_reviewers

#3869 fix: sdk7 UiText style
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/UiTextHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/UiElementUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/UiElementUtils.cs.meta
Labels: No QA Needed
