Repository decentraland/unity-renderer, pull requests merged in 2022-09, with the labels that each got.

#2601 feat: add avatar shape component in the new ECS7
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/AssemblyInfo.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/AssemblyInfo.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/AvatarShape.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/AvatarShape.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/AvatarShapeRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/AvatarShapeRegister.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/DCL.ECSComponents.AvatarShape.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/DCL.ECSComponents.AvatarShape.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Handler.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Handler/AvatarShapeComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Handler/AvatarShapeComponentHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Resources.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Resources/NewAvatarShape.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Resources/NewAvatarShape.prefab.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Serialization.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Serialization/AvatarShapeSerializer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Serialization/AvatarShapeSerializer.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Tests/AvatarShapeComponentHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Tests/AvatarShapeComponentHandlerShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Tests/AvatarShapeShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Tests/AvatarShapeShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Tests/DCL.ECSComponents.AvatarShape.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Tests/DCL.ECSComponents.AvatarShape.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/DCL.Plugins.ECS7Components.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBAvatarShape_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/ECS7ComponentsComposer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/AvatarUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/AvatarUtils.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/DCL.ECSComponents.Utils.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECSTestScene.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Definitions/AvatarShape.proto
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Editor/compiledVersion.gen.txt
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PBFiles/AvatarShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/IAvatarMovementController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/LOD.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnchorPoints/Implementation/AvatarAnchorPoints.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMovementController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
Labels: Not QA Needed

#2959 feat: channels analytics
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/ISocialAnalytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/SocialAnalytics.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/SocialAnalytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/HighlightsSubSection/HighlightsSubSectionMenu/HighlightsSubSectionComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlacesSubSectionMenu/PlacesSubSectionComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/JoinChannelComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/JoinChannelHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/JoinChannelModalPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/Tests/JoinChannelComponentControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/Tests/JoinChannelHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/LeaveChannelConfirmationWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/SearchChannelsWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChatChannelHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/CreateChannelWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/LeaveChannelConfirmationWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/SearchChannelsWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/ChannelJoinedSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/ChannelJoinedSource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/ChannelLeaveSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/ChannelLeaveSource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/ChannelLinkSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/ChannelLinkSource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Channels.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_ExploreV2.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/ExploreV2CurrentModal.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/ExploreV2CurrentModal.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/ChannelLinkDetector.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/UIHelpers.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
Labels: Not QA Needed

#2954 fix: onpointerevent colliders reset on scene bounds check
  unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/DCL.Plugins.UUIDEventComponents.asmdef
  unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/DCL.Components.Events.asmdef
  unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/OnPointerEvent.cs
  unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/OnPointerEventColliders.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/VideoTextureShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_SceneBoundariesChecker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_SceneBoundariesChecker_Extensions.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SBC_Asserts.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
  unity-renderer/Assets/Scripts/Tests/IntegrationTestSuite_Legacy.cs
Labels: ready for review

#2986 chore: reduce timeouts when necessary
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Wearables/WearablesFetchingHelper.cs
Labels: Not QA Needed

#2988 chore: remove Pravus as reviewer
  .github/auto_assign_config.yml
Labels: Not QA Needed

#2941 feat: [SUB-BRANCH] Implement channel list of players and counter
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChatChannelsControllerMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/UpdateChannelMembersPayload.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/UpdateChannelMembersPayload.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/LazyLoadingChatControllerMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Tests/Helpers/ChatController_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelMemberEntry.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelMemberEntry.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelMembersHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelMembersHUD.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChatChannelHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMemberEntry.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMemberEntry.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMemberEntryModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMemberEntryModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersHUDController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/CollapsableChannelMemberListComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/CollapsableChannelMemberListComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelMembersComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelMembersComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChatChannelWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelMemberEntryShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelMemberEntryShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelMembersComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelMembersComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelMembersHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelMembersHUDControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/WebSocketCommunication.cs
Labels: Not QA Needed

#2979 feat: enable or disable channel notifications
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChatChannelsControllerMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Tests/Helpers/ChatController_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/ChatNotificationControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/ChatNotificationControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/NotificationMessagesTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChatChannelHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PublicChannelElement.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChatChannelWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatEntry.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatEntryModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/SearchChannelsWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChatChannelComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChatChannelHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/CollapsableChatSearchListComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChannelEntryShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatChannelComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatEntryShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: Not QA Needed

#2999 fix: highlight backpack hair selection
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/CategoryToggle.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/SubcategoryToggle.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/FontOnToggle.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/FontOnToggle.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/ImageColorOnToggle.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/TMPColorOnToggle.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/TMPFontOnToggle.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggle.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggles.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggles/IUIToggleBehavior.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggles/IUIToggleBehavior.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggles/ImageColorOnToggle.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggles/ImageColorOnToggle.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggles/TMPColorOnToggle.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggles/TMPColorOnToggle.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggles/TMPFontOnToggle.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggles/TMPFontOnToggle.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggles/UIOnToggleUpdater.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIToggles/UIOnToggleUpdater.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCardHUD.prefab
Labels: ready for review

#2912 feat: add VisibilityComponent
  unity-renderer/Assets/DCLPlugins/ECS7/ComponentGroups/ComponentGroups.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ComponentGroups/Interfaces/IComponentGroups.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/BoxShape/Handler/ECSBoxShapeComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/DCL.Plugins.ECS7Components.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBVisibilityComponent_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBVisibilityComponent_Defaults.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/ECS7ComponentsComposer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/MeshRendererHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/MeshRendererRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/Tests/MeshRendererHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/AssemblyInfo.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/AssemblyInfo.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/DCL.ECSComponents.VisibilityComponent.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/DCL.ECSComponents.VisibilityComponent.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/Handler.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/Handler/ECSVisibilityComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/Handler/ECSVisibilityComponentHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/Tests/DCL.Components.ECSVisibilityComponentShould.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/Tests/DCL.Components.ECSVisibilityComponentShould.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/Tests/ECSVisibilityComponentShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/Tests/ECSVisibilityComponentShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/VisibilityComponentRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/VisibilityComponentRegister.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/IInternalECSComponents.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentModels.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentsId.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalRenderersExtensions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalRenderersExtensions.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/InternalECSComponents.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffer.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffer/Editor.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffer/Editor/protoc.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffer/Editor/protoc/bin.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Definitions/VisibilityComponent.proto
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Definitions/VisibilityComponent.proto.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/ComponentID/ComponentID.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PBFiles/VisibilityComponent.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PBFiles/VisibilityComponent.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECS7Plugin.Systems.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem/ECS7Plugin.Systems.Visibility.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem/ECS7Plugin.Systems.Visibility.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem/ECSVisibilitySystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem/ECSVisibilitySystem.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem/Tests/ECS7Plugin.Systems.Visibility.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem/Tests/ECS7Plugin.Systems.Visibility.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem/Tests/ECSVisibilitySystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem/Tests/ECSVisibilitySystemShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Textures/Assets/LoadingAtlas.spriteatlas
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Textures/Teleport/TeleportLoadingAtlas.spriteatlas
Labels: Not QA Needed

#3024 hotfixes 20220912 into dev
  unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/BaseAvatarReveal.cs
  unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/RevealAnimation.anim
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatChannelController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
Labels: Not QA Needed

#3012 feat: renderer protocol generation
  .gitignore
  README.md
  docs/how-to-renderer-protocol.md
  protocol-gen/package-lock.json
  protocol-gen/package.json
  protocol-gen/scripts/build.ts
  protocol-gen/scripts/tsconfig.json
  protocol-gen/tsconfig.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/TextShape/Tests/ECSTextShapeShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShapeTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BotsController/BotsController.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DCL.Runtime.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/DebugController.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/GeneratedCode/EngineInterface.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/GeneratedCode/EngineInterface.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/GeneratedCode/RendererProtocol.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/GeneratedCode/RendererProtocolService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/PerformanceTests/PerformanceTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/PhysicsCast/Tests/PhysicsCastTest.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/Protocol.asmdef
Labels: Not QA Needed

#3035 feat: channels search pagination by token
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/Channel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChannelSearchResultsPayload.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChannelSearchResultsPayload.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChatChannelsControllerMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Tests/Helpers/ChatController_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/ChatNotificationControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatEntryModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/SearchChannelsWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/SearchChannelsWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChatChannelComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChatChannelHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/CollapsableChatSearchListComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/CreateChannelWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChannelEntryShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatChannelComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatEntryShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/SearchChannelsWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/SearchChannelsWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: Not QA Needed

#3034 docs: update README required Unity version
  README.md
Labels: minor

#3045 signed version of Avatar-hud-collectibles approved PR
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
Labels: bug, major, Not QA Needed

#3049 fix: avatar shape null key fatal error when removed using SDK
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
Labels: ready for review, Not QA Needed

#3064 hotfix 20220917
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
Labels: Not QA Needed, no_reviewers

#3065 chore: master -> dev
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
Labels: Not QA Needed, no_reviewers

#2947 fix: add AB test variant support for feature flags
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystem.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/FeatureFlags/Data/FeatureFlag.cs
  unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
Labels: Not QA Needed

#3008 chore: add scene boundaries checking documentation
  docs/bots-tool.md
  docs/scene-boundaries-checking.md
  docs/scene-boundaries-checking/irregular-example.png
  docs/scene-boundaries-checking/irregular-gizmo-example-2.png
  docs/scene-boundaries-checking/irregular-gizmo-example.png
  docs/scene-boundaries-checking/scene-inner-boundaries.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
Labels: ready for review, Not QA Needed

#3067 feat: channels limit error
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChannelErrorCode.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChannelErrorCode.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChatChannelsControllerMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/JoinChannelErrorPayload.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/MuteChannelErrorPayload.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Tests/Helpers/ChatController_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelCreationHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelLimitReachedModal.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelLimitReachedModal.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLimitReachedWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLimitReachedWindowComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLimitReachedWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLimitReachedWindowController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLimitReachedWindowPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLimitReachedWindowPlugin.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/CreateChannelWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/CreateChannelWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelLimitReachedWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelLimitReachedWindowView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ICreateChannelWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLimitReachedWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLimitReachedWindowComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLimitReachedWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLimitReachedWindowControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/CreateChannelWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/CreateChannelWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystem.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Channels.cs
Labels: Not QA Needed

#3072 Compose correct url for face and body
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileModel.cs
Labels: bug, minor, explorer

#3086 fix: non-functional showInfo button be shown in backack emotes
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/EmotesCustomization/EmotesCustomizationSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/EmotesCustomizationComponentController.cs
Labels: bug, ready for review

#3057 Fix: gray screen flash on nav map
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/ExploreV2Menu.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/PlacesAndEventsSectionComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentControllerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentViewTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/ShowHideAnimator/ShowHideAnimator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMapLoadingLogo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMapLoadingLogo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Resources/NavMap.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/Variables/BaseVariable.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/SectionSelector/SectionToggle.cs
Labels: bug, ready for review

#3097 chore: add doc on how to use asset bundle converter
  README.md
  docs/how-to-use-asset-bundle-coverter.md
  docs/how-to-use-asset-bundle-coverter/Screen_Shot_2021-11-16_at_13.26.56.png
  docs/how-to-use-asset-bundle-coverter/Screen_Shot_2021-11-22_at_16.14.02.png
Labels: Not QA Needed

#3098 hotfix: avatar shape rollback
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
Labels: Not QA Needed, no_reviewers

#3100 chore: main -> dev
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
Labels: Not QA Needed, no_reviewers

#3060 feat: ECS7 add pointer events and pointer interaction hover feedback canvas
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/DCL.Plugins.ECS7Components.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBPointerEvents_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBPointerEvents_Defaults.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/ECS7ComponentsComposer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/DCL.ECSComponents.PointerEvents.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/DCL.ECSComponents.PointerEvents.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/PointerEventsRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/PointerEventsRegister.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/AssemblyInfo.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/AssemblyInfo.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/DCL.Plugins.ECSInteractionHoverCanvas.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/DCL.Plugins.ECSInteractionHoverCanvas.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/ECSInteractionHoverMonoBehavior.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/ECSInteractionHoverMonoBehavior.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/ECSInteractionHoverTooltipMonoBehavior.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/ECSInteractionHoverTooltipMonoBehavior.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Interfaces.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Interfaces/DCL.Plugins.ECSInteractionHoverCanvas.Interfaces.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Interfaces/DCL.Plugins.ECSInteractionHoverCanvas.Interfaces.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Interfaces/IECSInteractionHoverCanvas.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Interfaces/IECSInteractionHoverCanvas.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Resources.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Resources/ECSInteractionHoverCanvas.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Resources/ECSInteractionHoverCanvas.prefab.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Tests/DCL.Plugins.ECSInteractionHoverCanvas.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Tests/DCL.Plugins.ECSInteractionHoverCanvas.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Tests/ECSInteractionHoverMonoBehaviorShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Tests/ECSInteractionHoverMonoBehaviorShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECS7Plugin.Systems.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECS7Plugin.Systems.PointerInput.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECS7Plugin.Systems.PointerInput.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECSPointerInputSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/SystemsContext/SystemsContext.cs
  unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/PointerEventsController/PointerEventsController.cs
Labels: Not QA Needed

#3066 fix: ECS7 NFTShape
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBNFTShape_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/ECS7ComponentsComposer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/AssemblyInfo.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/DCL.ECSComponents.NFTShape.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Handler/ECSNFTShapeComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/NFTShapeFrame.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/NFTShapeFrameFactory.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/NFTShapeRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Baroque_Ornament.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Blocky.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Canvas.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Classic.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Diamond_Ornament.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Gold_Carved.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Gold_Edges.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Gold_Rounded.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Gold_Wide.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Metal_Medium.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Metal_Rounded.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Metal_Slim.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Metal_Wide.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Minimal_Black.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Minimal_Grey.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Minimal_White.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Minimal_Wide.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_None.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Pins.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Tape.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Wood_Slim.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Wood_Twigs.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Prefabs/NFTShapeLoader_Wood_Wide.prefab
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Serializer.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Serializer/NFTShapeSerializer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Serializer/NFTShapeSerializer.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Tests/DCL.Components.ECSNFTShapeShould.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Tests/DCL.ECSComponents.NFTShape.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Tests/DCL.ECSComponents.NFTShape.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Tests/ECSNFTShapeShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Tests/PrefabsShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Tests/PrefabsShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECSTestScene.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Definitions/NFTShape.proto
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PBFiles/NFTShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeHQImageHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTShapeHQImageHandlerShould.cs
Labels: ready for review

#3096 feat: change default (debug) port from 5000 to 7666
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/WebSocketCommunication.cs
Labels: enhancement, ready for review

#3136 chore: CI code generation of renderer protocol and ecs7 components
  .circleci/config.yml
Labels: Not QA Needed

#3145 feat: [Channels Sub-Branch] ChannelInfoPayload refactor
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChannelInfoPayloads.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChannelInfoPayloads.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChatChannelsControllerMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
Labels: Not QA Needed

#3007 feat: replaced channels mock for real controller
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/JoinChannelModalPlugin.cs
Labels: Not QA Needed
