Repository decentraland/unity-renderer, pull requests merged in 2022-08, with the labels that each got.

#2164 fix: out of scene bounds entities check
  unity-renderer/Assets/Builder/Scripts/DCLBuilderBridge.cs
  unity-renderer/Assets/Builder/Scripts/DCLBuilderEntity.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderEntity/BIWEntity.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Controllers/BIWEntityHandler.cs
  unity-renderer/Assets/DCLPlugins/CoreComponentsPlugin/DCL.Plugins.CoreComponents.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GLTFShape/Handler/GLTFShapeComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/Tests/UUIDComponentTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadableShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/Tests/BasicMaterialShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/Tests/PBRMaterialShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/DCL.Components.ParametrizedShape.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/ParametrizedShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Transform/DCLTransform.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Configuration/Configuration.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Asset_AB_GameObject.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Asset_GLTF.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DecentralandEntity.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSComponentManagerLegacy/ECSComponentsManagerLegacy.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/IDCLEntity.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/IParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MeshesInfo/MeshesInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MeshesInfo/MeshesInfoUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/MessagingControllersManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Interfaces/ISceneBoundsChecker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SBC_Asserts.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
Labels: ready for review

#2791 fix: Change message of the Voice Chat bar when no one else is in your area
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/VoiceChatHUD/VoiceChatWindowController.cs
Labels: no_reviewers

#2583 fix: ECS7 CRDT remove components and default values
  docs/ecs7-scene-messages-flow.md
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/CRDTDeserializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/CRDTDeserializerTypes.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/Tests/CRDTDeserializerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Serializer/Tests/CRDTSerializerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageConstants.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageDeserializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageSerializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Tests/KernelBinaryMessageShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Tests/KernelCommunication.BinaryMessage.Tests.asmdef
Labels: no_reviewers

#2793 fix: insuficient resources crash when creating avatar for the first time
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
Labels: ready for review

#2796 chore: add "Not QA Needed" exclusion label to auto-assign action
  .github/auto_assign_config.yml
Labels: Not QA Needed

#2802 fix: changes noted from review 06082022
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Resources/NotificationBadge_FriendsRequestTab.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
Labels: ready for review, no_reviewers

#2822 feat: [SUB-BRANCH] Create a confirmation modal for leave a channel
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Interfaces/IHUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/LeaveChannelConfirmationHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/LeaveChannelConfirmationHUD.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ILeaveChannelConfirmationWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ILeaveChannelConfirmationWindowComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/LeaveChannelConfirmationWindowComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/LeaveChannelConfirmationWindowComponentModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/LeaveChannelConfirmationWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/LeaveChannelConfirmationWindowComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/LeaveChannelConfirmationWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/LeaveChannelConfirmationWindowController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/SearchChannelsWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChatChannelHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/LeaveChannelConfirmationWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/LeaveChannelConfirmationWindowComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/LeaveChannelConfirmationWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/LeaveChannelConfirmationWindowControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/SearchChannelsWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
Labels: no_reviewers

#2817 fix: conversation list empty state when searching
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/CollapsableChatSearchListComponentView.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/CollapsableSortedList/CollapsableSortedListComponentView.cs
Labels: ready for review

#2826 fix: added payloads for reporting scenes and players
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UserContextMenu/Scripts/UserContextMenu.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#2840 fix: Add "You" in channels
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
Labels: Not QA Needed

#2821 fix: ECS7 `AssetPromise_PrimitiveMesh` ref count
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/AssetPromise_PrimitiveMesh.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/Tests/APK_PrimitiveMesh_Promise_Should.cs
Labels: Not QA Needed

#2839 chore: update debug script
  unity-renderer/Assets/Scenes/InitialScene.unity
  unity-renderer/Assets/Scripts/Attributes/Editor.meta
  unity-renderer/Assets/Scripts/Attributes/Editor/ExpandableAttribute.cs
  unity-renderer/Assets/Scripts/Attributes/Editor/ExpandableAttribute.cs.meta
  unity-renderer/Assets/Scripts/Attributes/Editor/MainAttributes.asmdef
  unity-renderer/Assets/Scripts/Attributes/Editor/MainAttributes.asmdef.meta
  unity-renderer/Assets/Scripts/Attributes/Runtime.meta
  unity-renderer/Assets/Scripts/Attributes/Runtime/DrawIfAttribute.cs
  unity-renderer/Assets/Scripts/Attributes/Runtime/DrawIfAttribute.cs.meta
  unity-renderer/Assets/Scripts/Attributes/Runtime/MainAttributesRuntime.asmdef
  unity-renderer/Assets/Scripts/Attributes/Runtime/MainAttributesRuntime.asmdef.meta
  unity-renderer/Assets/Scripts/Editor/DrawIfAttributeDrawer.cs
  unity-renderer/Assets/Scripts/Editor/DrawIfAttributeDrawer.cs.meta
  unity-renderer/Assets/Scripts/Editor/MainEditor.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/DebugParameters/DebugConfigComponent.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/DebugParameters/DebugParameters.asmdef
Labels: Not QA Needed

#2855 fix: remove disclaimer message on private chat
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatHUD.prefab
Labels: Not QA Needed

#2854 feat: channels presentation
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChatChannelsControllerMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/LazyLoadingChatControllerMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Tests/Helpers/ChatController_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/LazyLoading/LazyLoadingFriendsControllerMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/JoinChannelModalPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ConversationListHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
Labels: ready for review, Not QA Needed

#2837 fix: ECS7 cyclic parenting
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Handler/ECSTransformHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Tests/DCL.ECSComponents.Transform.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Tests/ECSTransformHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Utils/ECSTransformUtils.cs
Labels: Not QA Needed

#2889 fix: direct message listing fixes
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
Labels: ready for review, Not QA Needed

#2878 chore: implement use-gpu-only-meshes flag
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/FeatureFlags/Data/FeatureFlag.cs
  unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
Labels: Not QA Needed

#2811 fix: collider bounds in scene bounds check
  unity-renderer/Assets/Builder/Scripts/DCLBuilderEntity.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderEntity/BIWEntity.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GLTFShape/Handler/GLTFShapeComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GLTFShape/Tests/GLTFShapeComponentShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/ECSComponentsUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/Tests/RendererUtilsShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/ECS7TestEntity.cs
  unity-renderer/Assets/Rendering/Culling/CullingController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadableShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/GLTFShape_Tests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/ParametrizedShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/Tests/ParametrizedShapesTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Transform/DCL.Components.Transform.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Transform/DCLTransform.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/CollidersManager/CollidersManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DecentralandEntity.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSComponentManagerLegacy/ECSComponentsManagerLegacy.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/IDCLEntity.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MeshesInfo/MeshesInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MeshesInfo/MeshesInfoUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Interfaces/ISceneBoundsChecker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsFeedbackStyle_RedBox.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SBC_Asserts.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
  unity-renderer/Assets/Scripts/Tests/TestUtils.cs
  unity-renderer/TestResources/GLB/gltfshape-asset-bundle-colliders-no-renderers.glb
Labels: ready for review

#2901 docs: add missing frontmatter to ecs7-component-creation.md
  docs/ecs7-component-creation.md
Labels: Not QA Needed

#2897 fix: ECS7 gltf initial visibility
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GLTFShape/Handler/GLTFShapeComponentHandler.cs
Labels: Not QA Needed

#2924 fix: avatar attach component in portable experience
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarAttach/AnchorPointsGetterHandlers/GetAnchorPointsHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarAttach/Tests/AvatarAttachHandlerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/AvatarAttach/Tests/AvatarAttachHandlerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/AvatarAttach/Tests/AvatarAttachPlayerHandlerShould.cs
Labels: Not QA Needed

#2917 chore: add Animations Sequencer for DOTween
  unity-renderer/Packages/manifest.json
  unity-renderer/Packages/packages-lock.json
  unity-renderer/ProjectSettings/PackageManagerSettings.asset
Labels: Not QA Needed

#2923 fix: scene bounds check persistent scenes
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Tests/BIWEntityHandlerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.cs
  unity-renderer/Assets/Tutorial/Tests/TutorialControllerShould.cs
Labels: ready for review

#2672 spike: unity 2021 emscripten memory cap update
  unity-renderer/Assets/Scripts/Editor/PreBuildProcessing.cs
Labels: Not QA Needed, no_reviewers

#2872 feat: add first UI integration test for ECS7
  unity-renderer/Assets/DCLPlugins/ECS7/CanvasPainter/CanvasPainter.cs
  unity-renderer/Assets/DCLPlugins/ECS7/CanvasPainter/SceneCanvasSettings.asset
  unity-renderer/Assets/DCLPlugins/ECS7/CanvasPainter/Tests/CanvasPainterShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/CanvasPainter/Tests/CanvasPainterUITransformIntegrationTest.cs
  unity-renderer/Assets/DCLPlugins/ECS7/CanvasPainter/Tests/CanvasPainterUITransformIntegrationTest.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/CanvasPainter/Tests/DCL.ECS7.CanvasPainter.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/Components.meta
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/Components/ECS7Plugin.TestUtils.Components.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/Components/ECS7Plugin.TestUtils.Components.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/Components/UI.meta
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/Components/UI/ECS7TestUIUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/Components/UI/ECS7TestUIUtils.cs.meta
Labels: Not QA Needed

#2849 fix: bots tool
  unity-renderer/Assets/ABConverter/WearablesCollectionClient.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BotsController/BotsController.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BotsController/BotsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Wearables/WearablesAPIData.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Wearables/WearablesFetchingHelper.cs
Labels: ready for review

#2915 Chore: applied suggested graphical changes to channels
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationComponent/ChatNotificationMessageComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Resources/ChatNotificationMessage.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChatNotificationHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/TopNotificationHUD.prefab
  unity-renderer/Assets/Textures/UI/ChatNotiIcon.png
  unity-renderer/Assets/Textures/UI/ChatNotiIcon.png.meta
  unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
Labels: no_reviewers

#2936 chore: update UI particle package to 4.1.6
  unity-renderer/Packages/manifest.json
  unity-renderer/Packages/packages-lock.json
  unity-renderer/ProjectSettings/PackageManagerSettings.asset
Labels: Not QA Needed

#2900 feat: ECS7 MeshRenderer component
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/BoxShape/DCL.ECSComponents.BoxShape.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/BoxShape/Handler/ECSBoxShapeComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/CylinderShape/DCL.ECSComponents.CylinderShape.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/CylinderShape/Handler/ECSCylinderShapeComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/DCL.Plugins.ECS7Components.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBMeshRenderer_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBMeshRenderer_Defaults.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/ECS7ComponentsComposer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/DCL.ECSComponents.MeshRenderer.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/DCL.ECSComponents.MeshRenderer.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/MeshRendererHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/MeshRendererHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/MeshRendererRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/MeshRendererRegister.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/Tests/DCL.ECSComponents.MeshRenderer.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/Tests/DCL.ECSComponents.MeshRenderer.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/Tests/MeshRendererHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/Tests/MeshRendererHandlerShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/DCL.ECSComponents.PlaneShape.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/Handler/ECSPlaneShapeComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/SphereShape/DCL.ECSComponents.SphereShape.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/SphereShape/Handler/ECSSphereShapeHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECS7Plugin.TestScene.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECSTestScene.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentsExtensions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Definitions/MeshRenderer.proto
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Definitions/MeshRenderer.proto.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/ComponentID/ComponentID.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PBFiles/MeshRenderer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PBFiles/MeshRenderer.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetPromiseKeeper.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/AssetPromise_PrimitiveMesh.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/AssetPromise_PrimitiveMesh_Model.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/AssetPromise_PrimitiveMesh_Model.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/PrimitiveMeshFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/Tests/APK_PrimitiveMesh_Promise_Should.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/Tests/APK_PrimitiveMesh_ShouldWorkWhen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/Tests/MeshFactoryShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/PrimitiveMeshBuilder.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/DCLResources.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/DCLResources/DCLResourcesModel.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/DCLResources/DCLResourcesModel.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/DCLResources/PrimitiveMeshModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/DCLResources/PrimitiveMeshModel.cs.meta
Labels: Not QA Needed

#2852 wip: add SetSceneNumber
  unity-renderer/Assets/Plugins/KernelNativeBridge/kernelNativeBridge.c
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/NativeBridgeCommunication/NativeBridgeCommunication.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/NativeBridgeCommunication/Tests/NativeBridgeCommunicationShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/QueuedSceneMessage/QueuedSceneMessage.cs
Labels: Not QA Needed

#2931 feat: ECS7 MeshCollider component
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/DCL.Plugins.ECS7Components.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBMeshCollider_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBMeshCollider_Defaults.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/ECS7ComponentsComposer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/AssemblyInfo.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/AssemblyInfo.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/DCL.ECSComponents.MeshCollider.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/DCL.ECSComponents.MeshCollider.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/MeshColliderHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/MeshColliderHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/MeshColliderRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/MeshColliderRegister.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/Tests/DCL.ECSComponents.MeshCollider.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/Tests/DCL.ECSComponents.MeshCollider.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/Tests/MeshColliderHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/Tests/MeshColliderHandlerShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Definitions/MeshCollider.proto
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Definitions/MeshCollider.proto.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/ComponentID/ComponentID.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PBFiles/MeshCollider.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PBFiles/MeshCollider.cs.meta
Labels: Not QA Needed
