Repository decentraland/unity-renderer, pull requests merged in 2022-11, with the labels that each got.

#3353 chore: explorev2 performance
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/BuildModeHUD/Tests/BuildModeHUDViewShould.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Tests/BuilderMainPanelControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExperiencesViewer/Resources/ExperienceRow.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/ExploreV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/ExploreV2Menu.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard_Long.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/HighlightsSubSection/PlaceCard_Long.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/PlacesSubSection/PlaceCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventCard/EventCardAnimator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventCard/EventCardAnimator.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventCard/EventCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlaceCard/PlaceCardAnimator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlaceCard/PlaceCardAnimator.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlaceCard/PlaceCardAnimatorBase.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlaceCard/PlaceCardAnimatorBase.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlaceCard/PlaceCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlaceCard/PlaceLongCardAnimator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlaceCard/PlaceLongCardAnimator.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/HUDCommon.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/ShowHideAnimator/ShowHideAnimator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/Resources/ConnectWalletHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ControlsHUD/Test/ControlsHUDTest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/Test/TeleportPromptHUDTest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TransactionHUD/Resources/TransactionHUD.prefab
  unity-renderer/Assets/UIComponents/Resources/Button_Common.prefab
Labels: performance

#3359 test: reduce culling controller budget
  unity-renderer/Assets/Rendering/Culling/Interfaces/CullingControllerSettings.cs
Labels: performance

#3366 fix: hiccups caused when another player appears
  unity-renderer/Assets/Rendering/Culling/CullingController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/ItemLoading.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/Loaded.anim
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/Loading.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/LoadingController.controller
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/LoadingController.controller.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/LoadingController2.controller
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/LoadingController2.controller.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/LoadingIdle.anim
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/LoadingLoop.anim
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/NFTItemToggle.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/ItemSelector.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/ItemToggle.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/UIPageSelector.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDViewShould.cs
Labels: performance

#3326 fix: Culling controller refactor
  unity-renderer/Assets/Rendering/Culling/CullingController.cs
  unity-renderer/Assets/Rendering/Culling/CullingControllerUtils.cs
  unity-renderer/Assets/Rendering/Culling/CullingObjectsTracker.cs
  unity-renderer/Assets/Rendering/Culling/Interfaces/CullingControllerSettings.cs
Labels: minor

#3340 refactor: ECS7 remove CRDT messages queueing
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager.meta
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/CrdtExecutorsManager.cs
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/CrdtExecutorsManager.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/ECS7Plugin.CrdtExecutorsManager.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/ECS7Plugin.CrdtExecutorsManager.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/Tests/CrdtExecutorsManagerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/Tests/CrdtExecutorsManagerShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/Tests/ECS7Plugin.CrdtExecutorsManager.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/Tests/ECS7Plugin.CrdtExecutorsManager.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
  unity-renderer/Assets/Prefabs/Resources/Bridges.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/CRDTDeserializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/CRDTDeserializerTypes.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/Tests/CRDTDeserializerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/Tests/DCL.CRDTProtocol.Deserializer.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Executor/CRDTExecutor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Serializer/Tests/CRDTSerializerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Serializer/Tests/DCL.CRDTProtocol.Serializer.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/ByteUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/UnmanagedMemoryReader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/UnmanagedMemoryReader.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Bridge.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Bridge/BinaryMessageBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Bridge/BinaryMessageBridge.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Bridge/KernelCommunication.BinaryMessageBridge.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Bridge/KernelCommunication.BinaryMessageBridge.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageConstants.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageConstants.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageDeserializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageDeserializer.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageHeader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageHeader.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageSerializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/MessageProcessor.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/MessageProcessor/KernelBinaryMessageProcessor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/MessageProcessor/KernelBinaryMessageProcessor.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/MessageProcessor/KernelCommunication.BinaryMessageProcessor.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Tests/KernelBinaryMessageShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Tests/KernelCommunication.BinaryMessage.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/CRDTServiceContext.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/ServerBuilder/RPCServerBuilder.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTServiceImpl.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTStream.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTStream/CRDTStream.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTStream/CRDTStream.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTStream/RPC.Services.CRDTService.CRDTStream.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTStream/RPC.Services.CRDTService.CRDTStream.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/RPC.Services.CRDTService.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/Tests/CRDTServiceShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/Tests/RPC.Services.CRDTService.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/Interfaces/IMessagingControllersManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/Interfaces/MessagingTypes.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/MessagingControllersManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
Labels: Not QA Needed

#3474 fix: input field black screen overlay on chat /goto action
  unity-renderer/Packages/packages-lock.json
Labels: bug

#3478 fix: ECS7 move player entity
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Handler/ECSTransformHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Tests/ECSTransformHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Utils/ECSTransformUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/Variables/IBaseVariable.cs
Labels: Not QA Needed

#3501 fix: Channel members are being requested twice
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelMembersComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelMembersHUDControllerShould.cs
Labels: Not QA Needed

#3493 Feat: added new NFT icon for new passport
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/INFTIconComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/INFTIconComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTIconComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTIconComponentModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTIconComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTIconComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypeIconsAndColors.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypeIconsAndColors.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypesIcons.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypesIcons.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/PassportHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/PassportHUD.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/NFTIcon.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/NFTIcon.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/NFTIconComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/NFTIconComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/NFTIconsTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/NFTIconsTests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Utils/SerializableKeyValuePair.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Utils/SerializableKeyValuePair.cs.meta
  unity-renderer/Assets/Textures/UI/LinearGradientNFTs.png
  unity-renderer/Assets/Textures/UI/LinearGradientNFTs.png.meta
  unity-renderer/Assets/Textures/UI/RhombusShapedGradient.png
  unity-renderer/Assets/Textures/UI/RhombusShapedGradient.png.meta
  unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
Labels: Not QA Needed

#3432 feat: divide into pbr and unlit material
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBMaterial_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/MaterialHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/Tests/MaterialHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECSTestScene.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Material.gen.cs
Labels: Not QA Needed

#3489 fix: ECS7 magenta material
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/AssemblyInfo.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/DCL.ECSComponents.Material.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/MaterialHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/Tests/MaterialHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/MaterialSystem/Tests/ECS7Plugin.Systems.Material.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/MaterialSystem/Tests/ECSMaterialSystemShould.cs
Labels: Not QA Needed

#3073 Docs: code conventions
  docs/style-guidelines.md
  unity-renderer/Assets/Scripts/CodeStyleExample.cs
Labels: enhancement, pending response, Not QA Needed

#3325 Refactor/stickers controller QA
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/CrdtExecutorsManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimationEventHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarExpressionClap.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarExpressionHeart.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarExpressionHohoho.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarExpressionMoney.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarExpressionSnowflakes.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarFootstep.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarFootstepJump.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarFootstepLand.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Components.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Components/ReleaseParticlesOnFinish.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Components/ReleaseParticlesOnFinish.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/StickersController/StickersController.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/StickersController/StickersController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/StickersController/StickersFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/DestroyParticlesOnFinish.cs
  unity-renderer/ProjectSettings/QualitySettings.asset
Labels: new

#3512 fix: ECS7 use Color4 for UiText color
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Color_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Color_Defaults.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBMaterial_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBUiText_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/Tests/UiTextHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/UiText.gen.cs
Labels: Not QA Needed

#3508 Feat: added new placeholder passport panel behind Feature Flag
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/IPassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/IPassportNavigationComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/IPassportPlayerInfoComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/IPassportPlayerInfoComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportPlugin.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPreview.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPreview/IPassportPlayerPreviewComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPreview/IPassportPlayerPreviewComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPreview/PassportPlayerPreviewComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPreview/PassportPlayerPreviewComponentController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPreview/PassportPlayerPreviewComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPreview/PassportPlayerPreviewComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/PassportHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PlayerPassport.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PlayerPassport.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCardHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Friends/FriendEntry.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystem.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_HUDs.cs
Labels: Not QA Needed, no_reviewers, stream-social

#3408 chore: updated hardcoded heap size limit
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/FPSDisplay/MetricsModules/MemoryJSDebugMetricModule.cs
Labels: stream-performance

#3529 feat: (ecs7) change billboard approach
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/BillboardRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Handler.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Handler/BillboardComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Handler/BillboardComponentHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Tests/BillboardShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Tests/DCL.ECSComponents.Billboard.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/BillboardSystem.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/BillboardSystem/ECS7Plugin.Systems.ECSBillboardSystem.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/BillboardSystem/ECS7Plugin.Systems.ECSBillboardSystem.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/BillboardSystem/ECSBillboardSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/BillboardSystem/ECSBillboardSystem.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/BillboardSystem/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECS7Plugin.Systems.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/SystemsContext/ECS7Plugin.Systems.Context.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/SystemsContext/SystemsContext.cs
Labels: Not QA Needed

#3535 fix: ECS7 scene UI renderer over loading screen
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/ECSScenesUiSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECSScenesUiSystemShould.cs
Labels: Not QA Needed

#3556 refactor: UserProfileemotes caused a hiccup
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/BillboardSystem/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
Labels: new, performance

#3543 chore: ECS7 remove timestamp from raycast
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Handler/RaycastHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Tests/ECSRaycastShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Raycast.gen.cs
Labels: ready for review, Not QA Needed

#3540 docs: update .editorconfig
  unity-renderer/.editorconfig
  unity-renderer/ProjectSettings/QualitySettings.asset
  unity-renderer/unity-renderer.sln.DotSettings
Labels: Not QA Needed

#3589 chore: update reviewer list
  .github/auto_assign_config.yml
Labels: Not QA Needed

#3593 chore: updated readme with new unity version
  README.md
Labels: Not QA Needed

#3566 Feat: player info area in new passport
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/IPassportPlayerInfoComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/PassportHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/ButtonFriendStatus Variant.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/ButtonFriendStatus Variant.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PlayerPassport.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/UserContextMenuPanel Variant.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/UserContextMenuPanel Variant.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/PassportHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/IUserProfileBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileWebInterfaceBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: Not QA Needed, no_reviewers

#3611 chore: send friend request tests
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SendFriendRequestHUDComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SendFriendRequestHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/FriendRequestHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/FriendRequestHUDTests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SendFriendRequestHUDComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SendFriendRequestHUDComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SendFriendRequestHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SendFriendRequestHUDControllerShould.cs.meta
Labels: Not QA Needed

#3618 feat: ecs7 plugin always enabled
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
Labels: ready for review

#3571 fix: ecs7 input event result hit position
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Handler/RaycastHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECS7Plugin.Systems.PointerInput.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECS7Plugin.Systems.PointerInput.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECS7Plugin.Systems.PointerInput.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECSPointerInputSystemShould.cs
Labels: bug, sdk, ready for review, Not QA Needed

#3623 fix: crdt race condition with hotreload scene
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTServiceImpl.cs
Labels: Not QA Needed

#3637 fix: SDK7 Ui hot-reload
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/ECSScenesUiSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECSScenesUiSystemShould.cs
Labels: Not QA Needed

#3616 style: controls screen update
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ControlsHUD/Resources/ControlsHUD.prefab
  unity-renderer/Assets/Textures/UI/ArrowOutline.png
  unity-renderer/Assets/Textures/UI/ArrowOutline.png.meta
  unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
Labels: ready for review
