Repository decentraland/unity-renderer, pull requests merged in 2022-10, with the labels that each got.

#3146 Stop animations when character and tutorial robot are not rendered
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
  unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_LockTheCursor.cs
  unity-renderer/Assets/Tutorial/Scripts/TutorialStep.cs
  unity-renderer/Assets/Tutorial/Scripts/TutorialTeacher.cs
  unity-renderer/ProjectSettings/QualitySettings.asset
Labels: tech debt

#3070 chore: enable avatar shape dynamic scaling
  docs/scene-boundaries-checking.md
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldEditor.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/AvatarShape.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Tests/AvatarShapeShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Avatar.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarWithHologram.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/IAvatar.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarLODController/AvatarLODController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Transform/DCLTransform.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
Labels: ready for review

#3184 chore: update @dcl/protocol
  .gitattributes
  protocol-gen/package-lock.json
  protocol-gen/package.json
  protocol-gen/scripts/build-components.ts
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/ActionButton.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Animator.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/AudioSource.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/AudioStream.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/AvatarAttach.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/AvatarModifierArea.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/AvatarShape.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Billboard.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/BoxShape.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/CameraMode.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/CameraModeArea.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/CameraModeValue.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Color3.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Color4.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/CylinderShape.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/GltfContainer.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Id.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Material.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/MeshCollider.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/MeshRenderer.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/NFTShape.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerDown.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerDownResult.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerUp.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerUpResult.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PlaneShape.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PointerEvents.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PointerEventsResult.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PointerLock.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Raycast.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/RaycastResult.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/SphereShape.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/TextShape.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/UiStyles.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/UiText.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/UiTransform.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Vector3.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/VisibilityComponent.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/GeneratedCode/EngineInterface.gen.cs
Labels: Not QA Needed

#3157 fix: Welcome to Genesis plaza should not be shown outside of it
  unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_GenesisGreetings.cs
Labels: bug, minor

#3192 implementation of join channel error modal for unknown reason
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelJoinErrorModal.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelJoinErrorModal.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowPlugin.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelJoinErrorWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelJoinErrorWindowView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelJoinErrorWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelJoinErrorWindowComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelJoinErrorWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelJoinErrorWindowControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Channels.cs
Labels: Not QA Needed

#3177 Fix: map section by shortcut side effects other sections
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMapScrollRect.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapCloseButtonBehaviour.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapCloseButtonBehaviour.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapToastView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapVisibilityBehaviour.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapVisibilityBehaviour.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapZoom.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapZoom.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Resources/NavMap.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Tests/NavmapTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Tests/NavmapToastViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapAtlas.cs
Labels: bug, ready for review

#3206 feat: leave channel error modal
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelLeaveErrorModal.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelLeaveErrorModal.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowPlugin.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelLeaveErrorWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelLeaveErrorWindowView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/LeaveChannelConfirmationWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLeaveErrorWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLeaveErrorWindowComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLeaveErrorWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLeaveErrorWindowControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
Labels: Not QA Needed

#3209 Fix: ff changes and bugfixes for notifications and channels
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_HUDs.cs
Labels: Not QA Needed

#3215 refactor: remove old pointer events
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/ComponentID.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerDown.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerDown.gen.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerDownResult.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerDownResult.gen.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerUp.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerUp.gen.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerUpResult.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/OnPointerUpResult.gen.cs.meta
Labels: Not QA Needed

#3195 feat: [SUB-BRANCH] Feature Flag to allow the users to create channels
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/UsersAllowedToCreateChannelsVariantPayload.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/UsersAllowedToCreateChannelsVariantPayload.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChannelsFeatureFlagService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChannelsFeatureFlagService.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChannelsFeatureFlagService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChannelsFeatureFlagService.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/JoinChannelComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/JoinChannelModalPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/Tests/JoinChannelComponentControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ConversationListHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/SearchChannelsWindowMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/WorldChatWindowViewMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ISearchChannelsWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IWorldChatWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/SearchChannelsWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/SearchChannelsWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/SearchChannelsWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/FeatureFlags/Data/FeatureFlag.cs
Labels: Not QA Needed

#3208 Refactor/culling controller refactor
  unity-renderer/Assets/Rendering/Culling/CullingController.cs
  unity-renderer/Assets/Rendering/Culling/CullingControllerUtils.cs
  unity-renderer/Assets/Rendering/Culling/CullingObjectsTracker.cs
  unity-renderer/Assets/Rendering/Culling/Interfaces/CullingControllerSettings.cs
Labels: enhancement, explorer

#3224 chore: add extra reviewers
  .github/auto_assign_config.yml
Labels: Not QA Needed

#3236 Fix: avoid showing top notification when coming from open chat
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_HUDs.cs
Labels: Not QA Needed, no_reviewers

#3188 feat: ECS7 UiText component
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/DCL.Plugins.ECS7Components.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Color3_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Color3_Defaults.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBMaterial_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBUiText_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBUiText_Defaults.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/ECS7ComponentsComposer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/AssemblyInfo.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/AssemblyInfo.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/DCL.ECSComponents.UIText.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/DCL.ECSComponents.UIText.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/Tests/DCL.ECSComponents.UIText.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/Tests/DCL.ECSComponents.UIText.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/Tests/UiTextHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/Tests/UiTextHandlerShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/UiTextHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/UiTextHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/UiTextRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/UiTextRegister.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Font/AssetPromise_Font.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Font/Tests/APK_Font_Promise_Should.cs
Labels: Not QA Needed

#3243 fix: ECS7 billboard behavior and text align
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/BillboardRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Handler/BillboardComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Tests/BillboardShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBBillboard_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBTextShape_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBUiText_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/TextShape/ECSTextShapeComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/TextShape/Tests/ECSTextShapeShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/Tests/UiTextHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/UiTextHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/ProtoConvertUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECSTestScene.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Billboard.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/TextShape.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Texts.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/UiText.gen.cs
Labels: Not QA Needed

#3245 fix: ECS7 AudioStream not playing on start
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/AssemblyInfo.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/AudioStreamRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/DCL.ECSComponents.AudioStream.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/ECSAudioStreamComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/ECSAudioStreamComponentHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Handler.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Serialization.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Serialization/AudioStreamSerializer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Serialization/AudioStreamSerializer.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests/DCL.ECSComponents.AudioStream.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests/DCL.ECSComponents.AudioStream.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests/ECSAudioStreamShould.cs
Labels: Not QA Needed

#3258 Destroy particles on finish refactor
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/DestroyParticlesOnFinish.cs
Labels: tech debt, new

#3135 feat: choose io source device in settings
  unity-renderer/Assets/DCLServices/AudioDevicesService.meta
  unity-renderer/Assets/DCLServices/AudioDevicesService/AudioDevicesDefenitions.meta
  unity-renderer/Assets/DCLServices/AudioDevicesService/AudioDevicesDefenitions/AudioDevicesDefinitions.asmdef
  unity-renderer/Assets/DCLServices/AudioDevicesService/AudioDevicesDefenitions/AudioDevicesDefinitions.asmdef.meta
  unity-renderer/Assets/DCLServices/AudioDevicesService/AudioDevicesDefenitions/AudioDevicesResponse.cs
  unity-renderer/Assets/DCLServices/AudioDevicesService/AudioDevicesDefenitions/AudioDevicesResponse.cs.meta
  unity-renderer/Assets/DCLServices/AudioDevicesService/AudioDevicesDefenitions/IAudioDevicesBridge.cs
  unity-renderer/Assets/DCLServices/AudioDevicesService/AudioDevicesDefenitions/IAudioDevicesBridge.cs.meta
  unity-renderer/Assets/DCLServices/AudioDevicesService/AudioDevicesDefenitions/IAudioDevicesService.cs
  unity-renderer/Assets/DCLServices/AudioDevicesService/AudioDevicesDefenitions/IAudioDevicesService.cs.meta
  unity-renderer/Assets/DCLServices/AudioDevicesService/AudioDevicesService.asmdef
  unity-renderer/Assets/DCLServices/AudioDevicesService/AudioDevicesService.asmdef.meta
  unity-renderer/Assets/DCLServices/AudioDevicesService/WebBrowserAudioDevicesBridge.cs
  unity-renderer/Assets/DCLServices/AudioDevicesService/WebBrowserAudioDevicesBridge.cs.meta
  unity-renderer/Assets/DCLServices/AudioDevicesService/WebBrowserAudioDevicesService.cs
  unity-renderer/Assets/DCLServices/AudioDevicesService/WebBrowserAudioDevicesService.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/InputAudioDevicesConfiguration.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/InputAudioDevicesConfiguration.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Widgets/AudioVoiceChatWidget.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/DropDownSettingsControlTemplate.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/InputAudioDeviceControlController.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/InputAudioDeviceControlController.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/DropdownControlView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/PointerClickEventInterceptor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/PointerClickEventInterceptor.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/BaseControllers/SpinBoxSettingsControlController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SettingsControllers.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/InputAudioDeviceControlController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/InputAudioDeviceControlController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/QualityPresetControlController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsData/AudioSettings.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: enhancement, kernel

#3262 [SUB-BRANCH] Connect Wallet messages
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/BrowserBridge.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/BrowserBridge/BrowserBridge.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/BrowserBridge/BrowserBridge.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/BrowserBridge/IBrowserBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/BrowserBridge/IBrowserBridge.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/BrowserBridge/WebInterfaceBrowserBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/BrowserBridge/WebInterfaceBrowserBridge.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/ConnectWalletComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/ConnectWalletComponentController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/ConnectWalletComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/ConnectWalletComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/ConnectWalletHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/ConnectWalletHUD.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/ConnectWalletModalPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/ConnectWalletModalPlugin.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/IConnectWalletComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/IConnectWalletComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/Resources.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/Resources/ConnectWalletHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/Resources/ConnectWalletHUD.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/Tests/ConnectWalletComponentControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/Tests/ConnectWalletComponentControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/Tests/ConnectWalletComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/Tests/ConnectWalletComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/Tests/ConnectWalletHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ConnectWalletHUD/Tests/ConnectWalletHUDTests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ConversationListHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/WorldChatWindowViewMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IWorldChatWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystem.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_HUDs.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/IUserProfileBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileWebInterfaceBridge.cs
  unity-renderer/Assets/Textures/UI/ConnectWalletLogo.png
  unity-renderer/Assets/Textures/UI/ConnectWalletLogo.png.meta
  unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
  unity-renderer/Assets/UIComponents/Scripts/Components/CollapsableSortedList/CollapsableListToggleButton.cs
Labels: Not QA Needed

#3276 Fix: fixed clicking on notification redirecting to non joined channel
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
Labels: Not QA Needed, no_reviewers

#3281 feat: implemented profanity filtering on chat notification panel
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/IChatHUDComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationsFeature.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationMessagesHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/ChatNotificationControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/NotificationMessagesTests.asmdef
Labels: Not QA Needed

#3290 feat: message feedback whenever you are muted due spam filtering
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
Labels: Not QA Needed

#3282 fix: [SUB-BRANCH] Open already joined channels from link
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChatChannelsControllerMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Tests/Helpers/ChatController_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/JoinChannelComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/Tests/JoinChannelComponentControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Channels.cs
Labels: Not QA Needed

#3295 feat: disable channel links if the user is not allowed to create channels
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChannelsFeatureFlagService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChannelsFeatureFlagService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/JoinChannelModalPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/Tests/JoinChannelHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/ChannelLinkDetector.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/UIHelpers.asmdef
Labels: Not QA Needed

#3296 feat: implemented mute status on nearby channel
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/GeneralChatChannelHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/PublicChatPublicWindowMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IPublicChatWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatChannelComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatChannelControllerShould.cs
Labels: Not QA Needed

#3221 refactor: Player name optimization
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/PlayerName.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/Tests/PlayerNameShould.cs
  unity-renderer/ProjectSettings/PackageManagerSettings.asset
Labels: minor

#3321 clear unseen messages at the start of the session for each joined channel
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
Labels: Not QA Needed

#3323 refactor: (ECS7) change component name from PointerEvents to PointerHoverFeedback
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBPointerEvents_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBPointerHoverFeedback_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBPointerHoverFeedback_Defaults.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/ECS7ComponentsComposer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerHoverFeedback.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerHoverFeedback/DCL.ECSComponents.PointerHoverFeedback.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerHoverFeedback/DCL.ECSComponents.PointerHoverFeedback.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerHoverFeedback/PointerHoverFeedbackRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerHoverFeedback/PointerHoverFeedbackRegister.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/ComponentID.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PointerEventsResult.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PointerHoverFeedback.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PointerHoverFeedback.gen.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECSPointerInputSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/SystemsContext/SystemsContext.cs
Labels: Not QA Needed

#3235 feat: ECS7 avatar texture
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/DCL.ECSComponents.Defaults.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBMaterial_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Tests/TextureDefaults.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Tests/TextureDefaults/DCL.ECSComponents.Defaults.Texture.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Tests/TextureDefaults/DCL.ECSComponents.Defaults.Texture.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Tests/TextureDefaults/TextureShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Tests/TextureDefaults/TextureShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Texture_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Texture_Defaults.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/DCL.ECSComponents.Material.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/MaterialHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/Tests/DCL.ECSComponents.Material.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/Tests/MaterialHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECSTestScene.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/CameraType.gen.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Material.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Texture.gen.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Texture.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/AssetPromise_Material_Model.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfigModel.cs
Labels: Not QA Needed

#3263 fix: ECS7 Ui support for global scenes
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/IInternalECSComponent.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/InternalECSComponent.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/ECSScenesUiSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECSScenesUiSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/ECS7TestScene.cs
Labels: Not QA Needed

#3333 chore: update @dcl/rpc-csharp
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/GeneratedCode/Protocol.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/GeneratedCode/ProtocolService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/ServerBuilder/RPC.ServerBuilder.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTServiceImpl.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTServiceImpl.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/Tests/CRDTServiceShould.cs
  unity-renderer/Packages/packages-lock.json
Labels: Not QA Needed

#3354 hotfix 20221028
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
Labels: Not QA Needed, no_reviewers

#3350 fix: Passport description disappears after friend request
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
Labels: minor, new
