Repository decentraland/unity-renderer, pull requests merged in 2022-02, with the labels that each got.

#1796 feat: biw project publish refinement
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/LimitInputField/LimitInputField.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/BuilderPublisher.asmdef
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Prefabs/RotateLeft Variant.prefab
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Resources/Project/LandListAdapter.prefab
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Resources/Project/LandListAdapter.prefab.meta
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Resources/Project/PublishPopupView.prefab
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Resources/Project/PublishProgressView.prefab
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Resources/Project/PublishSuccessView.prefab
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Resources/PublishProgressView.prefab
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Resources/PublishProgressView.prefab.meta
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PublishInfo.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PublishLandListView.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PublishLandListView.cs.meta
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PublishMapView.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PublishProjectDetailView.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PublishProjectProgressView.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PublishProjectSuccesView.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PubllishLandListAdapter.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PubllishLandListAdapter.cs.meta
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/PublishProgressController.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/PublishProgressView.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/PublishProgressView.cs.meta
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/Scripts/Publisher.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Resources/ScriptableObjects/GodModeVariables.asset
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldCommon/ListView.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Cameras/ScreenshotCameraController.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/SceneManager/SceneManager.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Utils/BIWUtils.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Utils/BuilderInWorldUtils.asmdef
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Visuals/Textures.meta
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Visuals/Textures/SelectedParcelHighlight.png
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Visuals/Textures/SelectedParcelHighlight.png.meta
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Visuals/Textures/SelectedUnavailableParcelHighlight.png
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Visuals/Textures/SelectedUnavailableParcelHighlight.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Configuration/Configuration.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapParcelHighlight.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapParcelHighlight.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRendererAudioHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Renderer.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/RedParcelHighlight.prefab
  unity-renderer/Assets/UIComponents/Scripts/Components/Modal/ModalComponentView.cs
Labels: do not merge, do not review

#1870 fix: Move the StartMenu initialization before the world is up (II)
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentControllerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
Labels: ready for review

#1865 fix: change default panel for guest users from collectibles to body shape
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
Labels: ready for review

#1877 fix: fixed prefab merging failure for backpack panel
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
Labels: ready for review

#1879 fix: extends profile icon collider to top right corner
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
Labels: ready for review

#1864 feat: add FOV slider
  unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/FOVControlConfiguration.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/FOVControlConfiguration.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Widgets/GraphicsWidget.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/FOVControlController.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/FOVControlController.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/SettingsPanelHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/DefaultSettingsFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsGeneralSettingsRepository.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/FOVControlController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/FOVControlController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/Tests/SettingsControlsShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsData/GeneralSettings.cs
Labels: ready for review

#1790 feat: skins avatar category
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarCurator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/IVisibility.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/LoaderDefinitions/IBodyshapeLoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/LoaderDefinitions/ILoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/BodyShapeLoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/Loader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/WearableLoaderFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/AvatarShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/VisibilityShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Visibility.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/AvatarEditorHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/ItemToggle.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/NFTItemToggle.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/ItemSelector.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/ItemToggle.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Textures/AccesoriesIcon.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Textures/CollectiblesIcon.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Textures/HeadIcon.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Textures/MarketIcon.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Textures/SkinsIcon.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/Resources/UsersAroundListHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystem.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/AvatarAssets.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/Tests/WearableItemShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/Tests/WearableItemShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableLiterals.cs
Labels: ready for review

#1863 refactor: move builder components to own assembly
  unity-renderer/Assets/Builder/Scripts/Builder.asmdef
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/BuildModeHUD/Scripts/BuildModeHUD.asmdef
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderEntity/BuilderInWorldEntity.asmdef
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/BIWBridge.asmdef
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuildingTool.asmdef
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/EntityInformation/BuilderInWorldEntityInformation.asmdef
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Utils/EntityComponentUtils/BIWEntityComponentUtils.asmdef
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Tests/BuilderInWorldTest.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/DCL.Components.Builder.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/DCL.Components.Builder.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/Gizmos.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/Gizmos/DCLGizmos.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/Gizmos/DCLGizmos.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/Gizmos/DCLGizmosComponent.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/Gizmos/DCLGizmosComponent.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/SmartItem.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/SmartItem/SmartItem.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/SmartItem/SmartItem.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/SmartItem/SmartItemCommon.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/SmartItem/SmartItemCommon/SmartItemCommon.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/SmartItem/SmartItemCommon/SmartItemCommon.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/SmartItem/SmartItemCommon/SmartItemCommon.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/SmartItem/SmartItemCommon/SmartItemCommon.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/SmartItem/SmartItemComponent.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/SmartItem/SmartItemComponent.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/SmartItem/SmartItemCommon/SmartItemCommon.asmdef
  unity-renderer/Assets/Scripts/MainScripts/MainScripts.asmdef
Labels: ready for review

#1875 fix: avoid fps affecting movement speed
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/FreeMovementController.cs
Labels: ready for review

#1898 fix: realm message
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/Realms/RealmSelector_Modal.prefab
Labels: ready for review

#1892 fix: disable scrollwheel camera change when mouse on UI element
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
Labels: ready for review

#1925 fix: scenes stuck loading on GLTF promises silent forget
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/BlockedAndMasterPromisesShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/CoroutineHelpers/CoroutineUtils.cs
Labels: ready for review, merge me!

#1926 fix: scene bounds checker material replacement removal
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Scripts.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsFeedbackStyle_RedBox.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsFeedbackStyle_RedBox.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsFeedbackStyle_RedFlicker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SBC_Asserts.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundarieCheckerFeedbackStyleShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
Labels: ready for review

#1934 fix: opensea 403 workaround
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/OpenSea/RequestController.cs
Labels: ready for review

#1930 chore: removed scripts/prefabs related to unused MOTD
  unity-renderer/Assets/Resources/ScriptableObjects/MOTDActive.asset
  unity-renderer/Assets/Resources/ScriptableObjects/MOTDActive.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Interfaces/IHUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeHUD.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeHUDButton.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeHUDButton.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Tests/WelcomeHUDShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Tests/WelcomeHUDShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Tests/WelcomeHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Tests/WelcomeHUDTests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Textures.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Textures/MOTDHeader.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Textures/MOTDHeader.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUD.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#1924 fix: nft shape memory issue
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/DCL.Components.NFT.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/DCL.Components.NFT.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/INFTAsset.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/INFTAsset.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/NFTAssetLoadHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/NFTAssetLoadHelper.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/NFTAsset_Gif.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/NFTAsset_Gif.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/NFTAsset_Image.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/NFTAsset_Image.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/NFTInfoLoadHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/NFTInfoLoadHelper.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeConfig.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeHQImageHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeHQImageHandler.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Scripts/NFTAssetFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/DCL.Components.NFT.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/DCL.Components.NFT.Tests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTAssetLoadHelperShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTAssetLoadHelperShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTInfoFetcherShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTInfoLoadHelperShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTInfoLoadHelperShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTShapeHQImageHandlerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTShapeLoaderControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTShapeTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/WrappedTextureAsset/IPromiseLike_TextureAsset.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/WrappedTextureAsset/IPromiseLike_TextureAsset.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/WrappedTextureAsset/PromiseLikeTextureAsset.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/WrappedTextureAsset/PromiseLikeTextureAsset.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/WrappedTextureAsset/WrappedTextureAsset.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/WrappedTextureAsset/WrappedTextureAsset.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Asset.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/NFTPromptHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/LazyTextureObserver/TextureLoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/OpenSea/OpenSea.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/OpenSea/Requests/RequestBase.cs
Labels: ready for review

#1821 refactor: gif processing for better performance and multithreading
  unity-renderer/Assets/Plugins/UniGif/LICENSE
  unity-renderer/Assets/Plugins/UniGif/LICENSE.meta
  unity-renderer/Assets/Plugins/UniGif/README.md
  unity-renderer/Assets/Plugins/UniGif/UniGif.asmdef
  unity-renderer/Assets/Plugins/UniGif/UniGif.cs
  unity-renderer/Assets/Plugins/UniGif/UniGif.cs.meta
  unity-renderer/Assets/Plugins/UniGif/UniGifConst.cs
  unity-renderer/Assets/Plugins/UniGif/UniGifDecoder.cs
  unity-renderer/Assets/Plugins/UniGif/UniGifDecoder.cs.meta
  unity-renderer/Assets/Plugins/UniGif/UniGifExtension.cs
  unity-renderer/Assets/Plugins/UniGif/UniGifExtension.cs.meta
  unity-renderer/Assets/Plugins/UniGif/UniGifFormatter.cs
  unity-renderer/Assets/Plugins/UniGif/UniGifFormatter.cs.meta
  unity-renderer/Assets/Scenes/Test/UniGifStressTest.unity
  unity-renderer/Assets/Scenes/Test/UniGifStressTest.unity.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetPromiseKeeper.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/AssetPromise_Gif.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/GifProcessor/GifDecoderProcessor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/GifProcessor/GifDecoderProcessor.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/GifProcessor/GifProcessor.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/GifProcessor/GifProcessor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/GifProcessor/GifProcessor.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/GifProcessor/IGifProcessor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/GifProcessor/JSGifProcessor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/GifProcessor/JSGifProcessor.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/StressTest.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/StressTest/UniGifStressTest.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/StressTest/UniGifStressTest.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/StressTest/UniGifStressTest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/StressTest/UniGifStressTest.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/Tests/BlockedAndMasterPromisesShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/TaskUtils.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/TaskUtils.cs
  unity-renderer/Packages/manifest.json
  unity-renderer/Packages/packages-lock.json
  unity-renderer/TestResources/Gif/decentraland-loading.gif
Labels: ready for review

#1958 fix: fixes required by desktop renderer for beta flags
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/LoadingHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/LoadingHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Tests/LoadingHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Tests/LoadingHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Tests/LoadingHUDViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Tests/MinimapHUDTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Tests/NavmapToastViewShould.cs
  unity-renderer/Assets/Textures/UI/BugIcon 1.png
  unity-renderer/Assets/Textures/UI/BugIcon 1.png.meta
  unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
Labels: wip
