Repository decentraland/unity-renderer, pull requests merged in 2022-05, with the labels that each got.

#2225 fix: react to updates in player profiles
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
Labels: ready for review

#2210 feat: new asset promise keeper and new resource system
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/Data.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/Data/DCL.Components.MaterialModel.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/Data/DCL.Components.MaterialModel.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/Data/MaterialModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/Data/MaterialModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/Data.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/Data/DCL.Components.TextureModel.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/Data/DCL.Components.TextureModel.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/Data/TextureModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/Data/TextureModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetPromiseKeeper.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromise.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/AssetPromiseKeeper_Material.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/AssetPromise_Material.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/Asset_Material.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/Tests/APK_Material_Promise_Should.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/Tests/APK_Material_Promise_Should.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/Tests/APK_Material_ShouldWorkWhen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/Tests/APK_Material_ShouldWorkWhen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/Tests/APK_Material_Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/Tests/APK_Material_Tests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/Tests/BlockedAndMasterPromisesShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/Tests/BlockedAndMasterPromisesShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/AssetPromiseKeeper_TextureResource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/AssetPromiseKeeper_TextureResource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/AssetPromise_TextureResource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/AssetPromise_TextureResource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/Asset_TextureResource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/Asset_TextureResource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/Tests/APK_DCLTexture_Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/Tests/APK_DCLTexture_Tests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/Tests/APK_TextureResource_Promise_Should.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/Tests/APK_TextureResource_Promise_Should.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/Tests/APK_TextureResource_ShouldWorkWhen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/Tests/APK_TextureResource_ShouldWorkWhen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/Tests/BlockedAndMasterPromisesShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/TextureResource/Tests/BlockedAndMasterPromisesShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DCLResources.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.asmdef
Labels: ready for review

#2215 feat: Throttled Profanity Filter
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/IProfanityFilter.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/IProfanityFilter.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/ProfanityFilterSharedInstances.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/RegexProfanityFilter.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/ThrottledRegexProfanityFilter.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/ThrottledRegexProfanityFilter.cs.meta
Labels: ready for review

#2228 feat: Add a loading spinner in the taskbar while the Friends feature is being initialized
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Common/Friends/RealmTrackerController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
Labels: ready for review

#2235 Chore: cap scene load radius to 4
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/ScenesLoadRadiusControlConfiguration.asset
Labels: ready for review

#2240 fix: local gltf import
  unity-renderer/Assets/ABConverter/Core.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/TaskUtils.cs
  unity-renderer/Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs
  unity-renderer/Assets/UnityGLTF/Scripts/Editor/GLTFImporterInspector.cs
  unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Labels: ready for review

#2212 feat: ecs7 components runtime
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/DCL.ECSRuntime.Components.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/DCL.ECSRuntime.Components.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/ECSComponent.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/ECSComponent.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/ECSComponentData.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/ECSComponentData.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/Interfaces.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/Interfaces/DCL.ECSRuntime.Components.Inferfaces.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/Interfaces/DCL.ECSRuntime.Components.Inferfaces.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/Interfaces/IECSComponent.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/Interfaces/IECSComponent.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/Interfaces/IECSComponentHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Components/Interfaces/IECSComponentHandler.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsManager.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsManager/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsManager/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsManager/DCL.ECSRuntime.ComponentsManager.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsManager/DCL.ECSRuntime.ComponentsManager.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsManager/ECSComponentsManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsManager/ECSComponentsManager.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/DCL.ECSRuntime.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/DCL.ECSRuntime.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Factory.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Factory/DCL.ECSRuntime.Factory.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Factory/DCL.ECSRuntime.Factory.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Factory/ECSComponentsFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Factory/ECSComponentsFactory.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/DCL.ECSRuntime.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/DCL.ECSRuntime.Tests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/ECSComponentShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/ECSComponentShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/ECSComponentsManagerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/ECSComponentsManagerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/TestingComponent.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/TestingComponent.cs.meta
Labels: ready for review

#2249 fix: desktop crash due to multithreading issues
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
Labels: ready for review

#2255 fix: increase performance in hot code path
  unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/Tests/UUIDComponentTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/EntityIdHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/MessagingControllersManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/EntityIdHelperShould.cs
  unity-renderer/Assets/Scripts/Tests/TestUtils.cs
Labels: enhancement, merge me!

#2216 fix: now that hasConnectedWeb3 is fixed we can use it.
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
Labels: ready for review

#2045 fix: components not being removed on `ComponentRemoved` message
  unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/OnPointerHoverEnter.cs
  unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/OnPointerHoverEvent.cs
  unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/OnPointerHoverExit.cs
  unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/UUIDComponent.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Animator/DCLAnimator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioStream.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/AvatarModifierArea.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/AvatarAttach/AvatarAttachComponent.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Billboard/Billboard.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/Gizmos/DCLGizmos.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/SmartItem/SmartItemComponent.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/CameraModeArea/CameraModeArea.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/QuestTrackingInfo/QuestTrackingInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSComponentManagerLegacy/ECSComponentsManagerLegacy.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/BaseComponent.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.cs
Labels: ready for review

#2242 feat: CRDT deserializer
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/CRDTMessage.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/CRDTProtocol.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/CRDTDeserializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/CRDTDeserializer.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/CRDTDeserializerTypes.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/CRDTDeserializerTypes.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/DCL.CRDTProtocol.Deserializer.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/DCL.CRDTProtocol.Deserializer.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/Tests/CRDTDeserializerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/Tests/CRDTDeserializerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/Tests/DCL.CRDTProtocol.Deserializer.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/Tests/DCL.CRDTProtocol.Deserializer.Tests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Tests/CRDTTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Tests/CRDTTestsUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/ByteArrayReader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/ByteArrayReader.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/ByteUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/ByteUtils.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/IBinaryReader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/IBinaryReader.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/KernelCommunication.BinaryReader.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/KernelCommunication.BinaryReader.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/UnmanagedMemoryReader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/UnmanagedMemoryReader.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageDeserializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageDeserializer.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageHeader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageHeader.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageType.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelBinaryMessageType.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelCommunication.BinaryMessage.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/KernelCommunication.BinaryMessage.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Tests/KernelBinaryMessageShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Tests/KernelBinaryMessageShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Tests/KernelCommunication.BinaryMessage.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Tests/KernelCommunication.BinaryMessage.Tests.asmdef.meta
Labels: ready for review

#2270 Fix: avoid bug that duplicated animations in memory
  unity-renderer/Assets/DCLPlugins/EmoteAnimations/EmoteAnimationLoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/EmoteAnimationEquipper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/EmoteAnimationEquipperShould.cs
Labels: ready for review

#2224 refactor: remove `SceneLifeCycle` components dependency
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DCL.Runtime.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/LoadingFeedbackController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneLifecycleHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/IResourcesLoadTracker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/IResourcesLoadTracker.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/ResourcesLoadTrackerLegacyECS.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/ResourcesLoadTrackerLegacyECS.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/SceneResourcesLoadTracker.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/SceneResourcesLoadTracker.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/SceneResourcesLoadTracker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/SceneResourcesLoadTracker.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/Tests/MockedSharedComponentHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/Tests/MockedSharedComponentHelper.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/Tests/ResourcesLoadTrackerLegacyECSShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/Tests/ResourcesLoadTrackerLegacyECSShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/Tests/SceneResourcesLoadTracker.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/Tests/SceneResourcesLoadTracker.Tests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/Tests/SceneResourcesLoadTrackerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneResourcesLoadTracker/Tests/SceneResourcesLoadTrackerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.cs
Labels: ready for review

#2289 Fix: allow user to play emotes on moving platforms
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
Labels: ready for review

#2288 fix: PBRMaterial ref count
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs
Labels: ready for review

#2262 fix: disabled freefall camera when standing on invisible colliders
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Resources/Prefabs/CharacterController.prefab
Labels: ready for review

#2310 fix: fix biw publish
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/ScenesController/SceneData.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Tests/ProjectCardViewShould.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Tests/ProjectSceneCardViewShould.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Tests/SceneDataShould.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/Scripts/Publisher.cs
  unity-renderer/Assets/DCLPlugins/ECS7.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Definitions.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DeployedScenesFetcher/LandWithAccess/Scene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Interfaces/CatalystTypes.cs
Labels: ready for review

#2316 fix: Remove unused prefabs and references (Renderer side)
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Tests/BIWOutlinerShould.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Tests/BIWSceneManagerShould.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Tests/Modes/BIWGodModeShould.cs
  unity-renderer/Assets/Prefabs/Resources/SettingsController.prefab
  unity-renderer/Assets/Prefabs/Resources/SettingsController.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/Tests/SettingsControlsShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/InitialSceneReferences/MainSceneFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DCL.Runtime.asmdef
Labels: ready for review

#2297 refactor: biw prepare for ecs7
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/BIWBridge.asmdef
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/BuilderInWorldBridge.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/ECSComponentSenderHandler.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/ECSComponentSenderHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/IComponentSendHandler.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/IComponentSendHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/LegacyComponentSender.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/LegacyComponentSender.cs.meta
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Data/BuilderScene/BuilderScene.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Interfaces/IBuilderScene.cs
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/SceneManager/SceneManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/InitialSceneReferences/MainSceneFactory.cs
Labels: ready for review

#2328 fix: taskbar buttons when entering as a guest
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
Labels: critical, ready for review

#2320 feat: send binary message to kernel
  browser-interface/src/index.ts
  unity-renderer/Assets/Plugins/JSFunctions.jslib
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryWriter.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryWriter/BinaryWriter.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryWriter/BinaryWriter.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryWriter/KernelCommunication.BinaryWriter.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryWriter/KernelCommunication.BinaryWriter.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/DCLWebSocketService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/WebSocketCommunication.asmdef
Labels: ready for review

#2338 chore: moved chat entries prefabs to resources folder
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/DefaultChatEntryShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChatEntrySystem.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChatEntrySystem.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatEntryReceived.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatEntryReceived.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatEntrySent.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatEntrySent.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PublicChatEntryReceived.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PublicChatEntryReceived.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PublicChatEntryReceivedWhisper.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PublicChatEntryReceivedWhisper.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PublicChatEntrySent.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PublicChatEntrySent.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PublicChatEntrySentWhisper.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PublicChatEntrySentWhisper.prefab.meta
Labels: ready for review

#2329 feat: add plane shape component for the new ECS
  unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Data.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/AssemblyInfo.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/AssemblyInfo.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/DCL.ECSComponents.PlaneShape.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/DCL.ECSComponents.PlaneShape.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/Data.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/Data/DCL.ECSComponents.BoxShapeData.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/Data/DCL.ECSComponents.BoxShapeData.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/Data/ECSPlaneShape.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/Data/ECSPlaneShape.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/ECSPlaneShapeComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/ECSPlaneShapeComponentHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/Tests/DCL.Components.ECSPlaneShapeShould.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/Tests/DCL.Components.ECSPlaneShapeShould.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/Tests/ECSPlaneShapeShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PlaneShape/Tests/ECSPlaneShapeShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/PrimitiveMeshFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/DCLResources/PrimitiveMeshModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/Engineinterface.cs
Labels: ready for review

#2336 fix: send avatar rotation through comms
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
Labels: ready for review

#2326 feat: add audio stream component for new ECS
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioSource/ECSAudioSourceComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/AssemblyInfo.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/AssemblyInfo.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/DCL.ECSComponents.AudioStream.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/DCL.ECSComponents.AudioStream.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Data.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Data/ECSAudioStream.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Data/ECSAudioStream.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/ECSAudioStreamComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/ECSAudioStreamComponentHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests/DCL.Components.ECSAudioStreamShould.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests/DCL.Components.ECSAudioStreamShould.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests/ECSAudioStreamShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests/ECSAudioStreamShould.cs.meta
Labels: ready for review

#2352 fix: performance optimizations when user has many friends
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendEntry.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendEntryBase.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendEntryModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendEntryModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendRequestEntry.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendRequestEntryModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendRequestEntryModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/IFriendsHUDComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/CollapsableSortedFriendEntryList.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendRequestsTabComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendsTabComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendEntryShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendRequestEntryShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/FriendsHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/FriendsHUDWindowMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/CollapsableSortedList/CollapsableSortedListComponentView.cs
Labels: ready for review

#2357 style: linked wearables dropdown
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
Labels: ready for review

#2363 fix: remove bodyshape from hides lists
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CatalogController/CatalogController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/Tests/WearableItemShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
Labels: ready for review

#2360 fix: remove perfomance regression
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Editor.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Editor/DCL.Protobuf.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Editor/DCL.Protobuf.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Editor/ProtobufEditor.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Editor/ProtobufEditor.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Editor/protoc.exe
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Editor/protoc.exe.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/BoxShape.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/BoxShape.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Definitions.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Definitions/BoxShape.proto
  unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Definitions/BoxShape.proto.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/Plugins/Google.Protobuf.dll
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/Plugins/System.Buffers.dll
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/Plugins/System.Buffers.dll.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/Plugins/System.Memory.dll
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/Plugins/System.Memory.dll.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/Plugins/System.Runtime.CompilerServices.Unsafe.dll
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/Plugins/System.Runtime.CompilerServices.Unsafe.dll.meta
Labels: ready for review

#2366 fix: limited the amount of private chat channels & optimized loading hiccups
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendsTabComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ConversationListHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/WorldChatWindowViewMock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/CollapsableChatSearchListComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IWorldChatWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PrivateChatEntry.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/CollapsableSortedList/CollapsableSortedListComponentView.cs
Labels: ready for review

#2354 feat: chat history iteration with up & down keys
  unity-renderer/Assets/Resources/Prefabs/InputController.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/IChatHUDComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChatHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/ChatNextInHistory.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/ChatNextInHistory.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/ChatPreviousInHistory.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/ChatPreviousInHistory.asset.meta
Labels: ready for review

#2359 Fix: facial feature refresh
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/LoaderDefinitions/IBodyshapeLoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/BodyShapeLoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/Loader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/BodyshapeLoaderShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/LoaderShould.cs
Labels: ready for review

#2375 fix: unhandled exception when loading base64 images
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetPromise_Texture.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Tests/APK_Texture_Promise_Should.cs
Labels: ready for review

#2365 feat: add local testscene for ecs7 components
  unity-renderer/Assets/DCLPlugins/ECS7/Editor.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECS7Plugin.TestScene.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECS7Plugin.TestScene.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECS7TestScene.unity
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECS7TestScene.unity.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECSTestScene.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECSTestScene.cs.meta
Labels: ready for review
