Repository decentraland/unity-renderer, pull requests merged in 2023-05, with the labels that each got.

#5085 feat: implementation of empty state of the wearable grid
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorV2Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IWearableGridView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearablesSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDV2Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs
Labels: stream-social

#5064 feat: backpack v2 wearables new endpoint
  unity-renderer/Assets/DCLServices/Lambdas/ILambdasService.cs
  unity-renderer/Assets/DCLServices/Lambdas/LambdasService.cs
  unity-renderer/Assets/DCLServices/Lambdas/PaginatedResponse.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/IWearablesCatalogService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/LambdasWearablesCatalogService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/NftOrderByOperation.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/NftOrderByOperation.cs.meta
  unity-renderer/Assets/DCLServices/WearablesCatalogService/NftRarity.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/NftRarity.cs.meta
  unity-renderer/Assets/DCLServices/WearablesCatalogService/Tests/LambdasWearablesCatalogServiceShould.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearableResponse.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearablesCatalogServiceProxy.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WebInterfaceWearablesCatalogService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridItemComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/Tests/Helpers/AvatarAssetsTestHelpers.cs
Labels: stream-social

#5103 feat: new wearable label
  unity-renderer/Assets/DCLServices/WearablesCatalogService/LambdasWearablesCatalogService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearableResponse.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
Labels: stream-social

#5069 feat: filters bar for the backpack v2
  unity-renderer/Assets/DCLServices/Lambdas/LambdasService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/IWearablesCatalogService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/LambdasWearablesCatalogService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/NftCollectionType.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/NftCollectionType.cs.meta
  unity-renderer/Assets/DCLServices/WearablesCatalogService/Tests/LambdasWearablesCatalogServiceShould.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearableResponse.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearablesCatalogService.asmdef
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearablesCatalogServiceProxy.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WebInterfaceWearablesCatalogService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2ComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorV2Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackFiltersComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackFiltersComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackFiltersController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackFiltersController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackFiltersComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackFiltersComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/BackpackFilters.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/BackpackFilters.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDV2Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackFiltersComponentViewTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackFiltersComponentViewTests.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackFiltersControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackFiltersControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/WearablesHelper/WearablesFetchingHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/Tests/Helpers/AvatarAssetsTestHelpers.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/PageSelector/PageSelectorComponentView.cs
Labels: stream-social

#5116 Fix: different backpack v2 fixes
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftRarityBackground.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftRarityBackgroundSO.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftTypeColorSupporting.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftTypeIcons.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftWearableRarityBackground.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/BackpackInfoCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearableGridItemView.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/AvatarSlotsDefinition.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridItemComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypesIcons.asset
  unity-renderer/Assets/Textures/UI/BackpackV2/InfoCardBase.png
  unity-renderer/Assets/Textures/UI/BackpackV2/InfoCardBase.png.meta
Labels: No QA Needed, stream-social

#5122 Fix: various backpack v2 fixes
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftRarityBackground.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftRarityBackgroundSO.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftTypeColorSupporting.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftTypeIcons.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftWearableRarityBackground.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/BackpackInfoCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearableGridItemView.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/AvatarSlotsDefinition.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridItemComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypesIcons.asset
  unity-renderer/Assets/Textures/UI/BackpackV2/InfoCardBase.png
  unity-renderer/Assets/Textures/UI/BackpackV2/InfoCardBase.png.meta
Labels: No QA Needed, stream-social

#5124 Chore: added hidden avatar slots tests
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/AvatarSlotComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/AvatarSlotComponentViewShould.cs.meta
Labels: stream-social

#5121 Feat: intercom button
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUDDesktop.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDView.cs
Labels: stream-discoverability

#5120 fix: backpack v2 breadcrumb filters & icons
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IWearableGridView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftBreadcrumbComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftBreadcrumbModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftSubCategoryFilterComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftSubCategoryFilterModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/NftBreadcrumberSubcategoryFilter.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearablesBreadcrumb.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearablesSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearablesSection.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/NftBreadcrumbComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/NftSubCategoryFilterComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypeIconsAndColors.cs
Labels: stream-social

#5132 feat: ability of pre-visualize wearables before equipping
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
Labels: stream-social

#5137 feat: update backpack v2 main endpoint
  unity-renderer/Assets/DCLServices/WearablesCatalogService/LambdasWearablesCatalogService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/Tests/LambdasWearablesCatalogServiceShould.cs
Labels: No QA Needed, stream-social

#5105 Added analytics definition and integration for new backpack
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackAnalyticsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackAnalyticsTypes.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackAnalyticsTypes.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorV2Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackFiltersController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackAnalyticsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackAnalyticsController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IWearableGridView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackAnalyticsControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
Labels: No QA Needed, stream-social

#5135 feat: Added jump in button support for quest tracker steps
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/IQuestStepComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/IQuestTrackerComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestStepComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestStepComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestTrackerComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestTrackerComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Resources/QuestStep.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Resources/QuestTrackerHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestStepComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestTrackerComponentViewShould.cs
Labels: No QA Needed, stream-discoverability

#5136 feat: limit color presets for body shape category in backpack v2
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackColorPickerPresetsForSkin.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackColorPickerPresetsForSkin.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2ComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackEditorHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearablesSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDV2ComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDV2ComponentViewShould.cs.meta
  unity-renderer/Assets/UIComponents/Resources/ColorPicker.prefab
  unity-renderer/Assets/UIComponents/Scripts/Components/ColorPicker/ColorPickerComponentModel.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/ColorPicker/ColorPickerComponentView.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/ColorPicker/ColorSelector.cs
Labels: stream-social

#5142 fix: boundaries not being in sync with the SBC
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MeshesInfo/MeshesInfo.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MeshesInfo/MeshesInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MeshesInfo/MeshesInfoUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Interfaces/ISceneBoundsChecker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsFeedbackStyle_RedBox.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SBC_Asserts.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.cs
Labels: stream-core

#5042 feat: sdk7 video events
  scripts/package-lock.json
  scripts/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/ECS7ComponentsComposer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/Tests/VideoPlayerHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/VideoEventRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/VideoEventRegister.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/VideoPlayerHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/VideoPlayerRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentModels.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECS7Plugin.Systems.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VideoPlayerSystem/ECS7Plugin.Systems.VideoPlayer.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VideoPlayerSystem/ECSVideoPlayerSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VideoPlayerSystem/Tests/ECS7Plugin.Systems.VideoPlayer.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VideoPlayerSystem/Tests/ECSVideoPlayerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/VideoState.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/ComponentID.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/social/friendships/ClientFriendshipsService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/VideoEvent.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/VideoEvent.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentWriter/ECSComponentWriter.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentWriter/Interfaces/IECSComponentWriter.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/ECSComponentWriterShould.cs
  unity-renderer/Packages/manifest.json
  unity-renderer/Packages/packages-lock.json
Labels: No QA Needed

#5104 fix: sdk7 pointer events input
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/ProtoConvertUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/Extensions/InternalInputEventResultsExtensions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECSPointerInputSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/EntityInputShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/EntityInputShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/GlobalInputShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/GlobalInputShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/HoverFeedbackShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/HoverFeedbackShould.cs.meta
Labels: No QA Needed

#5150 fix: performance meter not working for loading flow
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/DebugParameters/DebugConfigComponent.cs
Labels: stream-core

#5172 fix: added cancellation handling on rendereable asset fallback
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
Labels: No QA Needed, stream-core

#5170 feat: Physics.Bake in AB loading flow with a Feature Flag
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
Labels: No QA Needed, stream-core

#5164 feat: [Social service] Fetch friend requests
  browser-interface/package-lock.json
  browser-interface/package.json
  scripts/package-lock.json
  scripts/package.json
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendRequest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/ISocialApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/ProxySocialApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/RPCSocialApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/FriendsControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/Helpers/FriendsController_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/RPCSocialApiBridgeShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/social/friendships/ClientFriendshipsService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/social/friendships/FriendshipsService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Friendships.gen.cs
Labels: no_reviewers

#5182 Feat: quest details section for quest log panel
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestDetails.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestDetails/IQuestDetailsComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestDetails/IQuestDetailsComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestDetails/QuestDetailsComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestDetails/QuestDetailsComponentModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestDetails/QuestDetailsComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestDetails/QuestDetailsComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestDetails/QuestDetailsSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestDetails/QuestDetailsSection.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestDetails/QuestStep Variant.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestDetails/QuestStep Variant.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestStepComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestDetailsComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestDetailsComponentViewShould.cs.meta
Labels: stream-discoverability

#5078 Feat: added new prefab for active quests
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/ActiveQuest.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/ActiveQuest/ActiveQuest.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/ActiveQuest/ActiveQuest.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/ActiveQuest/ActiveQuestComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/ActiveQuest/ActiveQuestComponentModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/ActiveQuest/ActiveQuestComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/ActiveQuest/ActiveQuestComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/ActiveQuest/IActiveQuestComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/ActiveQuest/IActiveQuestComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/ActiveQuestComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/ActiveQuestComponentViewShould.cs.meta
Labels: No QA Needed, stream-discoverability

#5195 fix: exception caused by fetching the scene ID from the new urn format
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/SceneAB/AssetPromise_SceneAB.cs
Labels: stream-core

#4756 chore: added handy override to change wearables catalog based on another user id
  unity-renderer/Assets/DCLServices/WearablesCatalogService/LambdasWearablesCatalogService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DebugConfig.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/DebugParameters/DebugConfigComponent.cs
Labels: No QA Needed, stream-core

#5213 chore: sdk7 remove texture mirror-once
  browser-interface/package-lock.json
  browser-interface/package.json
  scripts/package-lock.json
  scripts/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Tests/TextureDefaults/TextureShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Texture.gen.cs
Labels: No QA Needed

#5231 feat: added quest started popup and tests
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestOfferHUD/IQuestStartedPopupComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestOfferHUD/IQuestStartedPopupComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestOfferHUD/QuestStartedPopupComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestOfferHUD/QuestStartedPopupComponentModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestOfferHUD/QuestStartedPopupComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestOfferHUD/QuestStartedPopupComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestOfferHUD/QuestStartedPopupHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestOfferHUD/QuestStartedPopupHUD.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestHUDTest.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestStartedPopupComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestStartedPopupComponentViewShould.cs.meta
Labels: No QA Needed, stream-discoverability

#5153 Feat: PoC for merging removal and hide list
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarCurator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/AvatarSettings.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/AvatarCuratorShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/LoaderShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/WearableLoaderShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/IAvatarSlotComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/IAvatarSlotsView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2ComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackEditorHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/InfoCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftBreadcrumbComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/AvatarSlot.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/BackpackInfoCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearableGridItemView.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/AvatarSlotComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridItemComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/CharacterPreview/CharacterPreviewController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/ButtonDoubleClick.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/ButtonDoubleClick.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/HUDCommon.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/IButtonDoubleClick.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/IButtonDoubleClick.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/AvatarAssets.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableLiterals.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModel.cs
  unity-renderer/Assets/Textures/UI/Common/TexturesUI.spriteatlas
  unity-renderer/Assets/Textures/UI/Common/VisibleIcon.png
  unity-renderer/Assets/Textures/UI/Common/VisibleIcon.png.meta
Labels: stream-social

#5246 fix: plugins creation exception handling
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginInfo.cs
Labels: No QA Needed

#5237 fix: exception from AB (possible memory leak)
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
Labels: No QA Needed

#5251 feat: sdk7 implement`GltfContainer` collider properties
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBGltfContainer_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBGltfContainer_Defaults.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/DCL.ECSComponents.GltfContainer.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerCollidersHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerCollidersHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/DCL.ECSComponents.GltfContainer.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/GltfContainerCollidersShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/GltfContainerCollidersShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/GltfContainerComponentLifeCycleShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/GltfContainerComponentLifeCycleShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/GltfContainerHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/GltfContainerRenderersShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/GltfContainerRenderersShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/MeshColliderHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/LayerMaskUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/Extensions/InternalCollidersExtensions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/Extensions/InternalRenderersExtensions.cs
Labels: No QA Needed

#5257 fix: moved help icon to the taskbar
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-renderer/Assets/Textures/UI/Common/TexturesUI.spriteatlas
Labels: stream-discoverability

#5259 feat: add `forceRenderer` property
  browser-interface/package-lock.json
  browser-interface/package.json
  browser-interface/packages/lib/decentraland/profiles/sceneRuntime/AvatarForUserData.ts
  browser-interface/packages/lib/decentraland/profiles/sceneRuntime/sceneRuntimeCompatibleAvatar.ts
  browser-interface/packages/lib/decentraland/profiles/transformations/profileToRendererFormat.ts
  browser-interface/packages/lib/decentraland/profiles/transformations/profileToServerFormat.ts
  browser-interface/packages/shared/profiles/sagas/handleDeployProfile.ts
  browser-interface/packages/unity-interface/BrowserInterface.ts
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/CharacterPreview/CharacterPreviewController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModelDTO.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModelDTO.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileModelDTO.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileModelDTO.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/WebInterface.asmdef
Labels: No QA Needed, stream-social
