Repository decentraland/unity-renderer, pull requests merged in 2023-01, with the labels that each got.

#3870 fix: sdk7 hotreload
  unity-renderer/Assets/DCLPlugins/ECS7/ComponentCrdtWriteSystem/ComponentCrdtWriteSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ComponentCrdtWriteSystem/Tests/ComponentCrdtWriteSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
Labels: No QA Needed

#3871 fix: sdk7 hotreload test
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Tests/ECS7HotReload.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Tests/ECS7Plugin.Tests.asmdef
Labels: No QA Needed

#3851 feat: Add Lambdas Service
  unity-renderer/Assets/DCLServices/Lambdas.meta
  unity-renderer/Assets/DCLServices/Lambdas/AssemblyInfo.cs
  unity-renderer/Assets/DCLServices/Lambdas/AssemblyInfo.cs.meta
  unity-renderer/Assets/DCLServices/Lambdas/ILambdasService.cs
  unity-renderer/Assets/DCLServices/Lambdas/ILambdasService.cs.meta
  unity-renderer/Assets/DCLServices/Lambdas/LambdasService.asmdef
  unity-renderer/Assets/DCLServices/Lambdas/LambdasService.asmdef.meta
  unity-renderer/Assets/DCLServices/Lambdas/LambdasService.cs
  unity-renderer/Assets/DCLServices/Lambdas/LambdasService.cs.meta
  unity-renderer/Assets/DCLServices/Lambdas/Tests.meta
  unity-renderer/Assets/DCLServices/Lambdas/Tests/LambdasServiceShould.cs
  unity-renderer/Assets/DCLServices/Lambdas/Tests/LambdasServiceShould.cs.meta
  unity-renderer/Assets/DCLServices/Lambdas/Tests/LambdasServiceTests.asmdef
  unity-renderer/Assets/DCLServices/Lambdas/Tests/LambdasServiceTests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AudioClip/AssetPromise_AudioClip.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFDownloaderWrapper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFTextureDownloaderWrapper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFastDownloadProvider.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/GifProcessor/GifDecoderProcessor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetPromise_Texture.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapChunk.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests/MapChunk_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/GetWebRequestFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/GetWebRequestFactory.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IPostWebRequestFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IPostWebRequestFactory.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestAssetBundleFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestAssetBundleFactory.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestAsyncOperation.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestAsyncOperation.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestAudioFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestAudioFactory.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestFactory.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestTextureFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestTextureFactory.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/WebRequestAsyncOperation.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/PostWebRequestFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/PostWebRequestFactory.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestAssetBundleFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestAssetBundleFactory.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestAudio.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestAudioFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestAudioFactory.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestTextureFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestTextureFactory.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Catalyst.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Interfaces/ICatalyst.cs
  unity-renderer/Assets/UnityGLTF/Scripts/Loader/WebRequestLoader.cs
Labels: No QA Needed

#3846 feat: new data store for decoupled loading screen
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECS7Plugin.Systems.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/LoadingScreenPlugin/LoadingScreenPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Bridge/LoadingBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/LoadingHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/LoadingHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Tests/LoadingHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SignupHUD/SignupHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Tests/LoadingScreenControllerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_FeatureFlag.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_HUDs.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_LoadingScreen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_LoadingScreen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/FatalErrorReporter/DefaultFatalErrorReporter.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/MouseCatcher/MouseCatcher.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/DebugParameters/DebugConfigComponent.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/LoadingFeedbackController.cs
Labels: No QA Needed

#3890 fix: sdk7 set Material's albedo color as type Color4
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBMaterial_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/Tests/MaterialHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/MaterialSystem/Tests/ECSMaterialSystemShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Crdt.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Material.gen.cs
Labels: No QA Needed

#3896 Chore: double call in explore v2 on select
  unity-renderer/.editorconfig
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2ComponentRealmsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2ComponentRealmsController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/IExploreV2MenuComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/IExploreV2MenuComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentControllerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ThumbnailsManager/ThumbnailsManager.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/SectionSelector/SectionToggle.cs
  unity-renderer/unity-renderer.sln.DotSettings
Labels: No QA Needed

#3907 feat: decoupled loading screen percentage controller
  unity-renderer/Assets/DCLPlugins/LoadingScreenPlugin/DCLPlugins.LoadingScreenPlugin.asmdef
  unity-renderer/Assets/DCLPlugins/LoadingScreenPlugin/LoadingScreenPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/DCL.LoadingScreen.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Interfaces/ILoadingScreenView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/BodyFilled.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/BodyFilled.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/BodyStroke.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/BodyStroke.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/Cross.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/Cross.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/Portal.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/Portal.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/PortalGradient.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/PortalGradient.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/PortalLine02.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/PortalLine02.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/PortalMask.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/PortalMask.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/Ring.png
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/Ring.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/TeleportLoadingAtlas.spriteatlas
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/Teleport/TeleportLoadingAtlas.spriteatlas.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/TeleportLoading.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/TeleportLoading.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/_LoadingScreen.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenPercentageController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenPercentageController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenPercentageView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenPercentageView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenTipsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenTipsView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Tests/DCL.LoadingScreen.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Tests/LoadingScreenControllerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Tests/LoadingScreenViewTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/FatalErrorReporter/DefaultFatalErrorReporter.cs
Labels: No QA Needed

#3924 feat: decoupled loading screen blit background
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Interfaces/ILoadingScreenView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/_LoadingScreen.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Tests/LoadingScreenControllerTests.cs
Labels: No QA Needed

#3939 chore: remove LINQ from AvatarsLODController
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarsLODController.cs
Labels: No QA Needed

#3817 feat: sentry integration
  .circleci/config.yml
  ci-benchmark.sh
  ci-editmode-test.sh
  ci-playmode-test.sh
  ci-setup.sh
  convert-asset-bundles.sh
  scripts/.gitignore
  scripts/package-lock.json
  scripts/package.json
  scripts/src/inject-sentry-params.ts
  scripts/src/tsconfig.json
  scripts/tsconfig.json
  unity-renderer/Assets/Plugins/Sentry.meta
  unity-renderer/Assets/Plugins/Sentry/SentryBuildtimeOptionsConfiguration.asset
  unity-renderer/Assets/Plugins/Sentry/SentryBuildtimeOptionsConfiguration.asset.meta
  unity-renderer/Assets/Plugins/Sentry/SentryCliOptions.asset
  unity-renderer/Assets/Plugins/Sentry/SentryCliOptions.asset.meta
  unity-renderer/Assets/Resources/Sentry.meta
  unity-renderer/Assets/Resources/Sentry/SentryOptions.asset
  unity-renderer/Assets/Resources/Sentry/SentryOptions.asset.meta
  unity-renderer/Assets/Resources/Sentry/SentryRuntimeOptionsConfiguration.asset
  unity-renderer/Assets/Resources/Sentry/SentryRuntimeOptionsConfiguration.asset.meta
  unity-renderer/Assets/Scripts/Editor/MainEditor.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
  unity-renderer/Packages/manifest.json
  unity-renderer/Packages/packages-lock.json
Labels: stream-core

#3974 chore: align main dev 2023 01 11
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/AvatarShape.cs
  unity-renderer/Assets/DCLServices/Lambdas/LambdasService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarOnPointerDown/AvatarOutlineOnHoverEvent.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/CharacterPreview/CharacterPreviewController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPreview/PassportPlayerPreviewComponentController.cs
Labels: No QA Needed

#4024 Fix decoupled loading screen enabled when the AB test is off
  unity-renderer/Assets/DCLPlugins/LoadingScreenPlugin/LoadingScreenPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_LoadingScreen.cs
Labels: No QA Needed

#4037 fix: sdk7 exception while removing parent entity
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Handler/ECSTransformHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Tests/ECSTransformParentingSystemShould.cs
Labels: No QA Needed

#4038 fix: Offline friends sometimes don't load
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/RPCFriendsApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/FriendsControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/Helpers/FriendsController_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/WebInterfaceFriendsApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/WebInterfaceFriendsApiBridgeProxy.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
Labels: stream-social

#4063 fix: SceneControllerServiceShould test randomly failing
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests/SceneControllerServiceShould.cs
Labels: No QA Needed

#4025 Chore: refactor passport related code to address tech debt
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/ISocialAnalytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/SocialAnalytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Interfaces/IHUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTIconComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTIconComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NftPageView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/IPassportApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/IPlayerPassportHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/IPassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/IPassportPlayerInfoComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportReferenceContainer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportReferenceContainer.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/WebInterfacePassportApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/PassportHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PlayerPassport.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/PassportHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/PassportHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/PassportHUDViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Tests/PlayerInfoCardHUDViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_HUDs.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/Interfaces/ITheGraph.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/TheGraph.cs
Labels: stream-social

#4104 feat: disable sentry on prod
  ci-build.sh
Labels: No QA Needed

#4071 fix: avatar shape with null user id failing to load
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/PlayerName.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileWebInterfaceBridge.cs
Labels: stream-core

#4095 Errors only show when there are no fallbacks anymore (Asset Promises Handling)
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/APK_AB_GameObject_Promise_Should.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/BlockedAndMasterPromisesShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Tests/APKWithPoolableAssetShouldWorkWhen_Base.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
Labels: stream-core, priority: high

#4117 Fix: restored missing prefab for desktop build
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab.meta
Labels: No QA Needed, no_reviewers

#4097 fix: collider setup in sdk7 not working with gltfast
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerHandler.cs
Labels: No QA Needed

#3768 doc: update code snippets
  docs/how-to-renderer-protocol.md
Labels: No QA Needed

#4165 chore: update githubactions with new branch name
  .github/workflows/main.yml
  README.md
Labels: No QA Needed

#4166 chore: try to restore cache from `dev` branch if not exists
  .circleci/config.yml
Labels: No QA Needed

#4159 Fix: removed pointless log error for passport opening ct exception
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDView.cs
Labels: No QA Needed, stream-social
