Repository decentraland/unity-renderer, pull requests merged in 2023-02, with the labels that each got.

#4185 fix: command /version was reporting the kernel/renderer version inste…
  browser-interface/packages/shared/chat/sagas.ts
  browser-interface/packages/shared/rolloutVersions.ts
  browser-interface/packages/shared/session/getPerformanceInfo.ts
  docs/how-to-renderer-protocol.md
Labels: No QA Needed

#4197 fix: consume @dcl/explorer instead of @dcl/unity-renderer/@dcl/kernel
  browser-interface/packages/unity-interface/kernelConfigForRenderer.ts
  browser-interface/packages/unity-interface/loader.ts
Labels: No QA Needed

#4204 hotfix: Fix interactivity of the scenes input texts
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIInputText/Resources/UIInputText.prefab
Labels: release

#4201 chore: suppress warning on hiding deprecated "animation" field
  unity-renderer/Assets/Scripts/CodeStyleExample.cs
Labels: No QA Needed

#4223 fix: disable `CallGetCurrentStateWithoutStoredState` flaky test
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests/SceneControllerServiceShould.cs
Labels: No QA Needed

#4158 Feat: added missing passport analytics
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/ISocialAnalytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/SocialAnalytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/SocialAnalyticsTypes.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/CharacterPreview/PreviewCameraRotation.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPreview/IPassportPlayerPreviewComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPreview/PassportPlayerPreviewComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPreview/PassportPlayerPreviewComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/PassportHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDViewV2.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.cs
Labels: No QA Needed, stream-social

#4219 Web Request Layer new API
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/WebRequestControllerInterfaces.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequest.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestController.cs
Labels: enhancement, No QA Needed, stream-core

#4144 Add video error load texture
  unity-renderer/Assets/Resources/Textures/VideoFailed.png
  unity-renderer/Assets/Resources/Textures/VideoFailed.png.meta
  unity-renderer/Assets/Resources/Textures/VideoLoading.png
  unity-renderer/Assets/Resources/Textures/VideoLoading.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/WebVideoPlayerShould.cs
Labels: stream-core

#4253 chore: align dev to main 2023 02 03
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CatalogController/CatalogController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsFeedbackStyle_RedBox.cs
Labels: No QA Needed

#4229 add scene api & isPreview to runtime api
  browser-interface/package-lock.json
  browser-interface/package.json
  browser-interface/packages/shared/apis/host/Runtime.ts
  browser-interface/packages/shared/apis/host/Scene.ts
  browser-interface/packages/shared/apis/host/index.ts
Labels: No QA Needed

#4259 fix: preview mode
  browser-interface/packages/shared/scene-loader/sagas.ts
  browser-interface/runTestServer.js
  browser-interface/static/preview.html
Labels: No QA Needed

#4274 chore: align `dev` from `main` 2023 02 06
  browser-interface/build.js
  browser-interface/packages/entryPoints/index.ts
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CatalogController/CatalogController.cs
Labels: No QA Needed

#4279 chore: add "No QA Needed" label to exclussion list in auto assign tool
  .github/auto_assign_config.yml
Labels: No QA Needed

#4255 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: No QA Needed

#3266 Fix: typos
  README.md
Labels: stream-core

#4110 Chore: social improvements
  unity-renderer/Assets/Rendering/UI/ChargeWheel/M_ChargeBarV2Thicker.mat
  unity-renderer/Assets/Rendering/UI/ChargeWheel/M_LoadingSpinnerBackgroundBlack.mat
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTIconComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypeIconsAndColors.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypesIcons.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/NFTIcon.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PlayerPassport.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UserContextMenu/Scripts/UserContextMenu.cs
  unity-renderer/Assets/Textures/UI/LANDsIcon.png
  unity-renderer/Assets/Textures/UI/LANDsIcon.png.meta
  unity-renderer/Assets/Textures/UI/NameBackground.png
  unity-renderer/Assets/Textures/UI/NameBackground.png.meta
  unity-renderer/Assets/Textures/UI/Places.png
  unity-renderer/Assets/Textures/UI/Places.png.meta
  unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
Labels: stream-social

#4302 chore: remove @decentraland/explorer-team as CODEOWNER
  .github/CODEOWNERS
Labels: No QA Needed

#4289 fix: sdk7 deprecate base64 textures
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Texture_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/Tests/DCL.ECSComponents.Material.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/Tests/MaterialHandlerShould.cs
Labels: No QA Needed

#4187 fix: sdk7 PlaneShape mesh creation, uvs and texture orientation
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VideoPlayerSystem/ECSVideoPlayerSystem.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/PrimitiveMeshBuilder.cs
Labels: No QA Needed

#4281 chore: remove comms v2
  .circleci/config.yml
  browser-interface/Makefile
  browser-interface/build.js
  browser-interface/package-lock.json
  browser-interface/package.json
  browser-interface/packages/config/index.ts
  browser-interface/packages/shared/comms/sagas.ts
  browser-interface/packages/shared/comms/v2/LighthouseWorldInstanceConnection.ts
  browser-interface/packages/shared/comms/v2/proto/comms.proto
  browser-interface/packages/shared/comms/v2/proto/comms_pb.d.ts
  browser-interface/packages/shared/comms/v2/proto/comms_pb.js
  browser-interface/packages/shared/comms/v2/proto/compile-protobuf.sh
  browser-interface/packages/shared/meta/sagas.ts
  browser-interface/packages/shared/meta/selectors.ts
  browser-interface/packages/shared/meta/types.ts
  browser-interface/packages/shared/scene-loader/sagas.ts
Labels: No QA Needed

#4193 fix: move MessagingController before dependency
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DCL.Runtime.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/Interfaces/IMessagingControllersManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/MessagingControllersManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
Labels: No QA Needed, stream-core

#4208 Add non-allocating `WaitForBoolean`
  unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/AvatarReveal.asmdef
  unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/BaseAvatarReveal.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarSystem.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/WearableRetriever.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/GifProcessor/GifDecoderProcessor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/AvatarEditorHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/TaskUtils.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/TaskUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/Tests/TaskUtilsTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/Tests/TaskUtilsTests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/Tests/WaitForBooleanShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/Tests/WaitForBooleanShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/UniTaskUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/UniTaskUtils.cs.meta
  unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Labels: No QA Needed

#4313 Revert "Add video error load texture (#4144)"
  unity-renderer/Assets/Resources/Textures/VideoFailed.png
  unity-renderer/Assets/Resources/Textures/VideoFailed.png.meta
  unity-renderer/Assets/Resources/Textures/VideoLoading.png
  unity-renderer/Assets/Resources/Textures/VideoLoading.png.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/WebVideoPlayerShould.cs
Labels: No QA Needed

#4278 Chore: removed unused OnGUI event dispatcher
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UpdateEventHandler/IUpdateEventHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UpdateEventHandler/UpdateDispatcher.cs
Labels: No QA Needed

#4318 chore: update from main
  ci-build.sh
  ci-import-avpro.sh
  ci-setup-license.sh
  ci-setup.sh
  unity-renderer/ProjectSettings/ProjectSettings.asset
Labels: No QA Needed

#4196 chore: prevent warning on editor mode
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
Labels: No QA Needed, stream-core

#4084 chore: Refactor Wearables Catalog (Part 1 of 2)
  unity-renderer/Assets/DCLServices/Lambdas/LambdasService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService.meta
  unity-renderer/Assets/DCLServices/WearablesCatalogService/AssemblyInfo.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/AssemblyInfo.cs.meta
  unity-renderer/Assets/DCLServices/WearablesCatalogService/IWearablesCatalogService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/IWearablesCatalogService.cs.meta
  unity-renderer/Assets/DCLServices/WearablesCatalogService/LambdasWearablesCatalogService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/LambdasWearablesCatalogService.cs.meta
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearableResponse.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearableResponse.cs.meta
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearablesCatalogService.asmdef
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearablesCatalogService.asmdef.meta
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearablesCatalogServiceProxy.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearablesCatalogServiceProxy.cs.meta
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearablesWebInterfaceBridge.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearablesWebInterfaceBridge.cs.meta
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WebInterfaceWearablesCatalogService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WebInterfaceWearablesCatalogService.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/TestEnvironment/ServiceLocatorTestFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/TestEnvironment/TestEnvironment.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfigModel.cs
Labels: No QA Needed, stream-social

#4334 chore: faster parallel builds
  .circleci/config.yml
  browser-interface/Makefile
  browser-interface/build.js
  browser-interface/scripts/publish.ts
  browser-interface/scripts/utils.ts
  browser-interface/static/unity.loader.js
  scripts/hash-unity-files.sh
Labels: No QA Needed

#4333 fix: Load texture failed fail gracefully
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/LazyTextureObserver/TextureLoader.cs
Labels: minor, No QA Needed, sentry

#4339 fix: Sentry script busting the cache
  .circleci/config.yml
  scripts/hash-unity-files.sh
Labels: ready for review, No QA Needed, stream-core

#4352 chore: fix merge queue to main to build mac
  .circleci/config.yml
Labels: No QA Needed

#4353 chore: align main
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Profile/ProfileHUDControllerDesktop.cs
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Profile/ProfileHUDViewDesktop_V2.cs
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Profile/ProfileHUDViewDesktop_V2.cs.meta
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Profile/Resources/ProfileHUDDesktop_V2.prefab
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Profile/Resources/ProfileHUDDesktop_V2.prefab.meta
Labels: No QA Needed

#4360 chore: enable sentry on prod
  ci-build.sh
Labels: No QA Needed

#4385 feat: send ethereum network before renderer initializes
  browser-interface/packages/shared/session/sagas.ts
Labels: stream-core

#4386 feat: update lib
  .circleci/config.yml
  browser-interface/package-lock.json
  browser-interface/package.json
  browser-interface/packages/config/index.ts
  browser-interface/packages/entryPoints/index.ts
  browser-interface/packages/lib/browser/persistentStorage.ts
  browser-interface/packages/lib/decentraland/parcels/getTilesRectFromCenter.ts
  browser-interface/packages/lib/decentraland/profiles/transformations/profileToServerFormat.ts
  browser-interface/packages/lib/decentraland/url/resolveBaseUrl.ts
  browser-interface/packages/lib/javascript/humanReadableMillis.ts
  browser-interface/packages/lib/javascript/now.ts
  browser-interface/packages/lib/javascript/spaces.ts
  browser-interface/packages/lib/logger/perf.ts
  browser-interface/packages/lib/redux/index.ts
  browser-interface/packages/lib/redux/waitFor.ts
  browser-interface/packages/lib/redux/waitForAction.ts
  browser-interface/packages/shared/store/store.ts
  browser-interface/packages/shared/web3.ts
Labels: No QA Needed, stream-core

#4388 fix: setRemoteDescription failing on stable
  browser-interface/packages/shared/comms/adapters/voice/loopback.ts
  browser-interface/packages/shared/voiceChat/VoiceCommunicator.ts
Labels: No QA Needed, stream-core

#4387 fix: don't fail on retry realm
  browser-interface/packages/shared/comms/sagas.ts
Labels: No QA Needed, stream-core

#4218 Feat: added favorite button in places card
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/FavoriteButton.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/FavoriteButton.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/HighlightsSubSection/PlaceCard_Long.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/PlacesSubSection/PlaceCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/PlacesSubSection/PlaceCard_Modal.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/PlacesSubSection/PlacesSubSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Favorites.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Favorites/FavoriteButtonComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Favorites/FavoriteButtonComponentModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Favorites/FavoriteButtonComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Favorites/FavoriteButtonComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/PlacesAndEventsCardsFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/PlacesCardsConfigurator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/HighlightsSubSection/HighlightsSubSectionMenu/HighlightsSubSectionComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/HighlightsSubSection/HighlightsSubSectionMenu/HighlightsSubSectionComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/HighlightsSubSection/HighlightsSubSectionMenu/IHighlightsSubSectionComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/FavoritesSubSection/FavoritesSubSectionComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlaceCard/PlaceCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlacesSubSectionMenu/PlacesSubSectionComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExplorePlacesCommonTests.cs
  unity-renderer/Assets/Textures/UI/FavoriteIcon.png
  unity-renderer/Assets/Textures/UI/FavoriteIcon.png.meta
  unity-renderer/Assets/Textures/UI/NotFavoriteIcon.png
  unity-renderer/Assets/Textures/UI/NotFavoriteIcon.png.meta
  unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
Labels: stream-discoverability

#4381 feat: (sdk7 crdt) add append command and use for sending pointer events
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ComponentCrdtWriteSystem/ComponentCrdtWriteSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ComponentCrdtWriteSystem/Tests/ComponentCrdtWriteSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/Extensions/InternalInputEventResultsExtensions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/InputSenderSystem/ECSInputSenderSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/InputSenderSystem/Tests/ECSInputSenderSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECSPointerInputSystemShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/CRDTMessage.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/CRDTProtocol.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/CRDTDeserializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Serializer/CRDTSerializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Serializer/Tests/CRDTSerializerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Tests/CRDTTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Tests/CRDTTestsUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/PointerEventsResult.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentWriter/DCL.ECSRuntime.ComponentWriter.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentWriter/ECSComponentWriter.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentWriter/Interfaces/IECSComponentWriter.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/DCL.ECSRuntime.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/ECSComponentWriterShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/Tests/CRDTServiceShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests/SceneControllerServiceShould.cs
  unity-renderer/Assets/Scripts/Tests/MockingUtils/MockingUtils.cs
Labels: No QA Needed

#4411 fix: move back the lamport-timestamp to the sender pointer input system
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/InputSenderSystem/ECSInputSenderSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
Labels: No QA Needed

#4418 feat: rent map camera controller
  unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/IMapCameraController.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/RentMapCameraController.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/RentMapCameraController.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/MapCameraController.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/MapCameraController/RentMapCameraControllerShould.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/MapCameraController/RentMapCameraControllerShould.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/TestSuite/RentMapCameraControllerExposer.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/TestSuite/RentMapCameraControllerExposer.cs.meta
Labels: No QA Needed

#4416 feat: allow swift shader as debug flag
  browser-interface/packages/config/index.ts
  browser-interface/packages/unity-interface/initializer.ts
Labels: No QA Needed

#4420 refactor: update libs usage
  browser-interface/package-lock.json
  browser-interface/package.json
  browser-interface/packages/config/index.ts
  browser-interface/packages/lib/browser/cache.ts
  browser-interface/packages/lib/browser/isChrome.ts
  browser-interface/packages/lib/javascript/arrayCleanup.ts
  browser-interface/packages/lib/javascript/now.ts
  browser-interface/packages/lib/javascript/stringify.ts
  browser-interface/packages/lib/javascript/uniqBy.ts
  browser-interface/packages/lib/redux/sagaWatch.ts
  browser-interface/packages/shared/comms/adapters/voice/liveKitVoiceHandler.ts
  browser-interface/packages/shared/dao/utils/ping.ts
  browser-interface/packages/shared/ethereum/provider.ts
  browser-interface/packages/shared/loading/sagas.ts
  browser-interface/packages/shared/social/hotScenes.ts
  browser-interface/packages/shared/store/store.ts
  browser-interface/packages/shared/voiceChat/handlers.ts
  browser-interface/packages/shared/voiceChat/logger.ts
  browser-interface/packages/shared/voiceChat/sagas.ts
  browser-interface/packages/shared/voiceChat/utils.ts
  browser-interface/packages/unity-interface/BrowserInterface.ts
  browser-interface/packages/unity-interface/UnityInterface.ts
Labels: No QA Needed

#4401 feat: sdk7 allow media permission
  browser-interface/package-lock.json
  browser-interface/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/DCL.ECSComponents.AudioStream.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/ECSAudioStreamComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests/DCL.ECSComponents.AudioStream.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests/ECSAudioStreamShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/DCL.ECSComponents.Defaults.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBVideoPlayer_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Texture_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/Tests/DCL.ECSComponents.Material.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/Tests/MaterialHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/DCL.ECSComponents.VideoPlayer.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/Tests/DCL.ECSComponents.VideoPlayer.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/Tests/VideoPlayerHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/VideoPlayerHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Utils.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Utils/ECS7Plugin.Utils.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Utils/ECS7Plugin.Utils.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Utils/Scene.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Utils/Scene/Media.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Utils/Scene/Media.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Interfaces/CatalystTypes.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/SceneControllerServiceImpl.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/UnityParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
Labels: No QA Needed

#4372 feat: performance improvements for high end specs and more
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Configs/ResolutionControlConfiguration.asset
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Resources/DesktopGraphicsQualityPresets.asset
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/ResolutionSizeControlController.cs
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/ScreenResolutionUtils.cs
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/WindowModeControlController.cs
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Widgets/GraphicsWidgetDesktop.asset
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/SettingsDesktop/PlayerPrefsDesktopDisplaySettingsRepository.cs
  unity-renderer/Assets/Rendering/Common/ForwardRenderer.asset
  unity-renderer/Assets/Rendering/Common/SkyboxFowrwardRenderer.asset
  unity-renderer/Assets/Rendering/Common/SkyboxFowrwardRenderer.asset.meta
  unity-renderer/Assets/Rendering/Common/UniversalRenderPipelineAsset.asset
  unity-renderer/Assets/Rendering/Outliner/OutlineMaskFeature.cs
  unity-renderer/Assets/Rendering/Outliner/OutlineScreenEffectFeature.cs
  unity-renderer/Assets/Rendering/Outliner/Outliner.asmdef
  unity-renderer/Assets/Rendering/Outliner/Shaders/GaussianBlur.cginc
  unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxCamera.cs
  unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/ShaderQualityControlConfiguration.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/ShaderQualityControlConfiguration.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Widgets/GraphicsWidget.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/ShaderQualityControlController.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/ShaderQualityControlController.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsQualitySettingsRepository.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SettingsControllers.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/ShaderQualityControlController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/ShaderQualityControlController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsData/QualitySettings.cs
Labels: stream-core

#4430 Fix: hide notification area when no notifications are present
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/IMainChatNotificationsComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/MainChatNotificationsComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/ChatNotificationControllerShould.cs
Labels: stream-social

#4437 Hotfix 2023-02-16
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Configs/ResolutionControlConfiguration.asset
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Resources/DesktopGraphicsQualityPresets.asset
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/ResolutionSizeControlController.cs
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/ScreenResolutionUtils.cs
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/WindowModeControlController.cs
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Widgets/GraphicsWidgetDesktop.asset
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/SettingsDesktop/PlayerPrefsDesktopDisplaySettingsRepository.cs
  unity-renderer/Assets/Rendering/Common/ForwardRenderer.asset
  unity-renderer/Assets/Rendering/Common/SkyboxFowrwardRenderer.asset
  unity-renderer/Assets/Rendering/Common/SkyboxFowrwardRenderer.asset.meta
  unity-renderer/Assets/Rendering/Common/UniversalRenderPipelineAsset.asset
  unity-renderer/Assets/Rendering/Outliner/OutlineMaskFeature.cs
  unity-renderer/Assets/Rendering/Outliner/OutlineScreenEffectFeature.cs
  unity-renderer/Assets/Rendering/Outliner/Outliner.asmdef
  unity-renderer/Assets/Rendering/Outliner/Shaders/GaussianBlur.cginc
  unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxCamera.cs
  unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/ShaderQualityControlConfiguration.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/ShaderQualityControlConfiguration.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Widgets/GraphicsWidget.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/ShaderQualityControlController.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/ShaderQualityControlController.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsQualitySettingsRepository.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SettingsControllers.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/ShaderQualityControlController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/ShaderQualityControlController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsData/QualitySettings.cs
Labels: stream-core, release

#4428 refactor: move more things to lib
  browser-interface/packages/entryPoints/index.ts
  browser-interface/packages/entryPoints/loadWebsiteSystems.ts
  browser-interface/packages/lib/browser/isChrome.ts
  browser-interface/packages/lib/browser/persistentStorage.ts
  browser-interface/packages/lib/decentraland/parcels/getTilesRectFromCenter.ts
  browser-interface/packages/lib/decentraland/profiles/transformations/profileToServerFormat.ts
  browser-interface/packages/lib/decentraland/url/resolveBaseUrl.ts
  browser-interface/packages/lib/javascript/humanReadableMillis.ts
  browser-interface/packages/lib/javascript/now.ts
  browser-interface/packages/lib/javascript/spaces.ts
  browser-interface/packages/lib/javascript/stringify.ts
  browser-interface/packages/lib/javascript/uniqBy.ts
  browser-interface/packages/lib/logger/perf.ts
  browser-interface/packages/lib/redux/index.ts
  browser-interface/packages/lib/redux/waitFor.ts
  browser-interface/packages/lib/redux/waitForAction.ts
  browser-interface/packages/shared/comms/adapters/voice/liveKitVoiceHandler.ts
  browser-interface/packages/shared/social/hotScenes.ts
  browser-interface/packages/shared/world/positionThings.ts
  browser-interface/packages/unity-interface/UnityInterface.ts
  browser-interface/test/unit/positionThings.test.tsx
Labels: No QA Needed

#4442 fix: race condition on signup flow
  browser-interface/packages/shared/scene-loader/sagas.ts
Labels: ready for review, stream-core

#4380 refactor: minor cleanup of loading logic
  browser-interface/packages/shared/loading/sagas.ts
  browser-interface/packages/shared/loading/selectors.ts
  browser-interface/packages/shared/loadingScreen/sagas.ts
  browser-interface/packages/shared/loadingScreen/selectors.ts
Labels: ready for review, stream-core

#4296 refactor: GPU Skinning Throttler
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/AvatarShape.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Tests/AvatarShapeShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECS7Plugin.Systems.PointerInput.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECSPointerInputSystemShould.cs
  unity-renderer/Assets/Rendering/Utils/GPUSkinning/GPUSkinningThrottler.cs
  unity-renderer/Assets/Rendering/Utils/GPUSkinning/GPUSkinningThrottler.cs.meta
  unity-renderer/Assets/Rendering/Utils/GPUSkinning/GPUSkinningThrottlerService.cs
  unity-renderer/Assets/Rendering/Utils/GPUSkinning/GPUSkinningThrottlerService.cs.meta
  unity-renderer/Assets/Rendering/Utils/GPUSkinning/Interfaces.meta
  unity-renderer/Assets/Rendering/Utils/GPUSkinning/Interfaces/IGPUSkinningThrottlerService.cs
  unity-renderer/Assets/Rendering/Utils/GPUSkinning/Interfaces/IGPUSkinningThrottlerService.cs.meta
  unity-renderer/Assets/Rendering/Utils/GPUSkinning/Tests/GPUSkinningThrottlerShould.cs
  unity-renderer/Assets/Rendering/Utils/RenderUtils.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Avatar.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarWithHologram.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/AvatarShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/AvatarWithHologramShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
  unity-renderer/Assets/Scripts/Tests/IntegrationTestSuite/IntegrationTestSuite.cs
Labels: tech debt, stream-core, sprint-post-planning

#4476 refactor: single select to increase efficiency of profiles
  browser-interface/packages/shared/profiles/sagas/fetchProfile/index.ts
  browser-interface/test/unit/profiles.saga.test.tsx
Labels: No QA Needed, stream-core

#4338 chore: upload files only uncompressed, and unity artifacts in brotli
  browser-interface/scripts/cdn-uploader-config.yml
  browser-interface/scripts/publish-preview.sh
Labels: No QA Needed
