Repository decentraland/unity-renderer, pull requests merged in 2023-11, with the labels that each got.

#5883 fix: preview mode crash on start
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/EmotesCustomizationComponentView.cs
Labels: No QA Needed

#5891 fix hot reload for smart wearables
  browser-interface/packages/unity-interface/dcl.ts
Labels: No QA Needed

#5900 fix: backpack width is being cut in some resolutions (II)
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/EmotesCustomization/EmotesCustomizationSectionV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/EmotesCustomizationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftTypeIcons.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/BackpackInfoCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearableGridItemView.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearablesSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridComponentView.cs
  unity-renderer/Assets/Textures/UI/BackpackV2/BackpackIcons.spriteatlas
  unity-renderer/Assets/Textures/UI/BackpackV2/BackpackTextures/InfoCardCommon.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/BackpackTextures/InfoCardEpic.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/BackpackTextures/InfoCardLegendary.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/BackpackTextures/InfoCardMythic.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/BackpackTextures/InfoCardRare.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/BackpackTextures/InfoCardUncommon.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/BackpackTextures/InfoCardUnique.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/BackpackTextures/WearablesGradientBackground.png
  unity-renderer/Assets/Textures/UI/BackpackV2/BackpackTextures/WearablesGradientBackground.png.meta
  unity-renderer/Assets/UIComponents/Prefabs/PageSelector.prefab
Labels: No QA Needed

#5923 style: fix avatar creation background width
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
Labels: do not merge

#5930 style: fix amount label horizontal position
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/EmotesCustomization/EmoteCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearableGridItemView.prefab
Labels: ready for review

#5961 Release: 20231120
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarsLODController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/GPUSkinningThrottlingCurve.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/EmotesCustomizationComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/EmotesCustomizationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/IEmotesCustomizationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningNotification.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
Labels: release

#5971 feat: add item id in the equip and unequip wearable analytic
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackAnalyticsService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackAnalyticsService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackAnalyticsServiceShould.cs
Labels: No QA Needed

#5981 fix: sdk7 tween transform parent id overwrite
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/TweenSystem/ECS7Plugin.Systems.ECSTweenSystem.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/TweenSystem/ECSTweenSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/TweenSystem/Tests/ECSTweenSystemShould.cs
Labels: No QA Needed
