Repository decentraland/unity-renderer, pull requests merged in 2023-06, with the labels that each got.

#5193 feat: hint request service and sources
  unity-renderer/Assets/AddressableAssetsData/AddressableAssetSettings.asset
  unity-renderer/Assets/AddressableAssetsData/AssetGroups/LoadingScreen.asset
  unity-renderer/Assets/AddressableAssetsData/AssetGroups/LoadingScreen.asset.meta
  unity-renderer/Assets/AddressableAssetsData/AssetGroups/Schemas/LoadingScreen_BundledAssetGroupSchema.asset
  unity-renderer/Assets/AddressableAssetsData/AssetGroups/Schemas/LoadingScreen_BundledAssetGroupSchema.asset.meta
  unity-renderer/Assets/AddressableAssetsData/AssetGroups/Schemas/LoadingScreen_ContentUpdateGroupSchema.asset
  unity-renderer/Assets/AddressableAssetsData/AssetGroups/Schemas/LoadingScreen_ContentUpdateGroupSchema.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/DCL.LoadingScreenV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/DCL.LoadingScreenV2.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/DCL.LoadingScreenV2.Interfaces.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/DCL.LoadingScreenV2.Interfaces.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/Hint.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/Hint.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/IHintRequestSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/IHintRequestSource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/IHintTextureRequestHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/IHintTextureRequestHandler.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/ISourceWebRequestHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/ISourceWebRequestHandler.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LoadingScreenV2Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LoadingScreenV2Plugin.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LocalHintsContainer.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LocalHintsContainer/LocalHintsSceneJson.json
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LocalHintsContainer/LocalHintsSceneJson.json.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/HintRequestService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/HintRequestService.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/HintSceneParserUtil.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/HintSceneParserUtil.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/HintSourceSourceWebRequestHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/HintSourceSourceWebRequestHandler.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/HintTextureRequestHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/HintTextureRequestHandler.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/LocalHintRequestSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/LocalHintRequestSource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/RemoteHintRequestSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/RemoteHintRequestSource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/SceneHintRequestSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Scripts/SceneHintRequestSource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/HintRequestServiceShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/HintRequestServiceShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/LoadingScreenV2Tests.asmref
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/LoadingScreenV2Tests.asmref.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystem.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/Protocol.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Protocol/UnityParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/MainScripts.asmdef
  unity-renderer/Assets/Scripts/MainScripts/TestsAsmdef/EditModeTests/DCL.EditModeTests.asmdef
Labels: No QA Needed

#5296 fix: avoid logging `OperationCanceledException` exceptions from backpack
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackFiltersController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
Labels: No QA Needed

#5287 Chore: remove beta icon
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/ExploreV2/Resources/ExploreV2MenuDesktop.prefab
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUDDesktop.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/_LoadingScreen.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenView.cs
Labels: stream-discoverability

#5308 fix: guest login on desktop spawns in empty world
  unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxController.cs
Labels: stream-social

#5302 fix: nullRef of MeshRenderer for SDK6 component update
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/BaseAvatar.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BaseShape/BaseShape.cs
Labels: No QA Needed

#5312 fix: `onEnter` and `onLeave` events
  browser-interface/packages/shared/world/parcelSceneManager.ts
Labels: No QA Needed

#5297 fix: close searchbox close icon when thext is empty
  unity-renderer/Assets/UIComponents/Scripts/Components/SearchBar/SearchBarComponentView.cs
  unity-renderer/Assets/UIComponents/Tests/SearchBarComponentViewTests.cs
Labels: stream-social

#5330 chore: upgrade rpc-csharp package
  unity-renderer/Packages/packages-lock.json
Labels: No QA Needed, no_reviewers

#5311 fix: sdk7 audio source SBC and player attachment conflict when re-entering scene
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioSource/AudioSourceRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioSource/DCL.ECSComponents.AudioSource.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioSource/Handler/ECSAudioSourceComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioSource/Tests/ECSAudioSourceIntegrationTests.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioSource/Tests/ECSAudioSourceShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/ECS7Plugin.InternalECSComponents.Interfaces.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/Extensions/InternalSceneBoundsCheckExtensions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentModels.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/SceneBoundsCheckerSystem/ECSSceneBoundsCheckerSystem.cs
Labels: No QA Needed

#5314 feat: sdk7 UI canvas information component
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/DCL.Plugins.ECS7Components.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/ECS7ComponentsComposer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UICanvasInformation.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UICanvasInformation/DCL.ECSComponents.UiCanvasInformation.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UICanvasInformation/DCL.ECSComponents.UiCanvasInformation.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UICanvasInformation/UiCanvasInformationRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UICanvasInformation/UiCanvasInformationRegister.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECS7Plugin.Systems.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiCanvasInformationSystem.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiCanvasInformationSystem/ECS7Plugin.Systems.UiCanvasInformation.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiCanvasInformationSystem/ECS7Plugin.Systems.UiCanvasInformation.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiCanvasInformationSystem/ECSUiCanvasInformationSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiCanvasInformationSystem/ECSUiCanvasInformationSystem.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiCanvasInformationSystem/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiCanvasInformationSystem/Tests/ECS7Plugin.Systems.UiCanvasInformation.Tests.asmref
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiCanvasInformationSystem/Tests/ECS7Plugin.Systems.UiCanvasInformation.Tests.asmref.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiCanvasInformationSystem/Tests/ECSUiCanvasInformationSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiCanvasInformationSystem/Tests/ECSUiCanvasInformationSystemShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Tests/ECS7Plugin.Tests.asmdef
Labels: No QA Needed

#5324 feat: loading screen hints controller
  unity-renderer/Assets/AddressableAssetsData/AssetGroups/LoadingScreen.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/DCL.LoadingScreenV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/HintRequestService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/HintRequestService.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/HintSceneParserUtil.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/HintSceneParserUtil.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/HintSourceSourceWebRequestHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/HintSourceSourceWebRequestHandler.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/HintTextureRequestHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/HintTextureRequestHandler.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/LocalHintRequestSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/LocalHintRequestSource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/RemoteHintRequestSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/RemoteHintRequestSource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/SceneHintRequestSource.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/HintServiceScripts/SceneHintRequestSource.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/IHintView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/IHintView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/IHintViewManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Interfaces/IHintViewManager.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LoadingScreenScripts.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LoadingScreenScripts/HintView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LoadingScreenScripts/HintView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LoadingScreenScripts/HintViewManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LoadingScreenScripts/HintViewManager.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LoadingScreenScripts/LoadingScreenHintsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LoadingScreenScripts/LoadingScreenHintsController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/LoadingScreenV2Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/ResourceFolder.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/ResourceFolder/HintView.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/ResourceFolder/HintView.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/ResourceFolder/LocalHintsSceneJson.json
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/ResourceFolder/LocalHintsSceneJson.json.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsEditMode.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsEditMode/HintRequestServiceShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsEditMode/HintRequestServiceShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsEditMode/HintViewManagerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsEditMode/HintViewManagerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsEditMode/LoadingScreenControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsEditMode/LoadingScreenControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsEditMode/LoadingScreenV2TestsEditMode.asmref
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsEditMode/LoadingScreenV2TestsEditMode.asmref.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsPlayMode.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsPlayMode/LoadingScreenV2PlayModeTests.asmref
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreenV2/Tests/TestsPlayMode/LoadingScreenV2PlayModeTests.asmref.meta
Labels: No QA Needed

#5331 style: settings HUD UI enhancement
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Prefabs/Controls/ControlTemplateBase.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Prefabs/Controls/DropDownSettingsControlTemplate.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Prefabs/Controls/SliderSettingsControlTemplate.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Prefabs/Controls/SpinBoxSettingsControlTemplate.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Prefabs/Controls/ToggleSettingsControlTemplate.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/SettingsPanelHUD.prefab
Labels: ready for review

#5339 chore: enable incremental gc
  unity-renderer/ProjectSettings/ProjectSettings.asset
Labels: No QA Needed

#5336 feat: deploy outfits
  browser-interface/package-lock.json
  browser-interface/package.json
  browser-interface/packages/shared/profiles/actions.ts
  browser-interface/packages/shared/profiles/sagas/handleDeployOutfits.ts
  browser-interface/packages/unity-interface/BrowserInterface.ts
Labels: stream-social

#5347 Chore: updated gltFast, UniTask and shared-dependency packages
  unity-renderer/Packages/packages-lock.json
Labels: No QA Needed

#5355 fix: failing requests because of json conversion incompatibility
  unity-renderer/Assets/DCLServices/Lambdas/LandsService/LandsResponse.cs
  unity-renderer/Assets/DCLServices/Lambdas/NamesService/NamesResponse.cs
  unity-renderer/Assets/DCLServices/Lambdas/PaginatedResponse.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentController.cs
Labels: stream-core

#5357 fix: usage of string comparison not working correctly in webgl
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarSystemUtils.cs
  unity-renderer/Packages/packages-lock.json
Labels: stream-core

#5356 fix: avatar animations in backpack & passport
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Avatar.cs
Labels: stream-core

#5361 fix: emote rarity
  unity-renderer/Assets/DCLServices/EmotesCatalog/EmoteEntityDto.cs
  unity-renderer/Assets/DCLServices/EmotesCatalog/EmotesRequestWeb.cs
Labels: stream-core

#5226 feat: Add request events subscriptions and event updates to server
  browser-interface/packages/shared/chat/sagas.ts
  unity-renderer/Assets/Plugins/websocket-sharp-master/websocket-sharp/WebSocket.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/AllFriendsInitializationMessage.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/AllFriendsInitializationMessage.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendRequest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IClientFriendshipsService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/ISocialApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/ISocialClientProvider.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/ISocialClientProvider.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/MatrixInitializationBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/ProxySocialApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/RPCFriendsApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/RPCSocialApiBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/RPCSocialClientProvider.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/RPCSocialClientProvider.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/FriendsControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/Helpers/FriendsController_Mock.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/RPCSocialApiBridgeShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/ReceivedFriendRequestHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SentFriendRequestHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/ReceivedFriendRequestHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SendFriendRequestHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SentFriendRequestHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendRequestEntry.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendRequestEntryModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendRequestError.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/FriendRequestNotificationModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/MainChatNotificationsComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/ChatNotificationControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/TopNotificationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/SocialBarV1/Addressables/FriendsHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/IUserProfileBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileWebInterfaceBridge.cs
Labels: no_reviewers, stream-social

#5367 fix: sdk7 `GltfContainer` re-add support for skinned meshes colliders
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerCollidersHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/GltfContainerCollidersShould.cs
Labels: No QA Needed

#5378 hotfix: catalyst urls not correctly normalized in worlds
  unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Catalyst.cs
Labels: stream-core

#5383 feat: added a simple gaussian blur compatible with unity UI
  unity-renderer/Assets/Rendering/UI/Blur/Simplified.meta
  unity-renderer/Assets/Rendering/UI/Blur/Simplified/DCL_GaussianBlur.mat
  unity-renderer/Assets/Rendering/UI/Blur/Simplified/DCL_GaussianBlur.mat.meta
  unity-renderer/Assets/Rendering/UI/Blur/Simplified/SimpleGaussianBlur.shader
  unity-renderer/Assets/Rendering/UI/Blur/Simplified/SimpleGaussianBlur.shader.meta
Labels: No QA Needed, no_reviewers, stream-core

#5384 chore: clean console
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/BasicMaterial.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/AssetPromise_GLTFast_Instance.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/AssetPromise_GLTFast_Loader.cs
  unity-renderer/Packages/packages-lock.json
Labels: No QA Needed, stream-core

#5395 fix: avoid to load an empty hud when a realm comes with a null name
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/RealmViewer/RealmRowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/RealmRowComponentViewTests.cs
Labels: stream-social

#5381 Chore: quests refinement
  renderer-protocol/proto/decentraland/renderer/quests/quests.proto
  unity-renderer/Assets/DCLServices/QuestsService/IQuestRewardsResolver.cs
  unity-renderer/Assets/DCLServices/QuestsService/IQuestRewardsResolver.cs.meta
  unity-renderer/Assets/DCLServices/QuestsService/IQuestsService.cs
  unity-renderer/Assets/DCLServices/QuestsService/QuestReward.cs
  unity-renderer/Assets/DCLServices/QuestsService/QuestReward.cs.meta
  unity-renderer/Assets/DCLServices/QuestsService/QuestsService.asmdef
  unity-renderer/Assets/DCLServices/QuestsService/QuestsService.cs
  unity-renderer/Assets/DCLServices/QuestsService/TestScene/QuestServiceTestScene.cs
  unity-renderer/Assets/DCLServices/QuestsService/Tests/QuestsServiceShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/ExploreV2Menu.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/ActiveQuest/ActiveQuest.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/ActiveQuest/ActiveQuestComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/IQuestAnalyticsService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/IQuestAnalyticsService.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/IQuestLogComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestAnalyticsService.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestAnalyticsService.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestCompletedHUD/QuestCompletedComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestCompletedHUD/QuestCompletedHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestDetails/QuestDetailsComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestDetails/QuestDetailsComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestDetails/QuestDetailsSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestDetails/QuestStep Variant.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestLogComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestLogController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestLogController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestLogHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestOfferHUD/QuestStartedPopupHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestReward/QuestReward.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestRewardsResolver.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestRewardsResolver.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/Quests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quests/QuestsPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Quests.gen.cs
Labels: No QA Needed

#5394 chore: add friends analytics parameters
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/ISocialAnalytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/SocialAnalytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/ReportFriendRequestToAnalyticsExtensions.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/ReceivedFriendRequestHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SendFriendRequestHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SentFriendRequestHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/FriendRequestHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SendFriendRequestHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UserContextMenu/Scripts/UserContextMenu.cs
Labels: No QA Needed, stream-core

#5403 fix: green blockers not appearing when AB-NEW-CDN ff is on
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/ContentProvider.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/GlobalScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
Labels: stream-core

#5397 chore: add chat analytic parameters
  browser-interface/packages/shared/analytics/types.ts
  browser-interface/packages/shared/chat/sagas.ts
  browser-interface/packages/shared/types.ts
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatMessage/ChatMessage.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatWindowControllerShould.cs
Labels: No QA Needed, stream-core

#5412 fix: issues with component pooling
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Animator/DCLAnimator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioSource.cs
Labels: stream-core
