Repository decentraland/unity-renderer, pull requests merged in 2023-09, with the labels that each got.

#5673 chore: Update QA review group for auto assign
  .github/auto_assign_config.yml
Labels: No QA Needed

#5680 fix: make the events api endpoints point back to org
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsAPIController.cs
Labels: No QA Needed

#5679 fix: sdk7 systems update execution order
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UpdateEventHandler/UpdateDispatcher.cs.meta
Labels: bug, No QA Needed

#5681 chore: remove forced alphatest from srp batching helper
  unity-renderer/Packages/packages-lock.json
Labels: do not merge

#5684 fix: add isWorld field to the event’s metrics
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/ExploreV2Analytics/ExploreV2Analytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/EventsCardsConfigurator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/PlacesAndEventsCardsFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/IEventsSubSectionComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/SearchSubSection/ISearchSubSectionComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/SearchSubSection/SearchSubSectionComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/SearchSubSection/SearchSubSectionComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/EventsSubSectionComponentControllerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/SearchSubSectionComponentControllerTests.cs
Labels: No QA Needed

#5700 Chore: validation test for correct string comparison
  unity-renderer/Assets/Scripts/Tests/ValidationTests/CodeConventionsTests.cs
  unity-renderer/Assets/Scripts/Tests/ValidationTests/CodeConventionsTests.cs.meta
Labels: No QA Needed

#5709 chore: url params check for debugging in webgl
  unity-renderer/Assets/Plugins/JSFunctions.jslib
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: No QA Needed

#5751 chore: Remove tech leads group as a required reviewers for PR
  .github/auto_assign_config.yml
Labels: No QA Needed

#5753 chore: update review group list for auto assign
  .github/auto_assign_config.yml
Labels: No QA Needed
