Repository decentraland/unity-renderer, pull requests merged in 2023-10, with the labels that each got.

#5770 Feat: navmap analytics for satellite and navigations
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/ExploreV2Analytics/ExploreV2Analytics.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMapChunksLayersController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMapLocationControlsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapVisibilityBehaviour.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Tests/NavMapLocationControlsControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Tests/NavmapTests.asmdef
Labels: No QA Needed

#5769 Chore: navmap cleanup
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/FriendsTrackerInterface/IPlaceCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlaceCard/PlaceCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Navmap.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapToastView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapToastViewController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapVisibilityBehaviour.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Prefabs/CopyPlaceContextMenu.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Prefabs/CopyPlaceContextMenu.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Prefabs/NavmapFullModal.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Prefabs/NavmapToast.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Resources/NavMap.prefab
  unity-renderer/Assets/UIComponents/Scripts/Components/ContextMenu/PlaceCopyContextualMenu.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/ContextMenu/PlaceCopyContextualMenu.cs.meta
Labels: No QA Needed

#5799 feat: add learn more button for content moderation
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ContentModerationHUD/ContentModerationHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ContentModerationHUD/Prefabs/ContentModerationReportingHUD.prefab
Labels: No QA Needed

#5819 fix: sdk7 ui pointer blocking
  scripts/package-lock.json
  scripts/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIAbstractElements/Tests/UIElementHandlerBaseShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIAbstractElements/UIElementHandlerBase.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIDropdown/Tests/UIDropdownShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIInput/Tests/UIInputHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIInput/UIInputHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/UiTextHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UITransform/Tests/UITransformHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UITransform/UITransformHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentModels.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/ECSUiPointerEventsSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/Tests/UiPointerEventsSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/UIElements/Image/DCLImage.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/UiTransform.gen.cs
Labels: do not merge

#5871 fix: POI info button
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Prefabs/NavmapFilters.prefab
Labels: ready for review

#5879 chore: update auto_assign_config.yml
  .github/auto_assign_config.yml
Labels: No QA Needed

#5868 Release: 20231027
  browser-interface/packages/renderer-protocol/inverseRpc/services/analyticsService.ts
  browser-interface/packages/shared/renderer/sagas.ts
  browser-interface/packages/unity-interface/BrowserInterface.ts
  browser-interface/packages/unity-interface/UnityInterface.ts
  browser-interface/packages/unity-interface/delightedSurvey.ts
  renderer-protocol/proto/decentraland/renderer/kernel_services/analytics.proto
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Tween/ECSTweenHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UITransform/Tests/DCL.ECSComponents.UITransform.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UITransform/Tests/DCL.ECSComponents.UITransform.Tests.asmref
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UITransform/Tests/DCL.ECSComponents.UITransform.Tests.asmref.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UITransform/Tests/UITransformHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UITransform/UITransformHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/UiElementUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/ECSUiPointerEventsSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Tests/ECS7Plugin.Tests.asmdef
  unity-renderer/Assets/DCLServices/EmotesCatalog/EmotesRequestWeb.cs
  unity-renderer/Assets/DCLServices/EmotesService/EmoteAnimationLoader.cs
  unity-renderer/Assets/DCLServices/EmotesService/EmotesService.cs
  unity-renderer/Assets/DCLServices/WearablesCatalogService/LambdasWearablesCatalogService.cs
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/ExploreV2/ExploreV2Desktop.asmdef
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/ExploreV2/ExploreV2FeatureDesktop.cs
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/ExploreV2/ExploreV2MenuComponentControllerDesktop.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarEmotesController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/IAnimator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/IAvatarEmotesController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/RealmsInfoBridge/IRealmsInfoBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/RealmsInfoBridge/IRealmsInfoBridge.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/RealmsInfoBridge/RealmsInfoBridge.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/RealmsInfoBridge/RealmsInfoBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/RealmsInfoBridge/RealmsInfoHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/ExploreV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/ExploreV2Feature.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentControllerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/EmotesCustomization/EmotesCustomizationSectionV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/EmotesCustomizationComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/EmotesCustomizationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/IEmotesCustomizationComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEmotesSectionController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ContentModerationHUD/Prefabs/ContentModerationButtonForWorldsHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Prefabs/NavigationPanel.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/ShadowControlController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/SoftShadowsControlController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DebugConfig.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/EmoteClipData.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/SceneEmoteHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/DebugParameters/DebugConfigComponent.cs
  unity-renderer/Assets/Tutorial/Scripts/TutorialController.cs
Labels: release
