Repository decentraland/unity-renderer, pull requests merged in 2023-07, with the labels that each got.

#5431 fix: NRE caused by wearable not converted to AB
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/WearableRetriever.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/SceneAB/AssetPromise_SceneAB.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/ContentProvider.cs
Labels: No QA Needed

#5432 hotfix: remove pooling from Animator and AudioSources
  unity-renderer/Assets/DCLPlugins/CoreComponentsPlugin/Resources/PoolableCoreComponentsFactory.asset
Labels: No QA Needed

#5408 chore: mark flaky test as flaky
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/VideoTextureShould.cs
Labels: No QA Needed, stream-core

#5454 fix: the metric for outfits saving is not being sent
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Outfits/IOutfitsSectionComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Outfits/OutfitsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Outfits/OutfitsSectionComponentView.cs
Labels: No QA Needed

#5415 style: fix profile card scroll bar texture and collectibles scroll view mask
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PlayerPassport.prefab
Labels: ready for review

#5467 fix: social client ws url network dependant
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/RPCSocialClientProvider.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
Labels: No QA Needed, no_reviewers

#5422 feat: hands
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Avatar.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarCurator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarSystemUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/LoaderDefinitions/BodyWearables.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/LoaderDefinitions/BodyWearables.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/LoaderDefinitions/IBodyshapeLoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/LoaderDefinitions/ILoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/LoaderDefinitions/IWearableLoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/LoaderDefinitions/IWearableLoaderFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/WearableItemResolverDefinitions/IAvatarCurator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/BodyShapeLoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/Loader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/WearableLoader.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/WearableLoaderFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/AvatarCuratorShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/AvatarShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/AvatarSystemTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/AvatarWithHologramShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/BaseAvatarShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/BodyshapeLoaderShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/LODShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/LoaderShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/VisibilityShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/WearableLoaderFactoryShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/WearableLoaderShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/AvatarMeshCombinerHelper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftTypeIcons.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftTypePreviewCameraFocusConfig.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorV2Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/AvatarSlotsDefinition.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/AvatarSlotsHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDV2Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Test/ExternalUrlPromptHUDTest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/NFTIcons/NFTTypesIcons.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/FeatureFlags/Data/FeatureFlag.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/Tests/WearableItemShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableLiterals.cs
  unity-renderer/ProjectSettings/QualitySettings.asset
  unity-renderer/TestResources/Avatar/Assets/BaseFemale.glb
Labels: stream-core

#5478 fix: the passport_edit_profile metric stopped sending
  unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/SocialAnalyticsTypes.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/MyAccountHUD/MyAccountHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/MyAccountHUD/MyAccountPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/MyAccountHUD/MyProfileController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/MyAccountHUD/Tests/MyProfileControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/TestsAsmdef/PlayModeTests/DCL.PlaymodeTests.asmdef
Labels: No QA Needed

#5488 fix: the equip wearable metric is not being sent for outfits equipment
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackAnalyticsTypes.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
Labels: No QA Needed

#5495 fix: replace the current health endpoint by the new one
  unity-renderer/Assets/Rendering/ProceduralSkybox/World Timer/WorldTimer.cs
Labels: No QA Needed
