Repository decentraland/unity-renderer, pull requests merged in 2023-03, with the labels that each got.

#4511 fix: typo on gh build commenter
  .github/workflows/main.yml
Labels: No QA Needed, stream-core

#4515 Feat/new map renderer home point
  unity-renderer/Assets/AddressableAssetsData/AssetGroups/Map Renderer.asset
  unity-renderer/Assets/DCLServices/MapRendererV2/Addressables/HomePoint.prefab
  unity-renderer/Assets/DCLServices/MapRendererV2/Addressables/HomePoint.prefab.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/Addressables/SceneOfInterest.prefab
  unity-renderer/Assets/DCLServices/MapRendererV2/Addressables/SceneOfInterest.prefab.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/CommonBehavior.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/CommonBehavior/MapMarkerPoolableBehavior.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/CommonBehavior/MapMarkerPoolableBehavior.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/ColdUsersMarkersInstaller.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/ColdUsersMarkersInstaller.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/HomePointMarkerInstaller.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/HomePointMarkerInstaller.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/HotUsersMarkersInstaller.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/HotUsersMarkersInstaller.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/MapRendererChunkComponentsFactory.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/MapRendererConfiguration.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/MapRendererDrawOrder.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/MapRendererDrawOrder.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/SceneOfInterestsMarkersInstaller.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/SceneOfInterestsMarkersInstaller.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/Culling/MapCullingController.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/Atlas/IChunkController.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/HomePoint.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/HomePoint/HomePointMarker.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/HomePoint/HomePointMarker.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/HomePoint/HomePointMarkerController.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/HomePoint/HomePointMarkerController.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/HomePoint/HomePointMarkerObject.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/HomePoint/HomePointMarkerObject.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/HomePoint/IHomePointMarker.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/HomePoint/IHomePointMarker.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/IMapLayerView.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/IMapLayerView.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/MapLayer.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PointsOfInterest.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PointsOfInterest/ISceneOfInterestMarker.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PointsOfInterest/ISceneOfInterestMarker.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PointsOfInterest/SceneOfInterestMarker.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PointsOfInterest/SceneOfInterestMarker.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PointsOfInterest/SceneOfInterestMarkerObject.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PointsOfInterest/SceneOfInterestMarkerObject.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PointsOfInterest/ScenesOfInterestMarkersController.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PointsOfInterest/ScenesOfInterestMarkersController.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/UsersMarkers/HotArea/HotUserMarker.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapRendererV2.asmdef
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/Factory/MapRendererChunkComponentsFactoryShould.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/HomePoint.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/HomePoint/HomePointMarkerControllerShould.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/HomePoint/HomePointMarkerControllerShould.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/MapRendererShould.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/MapRendererV2Tests.asmdef
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/PointsOfInterest.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/PointsOfInterest/SceneOfInterestMarkerShould.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/PointsOfInterest/SceneOfInterestMarkerShould.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/PointsOfInterest/ScenesOfInterestMarkersControllerShould.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/PointsOfInterest/ScenesOfInterestMarkersControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MinimapMetadata.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MinimapMetadataController.cs
Labels: No QA Needed

#4526 fix: load self-signed cert from base64 and not a file, and add a comm…
  .gitignore
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/CommandLineParserDesktop/CommandLineParserUtils.cs
  unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/SelfCertificateData.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/SelfCertificateData.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/WebSocketCommunication.cs
  unity-renderer/self-signed.pfx
Labels: No QA Needed

#4541 chore: enable incremental gc
  unity-renderer/ProjectSettings/ProjectSettings.asset
Labels: No QA Needed

#4547 chore: skip preview publish for merge queue branches
  browser-interface/scripts/publish-preview.sh
  ci-publish-preview-artifacts.sh
Labels: No QA Needed

#4514 feat: improve saga performance
  browser-interface/packages/entryPoints/loadWebsiteSystems.ts
  browser-interface/packages/gif-processor/processors/gifuct-jsProcessor.ts
  browser-interface/packages/gif-processor/types.ts
  browser-interface/packages/lib/decentraland/profiles/transformations/profileToServerFormat.ts
  browser-interface/packages/lib/logger/getStack.ts
  browser-interface/packages/renderer-protocol/inverseRpc/services/analyticsService.ts
  browser-interface/packages/renderer-protocol/services/crdtService.ts
  browser-interface/packages/shared/analytics/hookAnalyticsObservables.ts
  browser-interface/packages/shared/analytics/trackEvent.ts
  browser-interface/packages/shared/analytics/types.ts
  browser-interface/packages/shared/atlas/sagas.ts
  browser-interface/packages/shared/catalogs/sagas.ts
  browser-interface/packages/shared/chat/sagas.ts
  browser-interface/packages/shared/comms/adapters/LivekitAdapter.ts
  browser-interface/packages/shared/comms/sagas.ts
  browser-interface/packages/shared/dao/pick-realm-algorithm/index.ts
  browser-interface/packages/shared/dao/sagas.ts
  browser-interface/packages/shared/friends/sagas.ts
  browser-interface/packages/shared/friends/utils.ts
  browser-interface/packages/shared/loading/ReportFatalError.ts
  browser-interface/packages/shared/loading/sagas.ts
  browser-interface/packages/shared/meta/sagas.ts
  browser-interface/packages/shared/meta/selectors.ts
  browser-interface/packages/shared/profiles/sagas/content/fetchCatalystProfile.ts
  browser-interface/packages/shared/profiles/sagas/fetchProfile/index.ts
  browser-interface/packages/shared/profiles/sagas/handleDeployProfile.ts
  browser-interface/packages/shared/profiles/sagas/handleSaveLocalAvatar.ts
  browser-interface/packages/shared/realm/connections/BFFConnection.ts
  browser-interface/packages/shared/referral/utils.ts
  browser-interface/packages/shared/renderer/sagas.ts
  browser-interface/packages/shared/scene-loader/sagas.ts
  browser-interface/packages/shared/sceneEvents/sagas.ts
  browser-interface/packages/shared/session/sagas.ts
  browser-interface/packages/shared/social/sagas.ts
  browser-interface/packages/shared/store/metricSaga.ts
  browser-interface/packages/shared/voiceChat/handlers.ts
  browser-interface/packages/shared/voiceChat/sagas.ts
  browser-interface/packages/shared/wearablesPortableExperience/sagas.ts
  browser-interface/packages/shared/world/SceneWorker.ts
  browser-interface/packages/unity-interface/BrowserInterface.ts
  browser-interface/packages/unity-interface/UnityInterface.ts
  browser-interface/packages/unity-interface/initializer.ts
  browser-interface/packages/unity-interface/loader.ts
  browser-interface/test/dao/pick-realm-algorithm/test-utils.ts
  browser-interface/test/index.ts
  browser-interface/test/sceneEvents/comms.spec.ts
  browser-interface/test/sceneEvents/visibleAvatars.spec.ts
  browser-interface/test/unit/catalog.saga.test.tsx
  browser-interface/test/unit/friends.saga.test.ts
  browser-interface/test/unit/profiles.saga.test.tsx
  browser-interface/tsconfig.json
Labels: ready for review, performance, stream-core, priority: mid, sprint-post-planning

#4509 docs: PULL_REQUEST template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: No QA Needed, stream-core

#4478 fix: skybox editor button not visible
  unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Editor/Procedural Skybox/SkyboxEditor.cs
Labels: No QA Needed

#4480 fix: ensure user profiles in social features
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/ReceivedFriendRequestHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SendFriendRequestHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PrivateChatModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
Labels: stream-social

#4573 fix: AB colliders not working because they are not readable on WebGL
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
Labels: stream-core

#4284 chore: added multiplatform dev to docs
  README.md
  docs/multiplatform-in-editor.md
  docs/multiplatform-in-editor/bootstrapper.png
  docs/multiplatform-in-editor/topmenu.png
Labels: No QA Needed

#4571 refactor: sdk7 delay internal components dirty state
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/CrdtExecutorsManager.cs
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/Tests/CrdtExecutorsManagerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Tests/BillboardShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Tests/DCL.ECSComponents.Billboard.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/DCL.ECSComponents.GltfContainer.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/GltfContainerHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/Tests/DCL.ECSComponents.MeshCollider.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/Tests/MeshColliderHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/Tests/DCL.ECSComponents.MeshRenderer.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshRenderer/Tests/MeshRendererHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Tests/DCL.ECSComponents.NFTShape.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/NFTShape/Tests/ECSNFTShapeShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Tests/DCL.Components.ECSRaycastShould.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Tests/ECSRaycastShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/Extensions/InternalCollidersExtensions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/Extensions/InternalRenderersExtensions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/IInternalECSComponent.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/IInternalECSComponents.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/InternalECSComponent.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/InternalECSComponents.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Tests/ECS7Plugin.InternalECSComponents.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Tests/UiContainerHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Tests/WriteSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/InputSenderSystem/Tests/ECS7Plugin.Systems.InputSender.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/InputSenderSystem/Tests/ECSInputSenderSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/MaterialSystem/Tests/ECS7Plugin.Systems.Material.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/MaterialSystem/Tests/ECSMaterialSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECS7Plugin.Systems.PointerInput.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECSPointerInputSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECS7Plugin.Systems.ScenesUiSystem.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECSScenesUiSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VideoPlayerSystem/Tests/ECS7Plugin.Systems.VideoPlayer.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VideoPlayerSystem/Tests/ECSVideoPlayerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem/Tests/ECS7Plugin.Systems.Visibility.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/VisibilitySystem/Tests/ECSVisibilitySystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/ECS7TestScene.cs
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/ECS7TestUtilsScenesAndEntities.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DCL.Runtime.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/DCL.Runtime.Interfaces.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/IParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
Labels: ready for review, stream-sdk

#4527 docs: update documentation to profile unity on desktop and webgl
  browser-interface/.dockerignore
  browser-interface/Dockerfile
  browser-interface/Makefile
  browser-interface/build.js
  browser-interface/docker-compose.yml
  browser-interface/init.sh
  docs/how-to-profile-a-local-unity-build-remotely.md
Labels: No QA Needed

#4611 fix: race condition on PX
  browser-interface/Makefile
  browser-interface/packages/config/index.ts
  browser-interface/packages/lib/decentraland/authentication/signedFetch.ts
  browser-interface/packages/renderer-protocol/inverseRpc/services/signRequestService.ts
  browser-interface/packages/shared/comms/adapters/LivekitAdapter.ts
  browser-interface/packages/shared/comms/sagas.ts
  browser-interface/packages/shared/loading/sagas.ts
  browser-interface/packages/shared/meta/sagas.ts
  browser-interface/packages/shared/portableExperiences/sagas.ts
  browser-interface/packages/shared/renderer/sagas-helper.ts
  browser-interface/test/index.ts
  browser-interface/test/unit/portableExperiences.test.tsx
Labels: ready for review, stream-core

#4592 fix: avatar in ghost mode if an owned emote is not found
  unity-renderer/Assets/DCLServices/EmotesCatalog/EmotesCatalogService.cs
Labels: No QA Needed

#4633 feat: visibility checker for new map
  unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/MapRendererChunkComponentsFactory.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Culling/CameraState.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Culling/CameraState.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/Culling/DummyMapCullingControllerVisibilityChecker.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Culling/IMapCullingVisibilityChecker.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Culling/MapCullingController.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Culling/MapCullingVisibilityChecker.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Culling/MapCullingVisibilityChecker.cs.meta
  unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/IMapCameraControllerInternal.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/MapCameraController.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/Culling/CullingControllerShould.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/MapCameraController/MapCameraControllerShould.cs
  unity-renderer/Assets/DCLServices/MapRendererV2/Tests/TestSuite/MapCullingControllerExposer.cs
Labels: No QA Needed

#4641 fix: several null refs and added better errors for content creators
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadableShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/SceneAB/AssetPromise_SceneAB.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFDownloaderWrapper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/ContentProvider.cs
Labels: stream-core

#4651 Hotfix 2023-03-16
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadableShape.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/SceneAB/AssetPromise_SceneAB.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFDownloaderWrapper.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/ContentProvider.cs
Labels: No QA Needed, no_reviewers

#4649 chore: increase scene timeout to 120
  browser-interface/packages/shared/world/SceneWorker.ts
Labels: No QA Needed

#4670 Fix: fixed clickable coordinates in chat
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Utils/CoordinateUtils.cs
Labels: No QA Needed

#4582 chore: sdk7 ui input text value property
  protocol-gen/package-lock.json
  protocol-gen/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIInput/Tests/UIInputHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIInput/UIInputHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/kernel_services/ClientMutualFriendsKernelService.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/kernel_services/MutualFriendsKernelService.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/MutualFriendsKernel.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/UiInput.gen.cs
Labels: No QA Needed

#4648 feat: spawn point based on teleport position and nearest spawn point
  browser-interface/packages/shared/scene-loader/sagas.ts
  browser-interface/packages/shared/world/positionThings.ts
  browser-interface/test/unit/positionThings.test.tsx
Labels: stream-core

#4642 fix: sdk7 ui input dropdown background color and size
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIDropdown/Resources.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIDropdown/Resources/DCL.UIDropdown.uss
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIDropdown/UIDropdownHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIInput/UIInputHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ScenesUI/DCLDefaultRuntimeTheme.tss
  unity-renderer/Assets/DCLPlugins/ECS7/ScenesUI/DCLDefaultRuntimeTheme.tss.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ScenesUI/ScenesUiPanelSettings.asset
  unity-renderer/Assets/DCLPlugins/ECS7/ScenesUI/Stylesheets.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ScenesUI/Stylesheets/DCL.UIDropdown.uss
  unity-renderer/Assets/DCLPlugins/ECS7/ScenesUI/Stylesheets/DCL.UIDropdown.uss.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ScenesUI/Stylesheets/DCL.UIInput.uss
  unity-renderer/Assets/DCLPlugins/ECS7/ScenesUI/Stylesheets/DCL.UIInput.uss.meta
Labels: No QA Needed

#4674 feat: open ~nearby channel by default when hitting ENTER key
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
Labels: stream-social

#4672 feat: browser-interface for windows and tutorial
  README.md
  browser-interface/Makefile
Labels: No QA Needed, no_reviewers, stream-core

#4716 chore: align main 20230322
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Asset_GLTFast_Loader.cs
Labels: No QA Needed

#4718 fix: sdk7 playground
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/SceneBoundsCheckerSystem/ECSSceneBoundsCheckerSystem.cs
Labels: No QA Needed

#4713 hotfix: nearby chat sequence sorting
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingByTimestamp.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingByTimestamp.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingSequentally.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingSequentally.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/IChatHUDComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
Labels: stream-social

#4735 Hotfix: revert chat timestamp fix
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingByTimestamp.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingByTimestamp.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingSequentally.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingSequentally.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/IChatHUDComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
Labels: No QA Needed

#4736 hotfix: force update when offscreen by feature flag
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerHandler.cs
  unity-renderer/Assets/Rendering/Culling/CullingController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_GLTF.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseSettings_Rendering.cs
Labels: No QA Needed

#4738 chore: align main 20232403
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerHandler.cs
  unity-renderer/Assets/DCLServices/Lambdas/LambdasService.cs
  unity-renderer/Assets/DCLServices/Lambdas/Tests/LambdasServiceShould.cs
  unity-renderer/Assets/Rendering/Culling/CullingController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_GLTF.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseSettings_Rendering.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingByTimestamp.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingByTimestamp.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingSequentally.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingSequentally.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/IChatHUDComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestAsyncOperation.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/WebRequestAsyncOperation.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestExtensions.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/SentryUtils/IWebRequestMonitor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/SentryUtils/SentryUtils.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/SentryUtils/SentryWebRequestMonitor.cs
Labels: No QA Needed

#4732 chore: add action to auto-sync main to dev
  .github/workflows/sync-main-to-dev.yml
Labels: No QA Needed

#4754 hotfix: texture resize with incorrect color format
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFTextureDownloaderWrapper.cs
  unity-renderer/Packages/packages-lock.json
Labels: stream-core

#4679 feat: add members list to the nearby channel
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/NearbyChatChannelHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/NearbyMembersHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/NearbyMembersHUD.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelMembersComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IPublicChatWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/NearbyMembersHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/NearbyMembersHUDController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelMembersComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/NearbyMembersHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/NearbyMembersHUDControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatWindowComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUD.asmdef
Labels: stream-social

#4746 fix: fixed teleport button for future events in explore panel
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard_Long.prefab
Labels: stream-discoverability

#4691 fix: sdk7 video playback
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/ECSAudioStreamComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests/DCL.ECSComponents.AudioStream.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AudioStream/Tests/ECSAudioStreamShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/Tests/MaterialHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/DCL.ECSComponents.VideoPlayer.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/Tests/DCL.ECSComponents.VideoPlayer.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/Tests/VideoPlayerHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/VideoPlayerHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/VideoPlayerRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Utils/Scene/Media.cs
Labels: No QA Needed

#4776 fix: null ref on disposed texture player not being handled well
  unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
Labels: stream-core

#4835 chore: disable physcs 2D auto simulation
  unity-renderer/ProjectSettings/Physics2DSettings.asset
Labels: No QA Needed
