Repository decentraland/unity-renderer, pull requests merged in 2023-04, with the labels that each got.

#4811 fix: null chat notification entries in rare occasions
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/MainChatNotificationsComponentView.cs
Labels: stream-social

#4816 fix: hiccup opening friends hud
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelMembersHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/VoiceChatHUD/VoiceChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileModel.cs
Labels: stream-social

#4800 fix: usernames in chat messages
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatControllerContextMenuUtility.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatMessage/ChatMessage.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntry.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntryModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DateSeparatorEntry.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/IChatHUDComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/DefaultChatEntryShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/IPrivateChatComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Tests/PrivateChatWindowControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChatHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChatChannelWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IPublicChatWindowView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChatChannelHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatWindowControllerShould.cs
Labels: stream-social

#4872 fix: skybox editor on pause
  unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Editor/Procedural Skybox/SkyboxEditor.cs
Labels: No QA Needed

#4855 feat: sdk7 add more component group types
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsGroup/ECSComponentsGroupCouple.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsGroup/ECSComponentsGroupCouple.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsGroup/ECSComponentsGroupTriple.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsGroup/ECSComponentsGroupTriple.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsGroup/ECSComponentsGroupWithoutCouple.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsGroup/ECSComponentsGroupWithoutCouple.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsGroup/ECSComponentsGroupWithoutSingle.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsGroup/ECSComponentsGroupWithoutSingle.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsGroup/Interfaces/ECSComponentsGroupData.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsGroup/Interfaces/IECSComponentsGroup.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsGroup/Interfaces/IECSReadOnlyComponentsGroup.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/ComponentsManager/ECSComponentsManager.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSRuntime/Tests/ECSComponentsGroupShould.cs
Labels: No QA Needed

#4856 fix: sdk7 add pointer events internal component
  unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/ECS7ComponentsComposer.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/DCL.ECSComponents.PointerEvents.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/PointerEventsExtensions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/PointerEventsExtensions.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/PointerEventsHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/PointerEventsHandler.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/PointerEventsRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/Tests/DCL.ECSComponents.PointerEvents.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/Tests/DCL.ECSComponents.PointerEvents.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/Tests/PointerEventsShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/Tests/PointerEventsShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/PointerEvents/UIPointerEventsHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/IInternalECSComponents.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentModels.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentsId.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/InternalECSComponents.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECS7Plugin.Systems.PointerInput.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECSPointerInputSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/SystemsContext/SystemsContext.cs
Labels: No QA Needed

#4857 fix: sdk7 UI pointer events
  unity-renderer/Assets/DCLPlugins/ECS7/ComponentGroups/ComponentGroups.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ComponentGroups/Interfaces/IComponentGroups.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Material/Tests/MaterialHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIComponentsUtils/Tests/UIPointerEventsUtilsShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIComponentsUtils/UIButtonAcceptanceMap.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIComponentsUtils/UIButtonAcceptanceMap.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIComponentsUtils/UIEventSubscription.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIComponentsUtils/UIEventSubscription.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIComponentsUtils/UIEventsSubscriptions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIComponentsUtils/UIEventsSubscriptions.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIComponentsUtils/UIPointerEventsUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VisibilityComponent/Tests/ECSVisibilityComponentShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/IInternalECSComponents.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentModels.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentsId.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/InternalECSComponents.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECS7Plugin.Systems.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/AssemblyInfo.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/AssemblyInfo.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/ECS7.System.UiPointerEvents.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/ECS7.System.UiPointerEvents.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/ECSUiPointerEventsSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/ECSUiPointerEventsSystem.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/Tests/ECS7.System.UiPointerEvents.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/Tests/ECS7.System.UiPointerEvents.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/Tests/UiPointerEventsSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/Tests/UiPointerEventsSystemShould.cs.meta
Labels: No QA Needed

#4761 fix: raycast protocol update
  protocol-gen/package-lock.json
  protocol-gen/package.json
  scripts/package-lock.json
  scripts/package.json
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBRaycast_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBRaycast_Defaults.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/Tests/GltfContainerHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/DCL.ECSComponents.MeshCollider.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/MeshColliderHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/MeshColliderRegister.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/Tests/MeshColliderHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Handler/DCLPlugins.ECSComponents.Raycast.Handler.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Handler/RaycastHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Raycast.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Tests/DCL.Components.ECSRaycastShould.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Tests/DCL.Components.ECSRaycastShould.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Tests/ECSRaycastShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/LayerMaskUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/LayerMaskUtils.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/ProtoConvertUtils.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/Extensions/InternalCollidersExtensions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/Extensions/InternalSceneBoundsCheckExtensions.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/IInternalECSComponents.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentModels.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/Interfaces/InternalECSComponentsId.cs
  unity-renderer/Assets/DCLPlugins/ECS7/InternalECSComponents/InternalECSComponents.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECS7Plugin.Systems.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/InputSenderSystem/ECSInputSenderSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PlayerSystem/ECS7Plugin.Systems.Player.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECS7Plugin.Systems.PointerInput.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECSPointerInputSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/RaycastSystem.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/RaycastSystem/ECS7Plugin.Systems.Raycast.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/RaycastSystem/ECS7Plugin.Systems.Raycast.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/RaycastSystem/ECSRaycastSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/RaycastSystem/ECSRaycastSystem.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/SceneBoundsCheckerSystem/ECSSceneBoundsCheckerSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/SceneBoundsCheckerSystem/OutOfSceneBoundsFeedbackStyle/ECSOutOfSceneBoundsFeedback_EnabledToggle.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/SceneBoundsCheckerSystem/OutOfSceneBoundsFeedbackStyle/ECSOutOfSceneBoundsFeedback_RedWireframe.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/UiPointerEvents/ECSUiPointerEventsSystem.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Configuration/Configuration.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/CameraType.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/InputAction.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/MeshCollider.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/PointerEvents.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/PointerEventsResult.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Raycast.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/RaycastHit.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/RaycastHit.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/RaycastResult.gen.cs
  unity-renderer/ProjectSettings/DynamicsManager.asset
  unity-renderer/ProjectSettings/ProjectSettings.asset
  unity-renderer/ProjectSettings/TagManager.asset
Labels: No QA Needed

#4915 fix: sdk7 billboard
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Tests/BillboardShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Tests/DCL.ECSComponents.Billboard.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBBillboard_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/TextShape/ECSTextShapeComponentHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/BillboardSystem/ECS7Plugin.Systems.ECSBillboardSystem.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/BillboardSystem/ECSBillboardSystem.cs
Labels: No QA Needed

#4936 chore: update SBC documentation ADR-192
  docs/scene-boundaries-checking.md
Labels: No QA Needed

#4892 fix: sdk7 pointer event collider for SkinnedMeshRenderer
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerHandler.cs
Labels: No QA Needed

#4904 fix: sdk7 Sphere MeshCollider
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/MeshColliderHandler.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/Tests/MeshColliderHandlerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/AssetPromise_PrimitiveMesh_Model.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/PrimitiveMeshFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/PrimitiveMeshBuilder.cs
Labels: No QA Needed

#4916 feat: backpack v2 layout & feature flag
  unity-renderer/Assets/DCLServices/WearablesCatalogService/WearablesCatalogServiceProxy.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDPlugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDPlugin.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2ComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2ComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorV2Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorV2Plugin.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackEditorHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackEditorHUDView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDV2Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDV2Tests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Interfaces/IHUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SignupHUD/SignupHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SignupHUD/Tests/SignupHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SignupHUD/Tests/SignupHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Tests/HUDTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystem.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
Labels: stream-social

#4941 chore: revert scene runtime version and fix unity splash screen
  .devcontainer/devcontainer.json
  browser-interface/package-lock.json
  browser-interface/package.json
  browser-interface/packages/shared/apis/host/Testing.ts
  browser-interface/packages/shared/apis/host/index.ts
  unity-renderer/Assets/Scripts/Tests/ValidationTests/SettingAssetsValidationTests.cs
  unity-renderer/ProjectSettings/ProjectSettings.asset
Labels: No QA Needed

#4934 fix: sdk7 ui position and visibility
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/ECSScenesUiSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECS7Plugin.Systems.ScenesUiSystem.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECSScenesUiSystemShould.cs
Labels: No QA Needed

#4924 chore: sdk7 raycast test coverage
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Tests/DCL.ECSComponents.Raycast.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Tests/DCL.ECSComponents.Raycast.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Tests/ECSRaycastHandlerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Raycast/Tests/ECSRaycastHandlerShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/RaycastSystem/ECSRaycastSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/RaycastSystem/Tests.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/RaycastSystem/Tests/ECS7Plugin.Systems.Raycast.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/RaycastSystem/Tests/ECS7Plugin.Systems.Raycast.Tests.asmdef.meta
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/RaycastSystem/Tests/ECSRaycastSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/RaycastSystem/Tests/ECSRaycastSystemShould.cs.meta
  unity-renderer/Assets/DCLPlugins/ECS7/TestsUtils/ECS7TestScene.cs
Labels: No QA Needed

#4959 feat: avatar dynamic slot list for new backpack
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsDefinitionSO.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsDefinitionSO.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsHUDController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/IAvatarSlotComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/IAvatarSlotsView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/IAvatarSlotsView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftTypeIcons.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/AvatarSlot.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/AvatarSlotList.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/AvatarSlotList.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/AvatarSlotSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/AvatarSlotSection.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/AvatarSlotsDefinition.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/AvatarSlotsDefinition.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/SectionSeparator.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/SectionSeparator.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/AvatarSlotComponentViewTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/AvatarSlotsHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/AvatarSlotsHUDControllerShould.cs.meta
Labels: No QA Needed, no_reviewers

#4933 feat: Show old EMOTES section into the new backpack layout + Basic avatar preview
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/EmotesCustomizationComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/IEmotesCustomizationComponentController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/EmotesCustomization/EmotesCustomizationComponentControllerTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2ComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorV2Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEmotesSectionController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEmotesSectionController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackPreviewPanel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackPreviewPanel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackEditorHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackPreviewPanel.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackPreviewPanel.prefab.meta
Labels: stream-social

#4993 feat: Manage the profile's saving in the new BackpackV2
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackAnalyticsController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackAnalyticsController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2ComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorV2Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEmotesSectionController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackPreviewPanel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackEditorHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackEmotesSectionController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackEmotesSectionController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackAnalyticsControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackAnalyticsControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/IUserProfileBridge.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileWebInterfaceBridge.cs
Labels: stream-social

#4996 feat: backpack v2 grid
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2ComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorV2Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IBackpackEditorHUDView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IWearableGridView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IWearableGridView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftBreadcrumbComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftBreadcrumbComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftBreadcrumbModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftBreadcrumbModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftRarity.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftRarity.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftSubCategoryFilterComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftSubCategoryFilterComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftSubCategoryFilterModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftSubCategoryFilterModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/GridPageButton.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/GridPageButton.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/GridPageSelector.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/GridPageSelector.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/NftBreadcrumberSubcategoryFilter.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/NftBreadcrumberSubcategoryFilter.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearableGridItemView.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearableGridItemView.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemModel.cs.meta
  unity-renderer/Assets/UIComponents/Scripts/Components/PageSelector.meta
  unity-renderer/Assets/UIComponents/Scripts/Components/PageSelector/PageSelectorButtonComponentView.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/PageSelector/PageSelectorButtonComponentView.cs.meta
  unity-renderer/Assets/UIComponents/Scripts/Components/PageSelector/PageSelectorButtonModel.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/PageSelector/PageSelectorButtonModel.cs.meta
  unity-renderer/Assets/UIComponents/Scripts/Components/PageSelector/PageSelectorComponentView.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/PageSelector/PageSelectorComponentView.cs.meta
  unity-renderer/Assets/UIComponents/Scripts/Components/PageSelector/PageSelectorModel.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/PageSelector/PageSelectorModel.cs.meta
Labels: stream-social

#4984 Feat: add backpack info card
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftRarityBackground.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftWearableRarityBackground.asset
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftWearableRarityBackground.asset.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/IInfoCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/IInfoCardComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/InfoCardComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/InfoCardComponentModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/InfoCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/InfoCardComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackInfoCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackInfoCard.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/ViewAllWearableInfo.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/ViewAllWearableInfo.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackInfoCardViewTest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackInfoCardViewTest.cs.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/BaseThumbnail.png
  unity-renderer/Assets/Textures/UI/BackpackV2/BaseThumbnail.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/CommonThumbnail.png
  unity-renderer/Assets/Textures/UI/BackpackV2/CommonThumbnail.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/EpicThumbnail.png
  unity-renderer/Assets/Textures/UI/BackpackV2/EpicThumbnail.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/LegendaryThumbnail.png
  unity-renderer/Assets/Textures/UI/BackpackV2/LegendaryThumbnail.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/MythicThumbnail.png
  unity-renderer/Assets/Textures/UI/BackpackV2/MythicThumbnail.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/RareThumbnail.png
  unity-renderer/Assets/Textures/UI/BackpackV2/RareThumbnail.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/UncommonThumbnail.png
  unity-renderer/Assets/Textures/UI/BackpackV2/UncommonThumbnail.png.meta
  unity-renderer/Assets/Textures/UI/BackpackV2/UniqueThumbnail.png
  unity-renderer/Assets/Textures/UI/BackpackV2/UniqueThumbnail.png.meta
  unity-renderer/Assets/UIComponents/Resources/DynamicIconList.prefab
  unity-renderer/Assets/UIComponents/Resources/DynamicIconList.prefab.meta
  unity-renderer/Assets/UIComponents/Scripts/Components/DynamicIconList.meta
  unity-renderer/Assets/UIComponents/Scripts/Components/DynamicIconList/DynamicListComponentView.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/DynamicIconList/DynamicListComponentView.cs.meta
  unity-renderer/Assets/UIComponents/Scripts/Components/DynamicIconList/IDynamicListComponentView.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/DynamicIconList/IDynamicListComponentView.cs.meta
  unity-renderer/Assets/UIComponents/Tests/DynamicIconListComponentViewTests.cs
  unity-renderer/Assets/UIComponents/Tests/DynamicIconListComponentViewTests.cs.meta
Labels: No QA Needed

#5003 Feat: add avatar equip slots animations for interactions
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/AvatarSlot.prefab
Labels: No QA Needed, stream-social

#4977 Feat: new quest tracker ui component
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/IQuestStepComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/IQuestStepComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/IQuestTrackerComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/IQuestTrackerComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/JumpInButton.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/JumpInButton.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestStepComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestStepComponentModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestStepComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestStepComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestTrackerComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestTrackerComponentModel.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestTrackerComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestTrackerComponentView.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestV2.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/QuestV2.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Resources.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Resources/QuestStep.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Resources/QuestStep.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Resources/QuestTrackerHUD.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Resources/QuestTrackerHUD.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestHUDTest.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestHUDTest.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestStepComponentViewTest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestStepComponentViewTest.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestTrackerComponentViewTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Quest_V2/Tests/QuestTrackerComponentViewTests.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/QuestsTrackerHUD/Prefabs/QuestsTrackerEntry.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/QuestsTrackerHUD/Prefabs/QuestsTrackerSection.prefab
Labels: No QA Needed, stream-discoverability

#5013 feat: backpack v2 integration
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDV2ComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorV2Plugin.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/IWearableGridView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/IInfoCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/InfoCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/AvatarSlot.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/AvatarSlot.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/AvatarSlotList.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/AvatarSlotList.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/AvatarSlotSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/AvatarSlotSection.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/BackpackInfoCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/BackpackInfoCard.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/AvatarSlotComponentViewTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackEditorHUDControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/BackpackInfoCardViewTest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridItemComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_BackpackV2.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_BackpackV2.cs.meta
Labels: stream-social

#4997 chore: reworked event card based on new design
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard_Long.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard_Modal.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventsSubSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/EventsCardsConfigurator.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventCard/EventCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/EventCardComponentViewTests.cs
Labels: stream-discoverability

#5032 chore: backpack v2 grid test coverage
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/InfoCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftBreadcrumbComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/NftSubCategoryFilterComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearablesBreadcrumb.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearablesBreadcrumb.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearablesSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearablesSection.prefab.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/NftBreadcrumbComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/NftBreadcrumbComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/NftSubCategoryFilterComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/NftSubCategoryFilterComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridControllerShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridItemComponentViewShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Tests/WearableGridItemComponentViewShould.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridComponentView.cs
  unity-renderer/Assets/UIComponents/Scripts/Components/PageSelector/PageSelectorComponentView.cs
Labels: stream-social

#5009 fix: sdk7 crdt consensus rules
  unity-renderer/Assets/DCLPlugins/ECS7/ComponentCrdtWriteSystem/ComponentCrdtWriteSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ComponentCrdtWriteSystem/Tests/ComponentCrdtWriteSystemShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/CrdtExecutorsManager.cs
  unity-renderer/Assets/DCLPlugins/ECS7/CrdtExecutorsManager/Tests/CrdtExecutorsManagerShould.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Tests/ECS7HotReload.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/CRDTMessage.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/CRDTProtocol.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/CrdtMessage.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/CrdtMessage.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/CRDTDeserializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/Tests/CRDTDeserializerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Executor/CRDTExecutor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Executor/Interface/ICRDTExecutor.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Executor/Tests/CRDTExecutorShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Serializer/CRDTSerializer.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Serializer/Tests/CRDTSerializerShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Tests/CRDTTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Tests/CRDTTestsUtils.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/Tests/KernelBinaryMessageShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/CRDTServiceContext.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTServiceImpl.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/Tests/CRDTServiceShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/SceneControllerServiceImpl.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests/RPC.Services.SceneControllerService.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests/SceneControllerServiceShould.cs
  unity-renderer/TestResources/CRDT/arraybuffer.test
Labels: No QA Needed

#5023 Feat: backpack v2 integration refinement
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/ExploreV2Menu.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/Realms/RealmViewer.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/AvatarSlotsView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/IAvatarSlotComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/IAvatarSlotsView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/IInfoCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/InfoCardComponentModel.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/InfoCard/InfoCardComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/AvatarSlot.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/AvatarSlotList.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/AvatarSlotSection.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/BackpackInfoCard.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/BackpackEditorHUDV2.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Resources/ViewAllWearableInfo.prefab
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridComponentView.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/WearableGridController.cs
  unity-renderer/Assets/Textures/UI/Common/EventsIcon.png
  unity-renderer/Assets/Textures/UI/Common/PlacesIcon.png
  unity-renderer/Assets/UIComponents/Resources/DynamicIconList.prefab
  unity-renderer/Assets/UIComponents/Resources/ProfileCard.prefab
  unity-renderer/Assets/UIComponents/Scripts/Components/DynamicIconList/DynamicListComponentView.cs
Labels: stream-social

#5018 fix: sdk7 primitives radius defaults
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBMeshCollider_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBMeshRenderer_Defaults.cs
  unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/MeshCollider/MeshColliderHandler.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/AssetPromise_PrimitiveMesh_Model.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/PrimitiveMesh/PrimitiveMeshFactory.cs
Labels: No QA Needed

#5033 feat: sdk7 renderer restricted actions
  browser-interface/packages/renderer-protocol/services/restrictedActionsService.ts
  browser-interface/packages/shared/apis/host/RestrictedActions.ts
  browser-interface/packages/shared/renderer/sagas.ts
  browser-interface/packages/shared/renderer/types.ts
  renderer-protocol/proto/decentraland/renderer/renderer_services/restricted_actions.proto
  renderer-protocol/public/renderer-interface.proto
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECS7Plugin.Systems.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECS7Plugin.Systems.PointerInput.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/ECSPointerInputSystem.cs
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECS7Plugin.Systems.PointerInput.Tests.asmdef
  unity-renderer/Assets/DCLPlugins/ECS7/Systems/PointerInputSystem/Tests/ECSPointerInputSystemShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Test/ExternalUrlPromptHUDTest.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Test/ExternalUrlPromptHUDTest.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/NFTPromptHUD.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/NFTPromptHUDController.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/Tests/NFTPromptHUDTests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/Tests/NFTPromptHUDTests.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/ClientRestrictedActionsService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/ClientRestrictedActionsService.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/RestrictedActionsService.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/RestrictedActionsService.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/RestrictedActions.gen.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/RestrictedActions.gen.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/RPCContext.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/RestrictedActionsContext.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Context/RestrictedActionsContext.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/ServerBuilder/RPC.ServerBuilder.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/ServerBuilder/RPCServerBuilder.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/AssemblyInfo.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/AssemblyInfo.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/RPC.Service.RestrictedActions.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/RPC.Service.RestrictedActions.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/RestrictedActionsServiceImpl.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/RestrictedActionsServiceImpl.cs.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/Tests.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/Tests/RPC.Service.RestrictedActions.Tests.asmdef
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/Tests/RPC.Service.RestrictedActions.Tests.asmdef.meta
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/Tests/RestrictedActionsServiceImplShould.cs
  unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/RestrictedActionsService/Tests/RestrictedActionsServiceImplShould.cs.meta
Labels: No QA Needed
